/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSPlaceholderSet : NSMutableSet  {
}

+ (id)mutablePlaceholder;
+ (id)immutablePlaceholder;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (void)initialize;

- (id)init;
- (void)dealloc;
- (id)objectEnumerator;
- (id)initWithCapacity:(unsigned int)arg1;
- (id)initWithObjects:(const id*)arg1 count:(unsigned int)arg2;
- (void)removeObject:(id)arg1;
- (id)member:(id)arg1;
- (void)addObject:(id)arg1;
- (unsigned int)count;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;

@end
