/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSPlaceholderDate : NSDate  {
}

+ (id)immutablePlaceholder;
+ (void)initialize;

- (id)init;
- (void)dealloc;
- (id)initWithTimeIntervalSinceReferenceDate:(double)arg1;
- (double)timeIntervalSinceReferenceDate;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;

@end
