/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSOrderedSetSetProxy : NSSet  {
    id _orderedSet;
}


- (void)dealloc;
- (id)initWithOrderedSet:(id)arg1;
- (id)objectEnumerator;
- (id)member:(id)arg1;
- (unsigned int)count;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
