/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSIsNilTransformer : _NSNegateBooleanTransformer  {
}

+ (BOOL)supportsReverseTransformation;

- (id)description;
- (id)transformedValue:(id)arg1;

@end
