/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class _NSUndoObject;

@interface _NSUndoStack : NSObject  {
    unsigned int _max;
    unsigned int _count;
    unsigned int _nestingLevel;
    _NSUndoObject *_head;
}


- (id)init;
- (void)dealloc;
- (void)removeObject:(id)arg1;
- (void)removeAllObjects;
- (unsigned int)count;
- (id)description;
- (id)_beginMark;
- (void)_removeBottom;
- (void)push:(id)arg1;
- (void)removeAllObjectsWithTarget:(id)arg1;
- (BOOL)popAndInvoke;
- (void)setDiscardable:(BOOL)arg1;
- (void)setGroupIdentifier:(id)arg1;
- (id)groupIdentifier;
- (unsigned int)max;
- (void)markEnd;
- (id)popUndoObject;
- (BOOL)isDiscardable;
- (void)markBegin;
- (void)setMax:(unsigned int)arg1;
- (id)topUndoObject;
- (unsigned int)nestingLevel;

@end
