/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSInvocation;

@interface _NSUndoInvocation : _NSUndoObject  {
    NSInvocation *_invocation;
}


- (void)dealloc;
- (void)invoke;
- (id)description;
- (id)initWithTarget:(id)arg1 invocation:(id)arg2;

@end
