/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSUndoLightInvocation : _NSUndoObject  {
    SEL _selector;
    id _arg;
}


- (void)dealloc;
- (void)invoke;
- (id)description;
- (id)_argument;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;

@end
