/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIActionSheetHostingController : UIViewController  {
    struct CGSize { 
        float width; 
        float height; 
    } _actionSheetSize;
}

@property struct CGSize { float x1; float x2; } actionSheetSize;


- (void)setActionSheetSize:(struct CGSize { float x1; float x2; })arg1;
- (struct CGSize { float x1; float x2; })actionSheetSize;

@end
