/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, UIImageView, UILabel;

@interface _UIAccessDeniedView : UIView  {
    UIImageView *_lockView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    NSString *_title;
    NSString *_message;
}

@property(copy) NSString * title;
@property(copy) NSString * message;


- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)message;
- (void)dealloc;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)setMessage:(id)arg1;
- (id)_textColor;
- (void)layoutSubviews;

@end
