/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSData;

@interface _UIMappedBitmapImage : UIImage  {
    NSData *_data;
}

@property(retain) NSData * data;

+ (void)initialize;

- (void)dealloc;
- (id)data;
- (void)setData:(id)arg1;
- (void)_preheatBitmapData;
- (id)_initWithOtherImage:(id)arg1;

@end
