/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMapTable;

@interface _UIObjectArgumentReplacingProxy : _UITargetedProxy  {
    int _lock;
    NSMapTable *_replacementMap;
}


- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (void)replaceObjectArgument:(id)arg1 with:(id)arg2;

@end
