/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface _UIPopoverViewBackgroundComponentView : UIView  {
    NSString *directionSelector;
}

@property(retain) NSString * directionSelector;


- (void)dealloc;
- (void)setDirectionSelector:(id)arg1;
- (id)directionSelector;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;

@end
