/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UISwappableImageViewAnimationProxy : NSObject  {
    id _originalObject;
}


- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end
