/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIStoryboard;

@interface _UIStoryboardProxy : NSObject  {
    UIStoryboard *_storyboard;
}


- (void)dealloc;
- (id)description;
- (id)initWithStoryboard:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
