/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _UIViewServiceXPCListener, NSMutableArray;

@interface _UIViewServiceSessionManager : NSObject  {
    int _lock;
    NSMutableArray *_sessions;
    _UIViewServiceXPCListener *_listener;
    NSMutableArray *_incomingConnections;
    int _connectionNotificationToken;
}

+ (BOOL)hasActiveSessions;
+ (void)startViewServiceSessionManager;

- (id)init;
- (void)dealloc;
- (void)_registerSessionForDefaultDeputies:(id)arg1;
- (void)_startListener;
- (BOOL)hasActiveSessions;
- (id)_init;

@end
