/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class AAAccount, NSOperationQueue, NSArray, NSMutableArray;

@interface AAAccountManager : NSObject  {
    NSMutableArray *_accounts;
    NSMutableArray *_originalAccounts;
    NSOperationQueue *_requesterQueue;
}

@property(readonly) NSArray * accounts;
@property(readonly) AAAccount * primaryAccount;

+ (id)sharedManager;

- (id)accountWithUsername:(id)arg1;
- (id)accountsEnabledForDataclass:(id)arg1;
- (void)saveAllAccounts;
- (id)primaryAccount;
- (id)accountWithPersonID:(id)arg1;
- (void)removeAccount:(id)arg1;
- (id)accounts;
- (void)addAccount:(id)arg1;
- (void)updateAccount:(id)arg1;
- (id)accountWithIdentifier:(id)arg1;
- (void)reloadAccounts;
- (void).cxx_destruct;

@end
