/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSOperationQueue, AAAccount, MSSearch;

@interface AAAutoAccountVerifier : NSObject <MSSearchDelegate> {
    NSOperationQueue *_requesterQueue;
    MSSearch *_search;
    AAAccount *_account;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _handler;

    int _attempts;
    BOOL _canceled;
}

@property(retain) AAAccount * account;


- (void)verifyWithHandler:(id)arg1;
- (void)sendVerificationEmail;
- (void)_validateToken:(id)arg1;
- (void)_verify;
- (id)initWithAccount:(id)arg1;
- (BOOL)search:(id)arg1 didFindResults:(id)arg2;
- (void)search:(id)arg1 didFinishWithError:(id)arg2;
- (void)setAccount:(id)arg1;
- (id)account;
- (id)init;
- (void).cxx_destruct;
- (void)cancel;

@end
