/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@interface ABDirectoryGroupWrapper : ABGroupWrapper  {
}

+ (id)newDirectoryGroupWrapperWithAccountIdentifier:(id)arg1 store:(void*)arg2 addressBook:(void*)arg3;

- (BOOL)isDirectoryWrapper;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (int)sourceType;

@end
