/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSArray, <ABMembersDataSourceDelegate>, <ABStyleProvider>, NSMutableArray;

@interface ABMembersFilteredDataSource : NSObject <UITableViewDelegate, UITableViewDataSource> {
    NSMutableArray *_records;
    void *_addressBook;
    <ABMembersDataSourceDelegate> *_delegate;
    <ABStyleProvider> *_styleProvider;
}

@property <ABMembersDataSourceDelegate> * delegate;
@property void* addressBook;
@property(retain) <ABStyleProvider> * styleProvider;
@property(readonly) NSArray * records;


- (void)addRecords:(id)arg1;
- (void)removeAllRecords;
- (id)records;
- (id)styleProvider;
- (void)setStyleProvider:(id)arg1;
- (void*)addressBook;
- (void)setAddressBook:(void*)arg1;
- (void)dealloc;
- (unsigned int)count;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)setDelegate:(id)arg1;
- (id)delegate;

@end
