/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class ABPersonViewControllerHelper;

@interface ABPersonViewController_DeletionDelegate : NSObject <UIActionSheetDelegate> {
    ABPersonViewControllerHelper *_controller;
}


- (id)initWithPersonViewController:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;

@end
