/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSString;

@interface ABPersonLinkedInfo : NSObject  {
    NSString *_type;
    NSString *_name;
    void *_person;
    BOOL _unified;
}

@property(retain) NSString * type;
@property(retain) NSString * name;
@property void* person;
@property(getter=isUnified) BOOL unified;


- (void)setUnified:(BOOL)arg1;
- (BOOL)isUnified;
- (void)setType:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)name;
- (id)description;
- (void)setPerson:(void*)arg1;
- (void*)person;
- (id)type;
- (void)setName:(id)arg1;

@end
