/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class UIImage, UIView;

@interface ABPersonIconImageView : UIView  {
    UIView *_imageView;
    int _imageType;
    struct CGSize { 
        float width; 
        float height; 
    } _iconSize;
    UIImage *_maskImage;
    UIImage *_overlayImage;
    id _styleHelper;
}

@property BOOL shouldPickBestImage;
@property(readonly) int imageType;
@property(retain) UIImage * maskImage;
@property(retain) UIImage * overlayImage;

+ (id)genericBlankPlaceholderImageOfSize:(struct CGSize { float x1; float x2; })arg1;
+ (id)newImageViewWithIconSize:(struct CGSize { float x1; float x2; })arg1 imageType:(int)arg2;
+ (struct CGSize { float x1; float x2; })optimalIconSize;
+ (id)_placeholderCompanyImageForType:(int)arg1 size:(struct CGSize { float x1; float x2; })arg2;
+ (id)_placeholderPersonImageForType:(int)arg1 size:(struct CGSize { float x1; float x2; })arg2;
+ (BOOL)_cardPlaceholderImageShouldApplyMaskAndOverlayForType:(int)arg1;
+ (id)rightBorderOverlayImageOfSize:(struct CGSize { float x1; float x2; })arg1;
+ (id)leftRightBorderOverlayImageOfSize:(struct CGSize { float x1; float x2; })arg1;

- (id)_placeholderCompanyImage;
- (id)_placeholderPersonImage;
- (BOOL)_cardPlaceholderImageShouldApplyMaskAndOverlay;
- (id)_overlayImageOrNSNull;
- (id)_maskImageOrNSNull;
- (void)setNeedsRecompositing;
- (int)imageType;
- (id)initWithIconSize:(struct CGSize { float x1; float x2; })arg1 imageType:(int)arg2;
- (void)setShouldPickBestImage:(BOOL)arg1;
- (BOOL)shouldPickBestImage;
- (BOOL)hasImageToDisplay;
- (void)setDisplayedPerson:(void*)arg1;
- (void)setNeedsReload;
- (id)personImageView;
- (void*)displayedPerson;
- (id)overlayImage;
- (id)maskImage;
- (void)setOverlayImage:(id)arg1;
- (void)setMaskImage:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)_updateImages;

@end
