/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@interface ABTableViewHelper : NSObject  {
}

+ (void)prepareCell:(id)arg1 asSelectedCell:(BOOL)arg2 styleProvider:(id)arg3;
+ (void)syncTableView:(id)arg1 withIndexPath:(id)arg2 animated:(BOOL)arg3 styleProvider:(id)arg4;
+ (id)newOverlayLabel;


@end
