/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@class NSString, NSMutableArray;

@interface ABVCardParameter : NSObject  {
    NSString *_name;
    NSString *_grouping;
    id _value;
    NSMutableArray *_types;
    BOOL _primary;
}


- (BOOL)isPrimary;
- (void)addType:(id)arg1;
- (void)addTypes:(id)arg1;
- (void)setGrouping:(id)arg1;
- (void)setIsPrimary:(BOOL)arg1;
- (id)types;
- (id)grouping;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)name;
- (void)finalize;
- (id)description;
- (void)setValue:(id)arg1;
- (id)value;

@end
