/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class UIBarButtonItem;

@interface ABVibrationPickerViewController : ABPickerViewController  {
    id _vibrationPickerViewController;
    BOOL _canEnterEditingMode;
    UIBarButtonItem *_saveButton;
}

@property(readonly) id vibrationPickerViewController;
@property(setter=_setSaveButton:,retain) UIBarButtonItem * _saveButton;


- (id)initWithVibrationType:(int)arg1;
- (id)_saveButton;
- (id)vibrationPickerViewController;
- (void)_setSaveButton:(id)arg1;
- (void)_vibrationSaveButtonClicked:(id)arg1;
- (float)ab_heightToFitForViewInPopoverView;
- (void)dealloc;
- (void)_getRotationContentSettings:(struct { BOOL x1; BOOL x2; BOOL x3; BOOL x4; float x5; int x6; }*)arg1;
- (void)loadView;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;

@end
