/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

@class ACDAuthenticationHandlerQueueManager, NSSet;

@interface ACDAuthenticationPluginManager : NSObject  {
    ACDAuthenticationHandlerQueueManager *_handlerManager;
    NSSet *_pluginBundles;
    struct dispatch_queue_s { } *_authenticationPluginQueue;
    struct dispatch_semaphore_s { } *_authPluginSemaphore;
}

@property(readonly) NSSet * pluginBundles;


- (id)pluginBundles;
- (void)verifyCredentialsForAccount:(id)arg1 client:(id)arg2 handler:(id)arg3;
- (id)pluginForAccountType:(id)arg1;
- (void)promptUserForCredentialsWithAccount:(id)arg1 handler:(id)arg2;
- (void)renewCredentialsForAccount:(id)arg1 accountStore:(id)arg2 handler:(id)arg3;
- (void)verifyCredentialsForAccount:(id)arg1 client:(id)arg2 saveWhenAuthorized:(BOOL)arg3 handler:(id)arg4;
- (id)init;
- (void)dealloc;
- (void).cxx_destruct;

@end
