/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

@class NSPersistentStoreCoordinator, ACDDatabase, NSManagedObjectContext;

@interface ACDDatabaseMigrator : NSObject  {
    NSManagedObjectContext *_migrationContext;
    NSPersistentStoreCoordinator *_coordinator;
    ACDDatabase *_database;
}


- (id)_compatibleModelForStoreAtURL:(id)arg1;
- (id)_fetchAllAuthorizationEntitiesForModelVersion:(int)arg1;
- (void)_migrateAccessAuthorizationsToTCCFromModelVersion:(int)arg1;
- (int)_versionForModel:(id)arg1;
- (id)_setUpContextForMigration;
- (id)initForDatabase:(id)arg1;
- (void).cxx_destruct;
- (BOOL)run;

@end
