/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Accounts.framework/Accounts
 */

@class ACAccount, XPCProxy<ACDOAuthSignerProtocol>;

@interface ACOAuthSigner : NSObject <XPCProxyTarget> {
    XPCProxy<ACDOAuthSignerProtocol> *oauthSignerProxy;
    struct dispatch_queue_s { } *connectionQueue;
    struct _xpc_connection_s { } *connection;
    ACAccount *_account;
    BOOL _shouldIncludeAppIdInRequest;
}

@property BOOL shouldIncludeAppIdInRequest;


- (id)signedURLRequestWithURLRequest:(id)arg1 applicationID:(id)arg2 timestamp:(id)arg3;
- (id)initWithAccount:(id)arg1;
- (BOOL)shouldIncludeAppIdInRequest;
- (id)signedURLRequestWithURLRequest:(id)arg1;
- (id)signedURLRequestWithURLRequest:(id)arg1 callingPID:(id)arg2 timestamp:(id)arg3;
- (void)setShouldIncludeAppIdInRequest:(BOOL)arg1;
- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
- (void)dealloc;
- (void).cxx_destruct;

@end
