/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class BBBulletin;

@interface AFBulletin : NSObject  {
    BBBulletin *_bulletin;
    BOOL _read;
}

@property(getter=isRead) BOOL read;
@property(retain) BBBulletin * bulletin;


- (void)setRead:(BOOL)arg1;
- (void)setBulletin:(id)arg1;
- (id)bulletin;
- (BOOL)isRead;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;

@end
