/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class DKConnection;

@interface AFSettingsConnection : NSObject  {
    DKConnection *_connection;
}


- (void)killDaemon;
- (void)saveAccount:(id)arg1 setActive:(BOOL)arg2;
- (void)setDictationEnabled:(BOOL)arg1;
- (void)barrier;
- (void)setAssistantEnabled:(BOOL)arg1;
- (void)_sendMessage:(id)arg1 withReplySync:(id)arg2;
- (void)_sendMessage:(id)arg1 withReply:(id)arg2;
- (void)_clearConnection;
- (void)setActiveAccountIdentifier:(id)arg1;
- (id)accounts;
- (void)deleteAccountWithIdentifier:(id)arg1;
- (void)dealloc;
- (void).cxx_destruct;
- (void)fetchSupportedLanguageCodes:(id)arg1;
- (id)_connection;

@end
