/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class NSArray;

@interface AFSpeechPhrase : NSObject  {
    NSArray *_interpretations;
    BOOL _isLowConfidence;
}

@property(copy) NSArray * interpretations;
@property BOOL isLowConfidence;


- (void)setInterpretations:(id)arg1;
- (void)setIsLowConfidence:(BOOL)arg1;
- (BOOL)isLowConfidence;
- (id)dkPlistRepresentation;
- (id)initWithDKPlistRepresentation:(id)arg1;
- (void).cxx_destruct;
- (id)interpretations;

@end
