/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
 */

@class ALAssetRepresentationPrivate;

@interface ALAssetRepresentation : NSObject  {
    id _internal;
}

@property(retain) ALAssetRepresentationPrivate * internal;


- (int)_fileDescriptor;
- (struct CGImage { }*)CGImageWithOptions:(id)arg1;
- (struct CGImage { }*)CGImageWithOptions:(id)arg1 format:(int)arg2 bakeInOrientation:(int)arg3;
- (id)_imageData;
- (id)initWithManagedAsset:(id)arg1 sidecar:(id)arg2 extension:(id)arg3 library:(id)arg4;
- (void)setInternal:(id)arg1;
- (id)internal;
- (struct CGSize { float x1; float x2; })dimensions;
- (id)metadata;
- (long long)size;
- (void)dealloc;
- (BOOL)isValid;
- (id)description;
- (struct CGImage { }*)fullScreenImage;
- (unsigned int)getBytes:(char *)arg1 fromOffset:(long long)arg2 length:(unsigned int)arg3 error:(id*)arg4;
- (struct CGImage { }*)fullResolutionImage;
- (id)UTI;
- (int)orientation;
- (id)filename;
- (id)url;
- (float)scale;

@end
