/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class ClassDisplayVC, AllClasses, UITabBarController, UIWindow, HTTPServer, ObjectsTVC;

@interface AppDelegate : NSObject <UIApplicationDelegate, UITabBarControllerDelegate> {
    UIWindow *window;
    UITabBarController *tabBarController;
    ObjectsTVC *objectsTVC;
    ClassDisplayVC *classDisplayVC;
    HTTPServer *httpServer;
    AllClasses *allClasses;
}

@property(retain) AllClasses * allClasses;
@property(retain) UIWindow * window;
@property(retain) UITabBarController * tabBarController;
@property(retain) ClassDisplayVC * classDisplayVC;
@property(retain) ObjectsTVC * objectsTVC;


- (id)window;
- (void)dealloc;
- (id)tabBarController;
- (void)setWindow:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)setObjectsTVC:(id)arg1;
- (id)objectsTVC;
- (void)setTabBarController:(id)arg1;
- (id)allClasses;
- (void)dismissModalView:(id)arg1;
- (void)showHeaderForClassName:(id)arg1;
- (unsigned short)serverPort;
- (id)responseForPath:(id)arg1;
- (id)myIPAddress;
- (void)useClass:(id)arg1;
- (id)httpServer;
- (id)classDisplayVC;
- (void)startWebServer;
- (void)setAllClasses:(id)arg1;
- (id)htmlIndex;
- (void)setClassDisplayVC:(id)arg1;

@end
