/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
 */

@class NSDictionary, NSMutableDictionary, NSString;

@interface APSMessage : NSObject <NSCoding> {
    NSMutableDictionary *_plist;
}

@property(retain) NSString * topic;
@property(retain) NSDictionary * userInfo;
@property unsigned int identifier;


- (id)initWithTopic:(id)arg1 userInfo:(id)arg2;
- (id)topic;
- (void)setTopic:(id)arg1;
- (void)dealloc;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)userInfo;
- (id)objectForKey:(id)arg1;
- (void)setUserInfo:(id)arg1;
- (void)setIdentifier:(unsigned int)arg1;
- (unsigned int)identifier;
- (id)initWithDictionary:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
