/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
 */

@interface APSOutgoingMessage : APSMessage  {
}

@property unsigned int timeout;
@property(getter=isCritical) BOOL critical;
@property int payloadFormat;
@property unsigned int payloadLength;


- (void)setPayloadLength:(unsigned int)arg1;
- (unsigned int)payloadLength;
- (int)payloadFormat;
- (void)setTimedOut:(BOOL)arg1;
- (BOOL)hasTimedOut;
- (void)setSent:(BOOL)arg1;
- (BOOL)wasSent;
- (BOOL)isCritical;
- (void)setCritical:(BOOL)arg1;
- (void)setPayloadFormat:(int)arg1;
- (BOOL)wasCancelled;
- (void)setMessageID:(unsigned int)arg1;
- (unsigned int)messageID;
- (unsigned int)timeout;
- (void)setTimestamp:(id)arg1;
- (id)timestamp;
- (void)setCancelled:(BOOL)arg1;
- (void)setTimeout:(unsigned int)arg1;

@end
