/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@class NSMutableArray;

@interface AVArrayQueueFeeder : AVQueueFeeder  {
    NSMutableArray *_items;
}


- (void)shuffleWithCurrentIndex:(unsigned int)arg1;
- (id)itemForIndex:(unsigned int)arg1;
- (id)pathAtIndex:(unsigned int)arg1;
- (unsigned int)numberOfPaths;
- (unsigned int)itemCount;
- (id)init;
- (void)dealloc;
- (id)initWithArray:(id)arg1;
- (void)removeObjectAtIndex:(unsigned int)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;

@end
