/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, NSDictionary, AVAssetReaderAudioMixOutputInternal, AVAudioMix;

@interface AVAssetReaderAudioMixOutput : AVAssetReaderOutput  {
    AVAssetReaderAudioMixOutputInternal *_audioMixOutputInternal;
}

@property(readonly) NSArray * audioTracks;
@property(readonly) NSDictionary * audioSettings;
@property(copy) AVAudioMix * audioMix;

+ (id)assetReaderAudioMixOutputWithAudioTracks:(id)arg1 audioSettings:(id)arg2;

- (struct opaqueMTAudioProcessingTap { }*)_audioTapProcessorForTrack:(id)arg1;
- (id)_audioVolumeCurveForTrack:(id)arg1;
- (void)_setAudioTapProcessor:(struct opaqueMTAudioProcessingTap { }*)arg1 forTrack:(id)arg2;
- (void)_setAudioVolumeCurve:(id)arg1 forTrack:(id)arg2;
- (id)audioSettings;
- (id)initWithAudioTracks:(id)arg1 audioSettings:(id)arg2;
- (id)audioTracks;
- (BOOL)_enableTrackExtractionReturningError:(id*)arg1;
- (void)setAudioMix:(id)arg1;
- (id)audioMix;
- (id)_asset;
- (id)mediaType;
- (id)init;
- (void)dealloc;
- (void)finalize;
- (id)description;

@end
