/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetWriterUnknownHelper : AVAssetWriterHelper  {
    short _alternateGroupID;
}


- (BOOL)_canAddInputGroup:(id)arg1 exceptionReason:(id*)arg2;
- (BOOL)_canAddInput:(id)arg1 exceptionReason:(id*)arg2;
- (id)initWithConfigurationState:(id)arg1;
- (void)cancelWriting;
- (void)startWriting;
- (void)addInputGroup:(id)arg1;
- (BOOL)canAddInputGroup:(id)arg1;
- (id)initWithURL:(id)arg1 fileType:(id)arg2;
- (void)setMovieTimeScale:(int)arg1;
- (void)setShouldOptimizeForNetworkUse:(BOOL)arg1;
- (BOOL)canAddInput:(id)arg1;
- (void)setMovieFragmentInterval:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (void)addInput:(id)arg1;
- (void)setMetadata:(id)arg1;
- (int)status;

@end
