/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSObject<OS_dispatch_queue>, <AVAssetResourceLoaderDelegate>, AVWeakReference;

@interface AVAssetResourceLoaderInternal : NSObject  {
    AVWeakReference *weakReference;
    AVWeakReference *weakReferenceToAsset;
    struct OpaqueFigAsset { } *figAsset;
    NSObject<OS_dispatch_queue> *stateQueue;
    <AVAssetResourceLoaderDelegate> *delegate;
    NSObject<OS_dispatch_queue> *delegateQueue;
}



@end
