/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVAsset, AVAssetTrackInternal;

@interface AVAssetTrack : NSObject <NSCopying, AVAsynchronousKeyValueLoading> {
    AVAssetTrackInternal *_track;
}

@property(readonly) AVAsset * asset;
@property(readonly) int trackID;

+ (id)keyPathsForValuesAffectingTimeRange;
+ (id)mediaTypesForMediaCharacteristics;

- (BOOL)_hasMultipleNonEmptyEdits;
- (id)_mostCloselyAssociatedTrackAmongTracks:(id)arg1;
- (id)_followingTrackAmongTracks:(id)arg1;
- (id)_fallbackTrack;
- (BOOL)_subtitleFormatDescriptionMatchesTextDisplayFlags:(unsigned int)arg1 flagsMask:(unsigned int)arg2;
- (id)_assetTrackInspector;
- (id)_pairedForcedOnlySubtitlesTrack;
- (id)_allReferencedTracksWithReferenceType:(id)arg1;
- (id)_firstReferencedTrackWithReferenceType:(id)arg1;
- (BOOL)isExcludedFromAutoselectionInTrackGroup;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })samplePresentationTimeForTrackTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (id)segmentForTrackTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (id)segments;
- (float)nominalFrameRate;
- (struct CGSize { float x1; float x2; })dimensions;
- (id)extendedLanguageTag;
- (float)estimatedDataRate;
- (id)mediaCharacteristics;
- (long long)totalSampleDataLength;
- (BOOL)isSelfContained;
- (id)formatDescriptions;
- (id)_initWithAsset:(id)arg1 trackID:(int)arg2 trackIndex:(long)arg3;
- (BOOL)hasMediaCharacteristics:(id)arg1;
- (struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })timeRange;
- (id)_initWithAsset:(id)arg1 trackIndex:(long)arg2;
- (id)_initWithAsset:(id)arg1 trackID:(int)arg2;
- (int)statusOfValueForKey:(id)arg1;
- (BOOL)isPlayable;
- (int)trackID;
- (id)metadataForFormat:(id)arg1;
- (id)availableMetadataFormats;
- (id)commonMetadata;
- (BOOL)hasMediaCharacteristic:(id)arg1;
- (int)naturalTimeScale;
- (struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; })preferredTransform;
- (float)preferredVolume;
- (void)loadValuesAsynchronouslyForKeys:(id)arg1 completionHandler:(id)arg2;
- (int)statusOfValueForKey:(id)arg1 error:(id*)arg2;
- (id)mediaType;
- (int)layer;
- (BOOL)isEnabled;
- (id)init;
- (void)dealloc;
- (id)locale;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)finalize;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (struct CGSize { float x1; float x2; })naturalSize;
- (id)languageCode;
- (id)asset;

@end
