/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSDictionary, NSURLRequest, AVAssetResourceLoader;

@interface AVAssetResourceLoadingRequestInternal : NSObject  {
    AVAssetResourceLoader *resourceLoader;
    NSDictionary *requestDictionary;
    NSURLRequest *URLRequest;
    unsigned char finished;
}



@end
