/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSObject<OS_dispatch_queue>, <AVCaptureAudioDataOutputSampleBufferDelegate>;

@interface AVCaptureAudioDataOutputInternal : NSObject  {
    <AVCaptureAudioDataOutputSampleBufferDelegate> *delegate;
    NSObject<OS_dispatch_queue> *clientQueue;
}


- (void)dealloc;

@end
