/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVCaptureDeviceInput, AVCaptureDeviceFormat;

@interface AVCaptureDeviceInternal : NSObject  {
    int _openRefCount;
    int _configLockRefCount;
    int _configLockPid;
    BOOL _usingDevice;
    AVCaptureDeviceFormat *_activeFormat;
    AVCaptureDeviceInput *_activeInput;
}



@end
