/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVCaptureDeviceFormatInternal, NSString;

@interface AVCaptureDeviceFormat : NSObject  {
    AVCaptureDeviceFormatInternal *_internal;
}

@property(readonly) NSString * mediaType;
@property(readonly) struct opaqueCMFormatDescription { }* formatDescription;
@property(readonly) NSArray * videoSupportedFrameRateRanges;

+ (id)_stringForFormatDescription:(struct opaqueCMFormatDescription { }*)arg1 frameRateRanges:(id)arg2;
+ (id)deviceFormatWithDictionary:(id)arg1 mediaType:(id)arg2 mediaSubType:(int)arg3;
+ (void)initialize;

- (int)supportedStabilizationMethod;
- (BOOL)isBinned;
- (BOOL)hasBinned;
- (id)initWithDictionary:(id)arg1 mediaType:(id)arg2 mediaSubType:(int)arg3;
- (id)videoSupportedFrameRateRanges;
- (BOOL)supportsLowLightBoost;
- (struct opaqueCMFormatDescription { }*)formatDescription;
- (id)mediaType;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end
