/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

@class FetchICEDataOp, NSString, IMExtendedOperation, IMAVChatParticipant, NSDictionary, NSMutableDictionary;

@interface AVChatNegotiationOp : IMExtendedOperation  {
    NSMutableDictionary *_result;
    FetchICEDataOp *_fetchICEDataOp;
    IMAVChatParticipant *_participant;
    IMExtendedOperation *_ardChannelOp;
    NSString *_conferenceID;
    NSDictionary *_extraContext;
    unsigned int _useICE : 1;
    unsigned int _shouldWaitForWifi : 1;
    unsigned int _showNetworkOptions : 1;
}


- (id)initWithParticipant:(id)arg1 conferenceID:(id)arg2 shouldWaitForWifi:(BOOL)arg3 shouldShowNetworkOptions:(BOOL)arg4;
- (void)createChildOperations;
- (void)dealloc;

@end
