/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSLocale, NSString, NSDictionary;

@interface AVMetadataItemInternal : NSObject  {
    struct OpaqueFigMetadataReader { } *reader;
    long itemIndex;
    NSString *keySpace;
    id key;
    NSString *commonKey;
    NSLocale *locale;
    id value;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    } time;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    } duration;
    NSDictionary *extras;
}



@end
