/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPlayerLayerSubtitleLayer : AVSubtitleLayer  {
}

+ (id)defaultActionForKey:(id)arg1;

- (id)actionForKey:(id)arg1;

@end
