/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface AVPropertyStorage : NSObject  {
    NSObject<OS_dispatch_queue> *_storageAccessWorkQueue;
    NSMutableDictionary *_propertyStorage;
}


- (id)objectForKey:(id)arg1 defaultObjectBlock:(id)arg2;
- (void)didAccessKVOForKey:(id)arg1;
- (void)willAccessKVOForKey:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)finalize;

@end
