/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface AVSubtitleLayerUsingWebKit : CALayer  {
    struct AVSubtitleLayerUsingWebKitPrivate { struct __GSFont {} *x1; struct __CFAttributedString {} *x2; } *_priv;
}


- (void)clearSubtitle;
- (void)setSubtitleString:(struct __CFAttributedString { }*)arg1 forced:(BOOL)arg2;
- (void)drawInContext:(struct CGContext { }*)arg1;
- (id)init;
- (void)dealloc;

@end
