/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVSynchronizedLayerInternal, AVPlayerItem;

@interface AVSynchronizedLayer : CALayer  {
    AVSynchronizedLayerInternal *_syncLayer;
}

@property(retain) AVPlayerItem * playerItem;

+ (id)synchronizedLayerWithPlayerItem:(id)arg1;

- (void)setPlayerItem:(id)arg1;
- (id)playerItem;
- (void)layerDidBecomeVisible:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (void)finalize;

@end
