/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AccountSettings.framework/AccountSettings
 */

@class <AccountRefreshProtocol>, <AccountFullAccountProtocol>, NSDictionary, BasicAccount, NSMutableDictionary;

@interface BasicAccount : NSObject <AccountFullAccountProtocol> {
    NSDictionary *_originalProperties;
    NSMutableDictionary *_properties;
    <AccountFullAccountProtocol> *_fullAccount;
    <AccountRefreshProtocol> *_syncAccount;
    BasicAccount *_parentAccount;
}

@property(retain) NSDictionary * originalProperties;

+ (id)_accountCreationMap;
+ (id)_dataclassesProperties;
+ (id)_creatorsInfo;
+ (BOOL)userConfirmationIsRequiredByDataclass:(id)arg1;
+ (BOOL)displayToggleForDataclass:(id)arg1;
+ (BOOL)showRemindersSeparatelyForAccountType:(id)arg1;
+ (id)deleteAccountActionsForAccountType:(id)arg1;
+ (id)userActionsToDisableDataclass:(id)arg1 forAccountType:(id)arg2;
+ (id)userActionsToEnableDataclass:(id)arg1 forAccountType:(id)arg2;
+ (id)allSupportedDataclasses;
+ (id)accountWithProperties:(id)arg1;
+ (id)accountWithType:(id)arg1 class:(id)arg2;
+ (id)createNewAccountUID;
+ (BOOL)_isValidAccountType:(id)arg1;
+ (id)removeActionsIncompatibleWithSingleStoreDataclass:(id)arg1;
+ (BOOL)multipleStoresSupportedByDataclass:(id)arg1;
+ (BOOL)isMultitaskingEnabled;
+ (id)supportedDataclassesForAccountType:(id)arg1;
+ (void)initialize;

- (id)shortTypeString;
- (void)_forcedSetEnabled:(BOOL)arg1 forDataclass:(id)arg2;
- (id)_creatorClassNameForAccountType:(id)arg1 creatorType:(id)arg2 loader:(id)arg3;
- (id)syncAccountCreatorClassNameForAccountType:(id)arg1;
- (id)originalProperties;
- (BOOL)refreshContainersForDataclass:(id)arg1;
- (BOOL)refreshContainerListForDataclass:(id)arg1;
- (BOOL)refreshContainerWithIdentifier:(id)arg1 forDataclass:(id)arg2;
- (id)fullAccountUsingLoader:(id)arg1;
- (void)setEnabledForDataclasses:(id)arg1;
- (id)typeString;
- (void)setAccountClass:(id)arg1;
- (id)syncStoreIdentifier;
- (id)propertiesToSave;
- (void)removeAccountPropertyForKey:(id)arg1;
- (void)renewAccountCredentialsWithHandler:(id)arg1;
- (BOOL)refreshContainersForDataclass:(id)arg1 isUserRequested:(BOOL)arg2;
- (BOOL)refreshContainerListForDataclass:(id)arg1 isUserRequested:(BOOL)arg2;
- (BOOL)refreshContainerWithIdentifier:(id)arg1 forDataclass:(id)arg2 isUserRequested:(BOOL)arg3;
- (id)_cachedSyncAccount;
- (void)setFullAccount:(id)arg1;
- (void)setParentAccount:(id)arg1;
- (id)fullAccountCreatorClassNameForAccountType:(id)arg1 loader:(id)arg2;
- (void)setEnabled:(BOOL)arg1 forDataclass:(id)arg2;
- (id)_profileRestrictedDataclasses;
- (id)_orderedDataclasses:(id)arg1;
- (void)_forcedSetAccountProperty:(id)arg1 forKey:(id)arg2;
- (id)accountClass;
- (void)setOriginalProperties:(id)arg1;
- (id)_initWithType:(id)arg1 class:(id)arg2;
- (void)setDisplayName:(id)arg1;
- (id)supportedDataclasses;
- (id)provisionedDataclasses;
- (BOOL)isEnabledForDataclass:(id)arg1;
- (id)parentAccount;
- (id)parentAccountIdentifier;
- (id)enabledDataclasses;
- (id)accountPropertyForKey:(id)arg1;
- (void)setAccountProperty:(id)arg1 forKey:(id)arg2;
- (id)displayName;
- (id)init;
- (void)dealloc;
- (id)identifier;
- (id)type;
- (id)properties;
- (id)initWithProperties:(id)arg1;

@end
