/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

@class NSString;

@interface BBBulletinTransaction : NSObject  {
    NSString *_bulletinID;
    unsigned int _transactionID;
}

@property(readonly) NSString * bulletinID;
@property(readonly) unsigned int transactionID;

+ (id)transactionWithBulletinID:(id)arg1;

- (id)initWithBulletinID:(id)arg1;
- (unsigned int)incrementTransactionID;
- (unsigned int)transactionID;
- (id)bulletinID;
- (void)dealloc;

@end
