/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSSignal : NSObject  {
    BOOL _signalled;
}


- (void)reset;
- (BOOL)hasBeenSignalled;
- (id)init;
- (void)signal;

@end
