/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@class NSDictionary, CALayer;

@interface CAContext : NSObject  {
}

@property(readonly) unsigned int contextId;
@property(retain) CALayer * layer;
@property struct CGColorSpace { }* colorSpace;
@property(readonly) NSDictionary * options;
@property float level;
@property(readonly) BOOL valid;

+ (id)currentContext;
+ (id)objectForSlot:(unsigned int)arg1;
+ (id)remoteContext;
+ (id)localContext;
+ (id)allContexts;
+ (id)remoteContextWithOptions:(id)arg1;
+ (id)localContextWithOptions:(id)arg1;
+ (void)setClientPort:(unsigned int)arg1;

- (void)setObject:(id)arg1 forSlot:(unsigned int)arg2;
- (void)deleteSlot:(unsigned int)arg1;
- (unsigned int)createSlot;
- (void)orderBelow:(unsigned int)arg1;
- (void)invalidate;
- (unsigned int)createFencePort;
- (void)setFence:(unsigned int)arg1 count:(unsigned int)arg2;
- (void)setFencePort:(unsigned int)arg1;
- (void)setFencePort:(unsigned int)arg1 commitHandler:(id)arg2;
- (void)orderAbove:(unsigned int)arg1;

@end
