/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVGetCalendarItemTask : CoreDAVGetTask  {
}


- (void)finishCoreDAVTaskWithError:(id)arg1;

@end
