/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@class <CalDAVAccountPropertyRefreshDelegate>;

@interface CalDAVAccountPropertyRefreshOperation : CalDAVOperation  {
    BOOL _fetchPrincipalSearchProperties;
}

@property <CalDAVAccountPropertyRefreshDelegate> * delegate;
@property BOOL fetchPrincipalSearchProperties;


- (void)refreshProperties;
- (void)setFetchPrincipalSearchProperties:(BOOL)arg1;
- (BOOL)fetchPrincipalSearchProperties;
- (void)getAccountPropertiesTask:(id)arg1 completedWithError:(id)arg2;

@end
