/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CAMediaTimingFunctionBuiltin : CAMediaTimingFunction  {
    unsigned int _index;
}


- (void)_getPoints:(double*)arg1;
- (id)description;
- (Class)classForCoder;
- (id)initWithCoder:(id)arg1;

@end
