/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@class NSArray, NSString, NSMutableArray;

@interface CAState : NSObject <NSCoding, NSCopying> {
    NSString *_name;
    NSString *_basedOn;
    NSMutableArray *_elements;
    double _nextDelay;
    double _previousDelay;
    BOOL _locked;
    BOOL _initial;
}

@property(copy) NSString * name;
@property(copy) NSString * basedOn;
@property(copy) NSArray * elements;
@property double nextDelay;
@property double previousDelay;
@property(getter=isLocked) BOOL locked;
@property(getter=isInitial) BOOL initial;


- (void)setInitial:(BOOL)arg1;
- (BOOL)isInitial;
- (void)setPreviousDelay:(double)arg1;
- (double)previousDelay;
- (void)setNextDelay:(double)arg1;
- (double)nextDelay;
- (void)setBasedOn:(id)arg1;
- (void)removeElement:(id)arg1;
- (void)addElement:(id)arg1;
- (id)elements;
- (void)setElements:(id)arg1;
- (void)foreachLayer:(id)arg1;
- (id)basedOn;
- (BOOL)isLocked;
- (id)init;
- (void)dealloc;
- (id)name;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setLocked:(BOOL)arg1;
- (void)setName:(id)arg1;
- (id)debugDescription;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
