/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CATransactionCompletionItem : NSObject  {
    void *_priv;
}

+ (id)completionItem;

- (id)init;
- (void)dealloc;
- (void)invalidate;

@end
