/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class CHDChart;

@interface CHAutoStyling : NSObject  {
    CHDChart *mChart;
}

+ (id)autoStylingWithChart:(id)arg1;

- (void)replaceStrokeAndFillInEmptyMarker:(id)arg1 withSeriesGraphicProperties:(id)arg2;
- (int)defaultMarkerStyleForSeriesIndex:(int)arg1;
- (id)initWithChart:(id)arg1;
- (void)dealloc;

@end
