/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface CHDAutomaticObject : NSObject  {
    NSString *mName;
}

+ (id)automaticEffects;
+ (id)automaticFill;
+ (id)automaticStroke;

- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
