/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDAxesCollection : EDKeyedCollection  {
}


- (id)axesAtPosition:(int)arg1;
- (void)adjustAxesPositionForHorizontalChart;

@end
