/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDLineType : CHDChartTypeWithGrouping  {
}


- (int)defaultLabelPosition;
- (id)initWithChart:(id)arg1;

@end
