/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDPie2DSeries : CHDSeries  {
    int mExplosion;
}


- (void)setExplosion:(int)arg1;
- (int)explosion;
- (id)init;

@end
