/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class EDString, OADGraphicProperties, CHDTrendlineLabel;

@interface CHDTrendline : NSObject  {
    boolmDisplayEquation;
    boolmDisplayRSquaredValue;
    double mBackward;
    double mForward;
    double mInterceptYAxis;
    int mPolynomialOrder;
    int mMovingAveragePeriod;
    int mType;
    OADGraphicProperties *mGraphicProperties;
    CHDTrendlineLabel *mLabel;
    EDString *mName;
}

+ (id)trendline;

- (id)defaultNameWithSeriesName:(id)arg1;
- (int)movingAveragePeriod;
- (int)polynomialOrder;
- (double)interceptYAxis;
- (double)forward;
- (double)backward;
- (bool)isDisplayRSquaredValue;
- (bool)isDisplayEquation;
- (void)setMovingAveragePeriod:(int)arg1;
- (void)setPolynomialOrder:(int)arg1;
- (void)setInterceptYAxis:(double)arg1;
- (void)setForward:(double)arg1;
- (void)setBackward:(double)arg1;
- (void)setDisplayRSquaredValue:(bool)arg1;
- (void)setDisplayEquation:(bool)arg1;
- (void)setGraphicProperties:(id)arg1;
- (id)graphicProperties;
- (void)setType:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)name;
- (id)label;
- (void)setLabel:(id)arg1;
- (int)type;
- (void)setName:(id)arg1;

@end
