/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class NSMutableDictionary, NSArray;

@interface CIFilterClassDescription : NSObject  {
    NSMutableDictionary *attributes;
    NSArray *inputKeys;
    NSArray *outputKeys;
}

+ (id)classDescriptionForClass:(Class)arg1;

- (id)initWithClass:(Class)arg1;
- (id)outputKeys;
- (id)inputKeys;
- (id)attributes;

@end
