/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class CIImage, CIVector, NSNumber;

@interface CILightTunnel : CIFilter  {
    CIImage *inputImage;
    CIVector *inputCenter;
    NSNumber *inputRotation;
    NSNumber *inputRadius;
}

@property(retain) CIImage * inputImage;
@property(copy) CIVector * inputCenter;
@property(copy) NSNumber * inputRotation;
@property(copy) NSNumber * inputRadius;

+ (id)customAttributes;

- (id)inputCenter;
- (void)setInputCenter:(id)arg1;
- (id)inputRotation;
- (void)setInputRotation:(id)arg1;
- (id)inputRadius;
- (void)setInputRadius:(id)arg1;
- (id)_kernel;
- (void)setInputImage:(id)arg1;
- (id)inputImage;
- (id)outputImage;
- (void)setDefaults;

@end
