/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIPDF417BarcodeGenerator : CICodeGenerator  {
}

+ (id)customAttributes;

- (struct CGImage { }*)outputCGImage;

@end
