/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@class NSURL;

@interface CoreDAVHrefItem : CoreDAVLeafItem  {
    NSURL *_baseURL;
    int _writeStyle;
}

@property int writeStyle;
@property(retain) NSURL * baseURL;


- (void)setWriteStyle:(int)arg1;
- (int)writeStyle;
- (id)payloadAsOriginalURL;
- (void)parserSuggestsBaseURL:(id)arg1;
- (id)payloadAsFullURL;
- (void)setBaseURL:(id)arg1;
- (void)write:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)baseURL;
- (id)initWithURL:(id)arg1;
- (id)description;

@end
