/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@class <CoreDAVCopyTaskDelegate>;

@interface CoreDAVCopyTask : CoreDAVCopyOrMoveTask  {
}

@property <CoreDAVCopyTaskDelegate> * delegate;


- (void)_callBackToDelegateWithResponses:(id)arg1 error:(id)arg2;
- (id)httpMethod;
- (BOOL)validate:(id*)arg1;
- (void)dealloc;

@end
