/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@class NSMutableSet;

@interface CoreDAVSupportedReportSetItem : CoreDAVItem  {
    NSMutableSet *_supportedReports;
}

@property(retain) NSMutableSet * supportedReports;

+ (id)copyParseRules;

- (void)addSupportedReport:(id)arg1;
- (void)setSupportedReports:(id)arg1;
- (id)supportedReports;
- (id)init;
- (void)dealloc;
- (id)description;

@end
