/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@class NSMutableArray;

@interface CPMemoryPool : NSObject  {
    struct _opaque_pthread_mutex_t { 
        long __sig; 
        BOOL __opaque[40]; 
    } _lock;
    NSMutableArray *_files;
    char *_label;
    unsigned long _slotSize;
    BOOL _swappable;
}

@property(readonly) unsigned long slotSize;


- (unsigned long)slotSize;
- (id)initWithLabel:(const char *)arg1 slotSize:(unsigned long)arg2 swappable:(BOOL)arg3;
- (void)sync;
- (id)nextSlot;
- (void)dealloc;

@end
