/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class NSObject<OS_dispatch_queue>, <DDLogFormatter>;

@interface DDAbstractLogger : NSObject <DDLogger> {
    <DDLogFormatter> *formatter;
    NSObject<OS_dispatch_queue> *loggerQueue;
}


- (id)init;
- (void)dealloc;
- (id)loggerQueue;
- (void)setLogFormatter:(id)arg1;
- (id)logFormatter;
- (void)logMessage:(id)arg1;

@end
