/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMBlob : DOMObject  {
}

@property(readonly) unsigned long long size;


- (unsigned long long)size;
- (void)dealloc;
- (void)finalize;
- (id)type;

@end
