/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMCSSStyleSheet, NSString, DOMCSSRule;

@interface DOMCSSRule : DOMObject  {
}

@property(readonly) unsigned short type;
@property(copy) NSString * cssText;
@property(readonly) DOMCSSStyleSheet * parentStyleSheet;
@property(readonly) DOMCSSRule * parentRule;


- (id)parentRule;
- (id)parentStyleSheet;
- (void)setCssText:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (id)cssText;
- (unsigned short)type;

@end
