/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMHTMLLIElement : DOMHTMLElement  {
}

@property(copy) NSString * type;
@property int value;


- (void)setType:(id)arg1;
- (id)type;
- (void)setValue:(int)arg1;
- (int)value;

@end
