/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLOptionsCollection : DOMObject  {
}

@property int selectedIndex;
@property unsigned int length;


- (void)add:(id)arg1 index:(unsigned int)arg2;
- (id)namedItem:(id)arg1;
- (void)dealloc;
- (void)setLength:(unsigned int)arg1;
- (unsigned int)length;
- (void)finalize;
- (id)item:(unsigned int)arg1;
- (void)setSelectedIndex:(int)arg1;
- (int)selectedIndex;
- (void)remove:(unsigned int)arg1;

@end
