/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMHTMLFrameSetElement : DOMHTMLElement  {
}

@property(copy) NSString * cols;
@property(copy) NSString * rows;


- (void)setCols:(id)arg1;
- (id)cols;
- (id)rows;
- (void)setRows:(id)arg1;

@end
