/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLPreElement : DOMHTMLElement  {
}

@property int width;
@property BOOL wrap;


- (void)setWidth:(int)arg1;
- (void)setWrap:(BOOL)arg1;
- (BOOL)wrap;
- (int)width;

@end
