/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLMenuElement : DOMHTMLElement  {
}

@property BOOL compact;


- (void)setCompact:(BOOL)arg1;
- (BOOL)compact;

@end
