/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMCSSPrimitiveValue;

@interface DOMRect : DOMObject  {
}

@property(readonly) DOMCSSPrimitiveValue * top;
@property(readonly) DOMCSSPrimitiveValue * right;
@property(readonly) DOMCSSPrimitiveValue * bottom;
@property(readonly) DOMCSSPrimitiveValue * left;


- (id)top;
- (id)right;
- (id)left;
- (id)bottom;
- (void)dealloc;
- (void)finalize;

@end
