/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMMediaList, DOMStyleSheet, NSString, DOMNode;

@interface DOMStyleSheet : DOMObject  {
}

@property(readonly) NSString * type;
@property BOOL disabled;
@property(readonly) DOMNode * ownerNode;
@property(readonly) DOMStyleSheet * parentStyleSheet;
@property(readonly) NSString * href;
@property(readonly) NSString * title;
@property(readonly) DOMMediaList * media;


- (id)ownerNode;
- (id)parentStyleSheet;
- (id)media;
- (id)href;
- (void)dealloc;
- (id)title;
- (void)setDisabled:(BOOL)arg1;
- (void)finalize;
- (BOOL)disabled;
- (id)type;

@end
