/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMValidityState : DOMObject  {
}

@property(readonly) BOOL valueMissing;
@property(readonly) BOOL typeMismatch;
@property(readonly) BOOL patternMismatch;
@property(readonly) BOOL tooLong;
@property(readonly) BOOL rangeUnderflow;
@property(readonly) BOOL rangeOverflow;
@property(readonly) BOOL stepMismatch;
@property(readonly) BOOL customError;
@property(readonly) BOOL valid;


- (BOOL)customError;
- (BOOL)stepMismatch;
- (BOOL)rangeOverflow;
- (BOOL)rangeUnderflow;
- (BOOL)tooLong;
- (BOOL)patternMismatch;
- (BOOL)typeMismatch;
- (BOOL)valueMissing;
- (void)dealloc;
- (void)finalize;
- (BOOL)valid;

@end
