/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMCSSStyleDeclaration, NSString;

@interface DOMWebKitCSSKeyframeRule : DOMCSSRule  {
}

@property(copy) NSString * keyText;
@property(readonly) DOMCSSStyleDeclaration * style;


- (void)setKeyText:(id)arg1;
- (id)keyText;
- (id)style;

@end
