/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMWebKitTransitionEvent : DOMEvent  {
}

@property(readonly) NSString * propertyName;
@property(readonly) double elapsedTime;


- (id)propertyName;
- (double)elapsedTime;

@end
