/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class EDString;

@interface EDContentFormat : NSObject <EDKeyedObject, NSCopying> {
    EDString *mFormatString;
    unsigned int mFormatId;
    boolmBuiltIn;
    boolmReferenced;
}

+ (id)contentFormatWithNSString:(id)arg1 formatId:(unsigned int)arg2 builtIn:(bool)arg3;
+ (id)contentFormatWithFormatString:(id)arg1 formatId:(unsigned int)arg2;
+ (id)contentFormatWithFormatString:(id)arg1;

- (void)setReferenced:(bool)arg1;
- (void)setFormatId:(unsigned int)arg1;
- (bool)referenced;
- (BOOL)isEqualToContentFormat:(id)arg1;
- (bool)builtIn;
- (unsigned int)formatId;
- (id)init;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)formatString;
- (int)key;

@end
