/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDContentFormatsCollection : EDKeyedCollection  {
    unsigned int mNextContentFormatId;
}


- (bool)isOverwritingKeyOK;
- (void)addDefaultWithNSString:(id)arg1 formatId:(unsigned int)arg2;
- (void)setupDefaults;
- (unsigned int)addOrEquivalentObject:(id)arg1;
- (id)init;
- (unsigned int)addObject:(id)arg1;

@end
