/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class EDReference, EDString;

@interface EDHyperlink : NSObject  {
    EDString *mPath;
    EDString *mDosPath;
    EDString *mDescriptionText;
    EDString *mTextMark;
    EDString *mToolTip;
    EDReference *mReference;
    int mType;
}

+ (id)hyperlink;

- (id)toolTip;
- (id)textMark;
- (id)dosPath;
- (id)descriptionText;
- (void)setToolTip:(id)arg1;
- (void)setReference:(id)arg1;
- (void)setTextMark:(id)arg1;
- (void)setDosPath:(id)arg1;
- (void)setDescriptionText:(id)arg1;
- (id)reference;
- (void)setPath:(id)arg1;
- (void)setType:(int)arg1;
- (void)dealloc;
- (int)type;
- (id)path;

@end
