/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDMergedCellCollection : EDCollection  {
}


- (id)referenceContainingRow:(int)arg1 column:(int)arg2;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;
- (unsigned int)addObject:(id)arg1;

@end
