/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDOneCellAnchor : EDAnchor  {
    struct EDCellAnchorMarker { 
        int columnIndex; 
        float columnAdjustment; 
        int rowIndex; 
        float rowAdjustment; 
    } mFrom;
    struct CGSize { 
        float width; 
        float height; 
    } mSize;
    BOOL mIsRelative;
}


- (void)setRelative:(BOOL)arg1;
- (BOOL)isRelative;
- (void)setFrom:(struct EDCellAnchorMarker { int x1; float x2; int x3; float x4; })arg1;
- (struct EDCellAnchorMarker { int x1; float x2; int x3; float x4; })from;
- (struct CGSize { float x1; float x2; })size;
- (id).cxx_construct;
- (void)setSize:(struct CGSize { float x1; float x2; })arg1;

@end
