/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableDictionary;

@interface EDOptimizedStringsCollection : EDCollection  {
    NSMutableDictionary *mStringDictionary;
}


- (unsigned int)addOrEquivalentObject:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)replaceObjectAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (unsigned int)addObject:(id)arg1;

@end
