/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class EDCollection;

@interface EDPivotConditionalFormat : NSObject  {
    unsigned int mPriority;
    int mType;
    int mScope;
    EDCollection *mPivotAreas;
}

+ (id)pivotConditionalFormat;

- (id)pivotAreas;
- (void)setScope:(int)arg1;
- (int)scope;
- (void)setType:(int)arg1;
- (id)init;
- (void)dealloc;
- (void)setPriority:(unsigned int)arg1;
- (unsigned int)priority;
- (int)type;

@end
