/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDReferenceCollection : EDCollection  {
    boolmCoalesce;
}

+ (id)coalesceCollection;
+ (id)noCoalesceCollection;

- (bool)coalesceReferenceAtIndex1:(int)arg1 index2:(int)arg2;
- (void)coalesce;
- (id)initWihNoCoalesce;
- (id)referenceToCellWithIndex:(unsigned int)arg1 byRow:(bool)arg2;
- (id)reverseReferencesByRow:(bool)arg1;
- (unsigned int)countOfCellsBeingReferenced;
- (id)init;
- (void)replaceObjectAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;
- (unsigned int)addObject:(id)arg1;

@end
