/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EDStylesCollection : EDCollection  {
    unsigned int mDefaultWorkbookStyleIndex;
}


- (unsigned int)defaultWorkbookStyleIndex;
- (void)setDefaultWorkbookStyleIndex:(unsigned int)arg1;
- (id)defaultWorkbookStyle;
- (id)init;
- (void)replaceObjectAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (void)removeAllObjects;
- (void)removeObjectAtIndex:(unsigned int)arg1;
- (unsigned int)addObject:(id)arg1;

@end
