/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/EventKit.framework/EventKit
 */

@interface EKAlarmWrapper : NSObject  {
    struct CalAlarmOccurrence { } *_alarm;
}

+ (id)wrapperWithAlarmOccurrence:(struct CalAlarmOccurrence { }*)arg1;

- (id)occurrence;
- (id)initWithAlarmOccurrence:(struct CalAlarmOccurrence { }*)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (double)fireDate;

@end
