/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/EventKit.framework/EventKit
 */

@class NSURL, NSString;

@interface EKPersistentParticipant : EKPersistentObject <NSCopying> {
}

@property(readonly) NSString * UUID;
@property(copy) NSString * displayName;
@property(copy) NSString * emailAddress;
@property(copy) NSURL * address;
@property(copy) NSString * firstName;
@property(copy) NSString * lastName;

+ (id)defaultPropertiesToLoad;

- (id)owner;
- (id)emailAddress;
- (void)setEmailAddress:(id)arg1;
- (void)setLastName:(id)arg1;
- (void)setFirstName:(id)arg1;
- (id)lastName;
- (id)firstName;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (void)setAddress:(id)arg1;
- (id)init;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)UUID;
- (id)address;

@end
