/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/EventKit.framework/EventKit
 */

@class EKSourceConstraints, NSString, NSNumber;

@interface EKPersistentSource : EKPersistentObject  {
    EKSourceConstraints *_constraints;
}

@property NSString * UUID;
@property int sourceType;
@property(copy) NSString * title;
@property(copy) NSNumber * defaultAlarmOffset;
@property(copy) NSString * externalID;
@property(getter=isEnabled) BOOL enabled;
@property(readonly) EKSourceConstraints * constraints;

+ (id)relations;
+ (id)defaultPropertiesToLoad;

- (void)setUUID:(id)arg1;
- (void)setDefaultAlarmOffset:(id)arg1;
- (id)defaultAlarmOffset;
- (int)entityType;
- (id)externalID;
- (void)setExternalID:(id)arg1;
- (void)reset;
- (BOOL)refresh;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)isEnabled;
- (id)init;
- (void)dealloc;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)description;
- (void)setSourceType:(int)arg1;
- (int)sourceType;
- (id)UUID;
- (id)constraints;

@end
