/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface EPBorder : EDBorder  {
    int mPrecedence;
}

+ (id)borderWithBorder:(id)arg1 precedence:(int)arg2 resources:(id)arg3;

- (id)initWithBorder:(id)arg1 precedence:(int)arg2 resources:(id)arg3;
- (int)precedence;
- (BOOL)isEqualToBorder:(id)arg1;

@end
