/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface EXReader : OCXReader  {
    NSString *mTemporaryDirectory;
}

@property(retain) NSString * temporaryDirectory;


- (void)setTemporaryDirectory:(id)arg1;
- (id)temporaryDirectory;
- (id)read;
- (void)dealloc;

@end
