/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class AllClasses, UIAlertView, NSArray, UIProgressView;

@interface FrameworksTVC : UITableViewController <UITableViewDataSource, UITableViewDelegate> {
    NSArray *publicFrameworks;
    NSArray *privateFrameworks;
    NSArray *bundleFrameworks;
    AllClasses *allClasses;
    UIAlertView *alertView;
    UIProgressView *progressView;
}

@property(retain) NSArray * publicFrameworks;
@property(retain) NSArray * privateFrameworks;
@property(retain) NSArray * bundleFrameworks;
@property(retain) AllClasses * allClasses;


- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)bundleFrameworks;
- (id)privateFrameworks;
- (id)publicFrameworks;
- (void)loadAllFrameworks:(id)arg1;
- (void)setPublicFrameworks:(id)arg1;
- (void)setPrivateFrameworks:(id)arg1;
- (id)frameworksAtPath:(id)arg1;
- (void)setBundleFrameworks:(id)arg1;
- (id)loadedBundleFrameworks;
- (id)allClasses;
- (void)setAllClasses:(id)arg1;

@end
