/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class UIButton, UILabel;

@interface FrameworkCell : UITableViewCell  {
    UILabel *label;
    UIButton *button;
}

@property(retain) UILabel * label;
@property(retain) UIButton * button;


- (id)button;
- (id)label;
- (void)setLabel:(id)arg1;
- (void)setButton:(id)arg1;

@end
