/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSDictionary, NSArray;

@interface FTCanonicalizeMessage : FTMessage <NSCopying> {
    NSArray *_URIs;
    NSDictionary *_regionContext;
    NSArray *_responseNodes;
}

@property(copy) NSArray * URIs;
@property(copy) NSDictionary * regionContext;
@property(copy) NSArray * responseNodes;


- (void)setResponseNodes:(id)arg1;
- (id)responseNodes;
- (void)setRegionContext:(id)arg1;
- (id)regionContext;
- (void)setURIs:(id)arg1;
- (id)URIs;
- (void)handleResponseDictionary:(id)arg1;
- (id)bagKey;
- (int)responseCommand;
- (int)command;
- (BOOL)wantsBagKey;
- (BOOL)wantsHTTPHeaders;
- (BOOL)wantsCompressedBody;
- (id)requiredKeys;
- (id)messageBody;
- (BOOL)wantsBinaryPush;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
