/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTClientServices.framework/FTClientServices
 */

@class NSString;

@interface FTCConnectionHandler : NSObject  {
    int _serviceType;
    unsigned long long _caps;
    NSString *_name;
    NSString *_listenerID;
    NSString *_logName;
    BOOL _listeningForNotifications;
}

@property unsigned long long caps;
@property int serviceType;
@property(copy) NSString * name;
@property(readonly) NSString * _serviceName;
@property(setter=_setLogName:,copy) NSString * _logName;
@property(setter=_setListenerID:,copy) NSString * _listenerID;


- (void)setCaps:(unsigned long long)arg1;
- (unsigned long long)caps;
- (BOOL)_isServiceSupported;
- (id)_listenerID;
- (void)_handleDaemonDisconnected:(id)arg1;
- (void)_disconnectFromDaemon;
- (id)initWithServiceType:(int)arg1 name:(id)arg2 capabilities:(unsigned long long)arg3;
- (void)_setListenerID:(id)arg1;
- (id)_serviceName;
- (void)_stopListeningForNotifications;
- (void)_handleCapabilitiesChanged:(id)arg1;
- (void)_handleDaemonConnected:(id)arg1;
- (BOOL)connectToDaemon:(BOOL)arg1;
- (BOOL)isConnectedToDaemon;
- (void)_startListeningForNotifications;
- (id)initWithServiceType:(int)arg1 name:(id)arg2;
- (id)_logName;
- (void)_setLogName:(id)arg1;
- (BOOL)connectToDaemon;
- (void)setServiceType:(int)arg1;
- (int)serviceType;
- (void)dealloc;
- (id)name;
- (void)setName:(id)arg1;

@end
