/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@interface FTFaceTimeServerBag : FTServerBag  {
}

+ (id)_bagCreationLock;

- (id)_bagDefaultsDomain;
- (id)init;

@end
