/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSString, NSDictionary;

@interface FTGetRegionMetadataMessage : FTMessage <NSCopying> {
    NSString *_language;
    NSDictionary *_responseRegionInformation;
}

@property(copy) NSString * language;
@property(copy) NSDictionary * responseRegionInformation;


- (void)setResponseRegionInformation:(id)arg1;
- (id)responseRegionInformation;
- (void)handleResponseDictionary:(id)arg1;
- (id)bagKey;
- (int)responseCommand;
- (int)command;
- (BOOL)wantsBagKey;
- (BOOL)wantsHTTPGet;
- (BOOL)wantsHTTPHeaders;
- (BOOL)wantsCompressedBody;
- (id)requiredKeys;
- (id)messageBody;
- (BOOL)wantsBinaryPush;
- (id)language;
- (void)setLanguage:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
