/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSData;

@interface FTiMessageGenericMessage : FTiMessagePeerMessage <NSCopying> {
    NSData *_data;
}

@property(copy) NSData * data;


- (int)command;
- (id)requiredKeys;
- (id)messageBody;
- (void)dealloc;
- (id)data;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setData:(id)arg1;

@end
