/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSArray, NSData, NSString;

@interface FTiMessagePeerMessage : FTiMessageMessage <NSCopying> {
    NSData *_targetToken;
    NSString *_targetPeerID;
    NSString *_sourcePeerID;
    NSData *_targetSessionToken;
    NSArray *_targetPeers;
    NSString *_messageID;
}

@property(copy) NSData * targetSessionToken;
@property(copy) NSString * targetPeerID;
@property(copy) NSString * sourcePeerID;
@property(copy) NSData * targetToken;
@property(copy) NSString * messageID;
@property(copy) NSArray * targetPeers;


- (void)setTargetSessionToken:(id)arg1;
- (id)targetSessionToken;
- (void)setTargetToken:(id)arg1;
- (id)targetToken;
- (void)setTargetPeers:(id)arg1;
- (id)targetPeers;
- (void)setSourcePeerID:(id)arg1;
- (id)sourcePeerID;
- (void)setTargetPeerID:(id)arg1;
- (id)targetPeerID;
- (id)requiredKeys;
- (id)messageBody;
- (void)setMessageID:(id)arg1;
- (id)messageID;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
