/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@interface FTiMessageServerBag : FTServerBag  {
}

+ (id)_sharedInstanceForClass:(Class)arg1;
+ (id)_bagCreationLock;
+ (id)sharedInstance;

- (id)_bagDefaultsDomain;
- (id)init;

@end
