/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSData, NSString;

@interface FTiMessageTextMessage : FTiMessagePeerMessage <NSCopying> {
    NSData *_messageData;
    NSString *_encryptionType;
}

@property(copy) NSData * messageData;
@property(copy) NSString * encryptionType;


- (void)setEncryptionType:(id)arg1;
- (void)setMessageData:(id)arg1;
- (int)command;
- (BOOL)payloadCanBeLogged;
- (id)requiredKeys;
- (id)messageBody;
- (id)encryptionType;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)messageData;

@end
