/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSArray;

@interface FTProfileGetHandlesMessage : FTProfileMessage <NSCopying> {
    NSArray *_responseHandles;
}

@property(copy) NSArray * responseHandles;


- (void)setResponseHandles:(id)arg1;
- (id)responseHandles;
- (void)handleResponseDictionary:(id)arg1;
- (id)bagKey;
- (id)requiredKeys;
- (id)messageBody;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
