/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSNumber, NSString;

@interface FTProfileValidateHandleMessage : FTProfileMessage <NSCopying> {
    NSString *_uri;
    NSNumber *_responseVettingStatus;
    NSString *_deviceName;
}

@property(setter=setURI:,copy) NSString * URI;
@property(copy) NSString * deviceName;
@property(copy) NSNumber * responseVettingStatus;


- (void)setResponseVettingStatus:(id)arg1;
- (id)responseVettingStatus;
- (id)URI;
- (void)setDeviceName:(id)arg1;
- (void)handleResponseDictionary:(id)arg1;
- (id)bagKey;
- (id)requiredKeys;
- (id)messageBody;
- (void)setURI:(id)arg1;
- (id)deviceName;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
