/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSString, NSArray;

@interface FTProfileGetDevicesMessage : FTProfileMessage <NSCopying> {
    NSString *_service;
    NSArray *_responseDevices;
}

@property(copy) NSString * service;
@property(copy) NSArray * responseDevices;


- (void)setResponseDevices:(id)arg1;
- (id)responseDevices;
- (void)handleResponseDictionary:(id)arg1;
- (id)bagKey;
- (id)requiredKeys;
- (id)messageBody;
- (void)setService:(id)arg1;
- (id)service;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
