/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSNumber, NSString, NSDictionary;

@interface FTProfileLinkHandleMessage : FTProfileMessage <NSCopying> {
    NSString *_uri;
    NSDictionary *_authenticationData;
    NSNumber *_responseVettingStatus;
}

@property(setter=setURI:,copy) NSString * URI;
@property(copy) NSDictionary * authenticationData;
@property(copy) NSNumber * responseVettingStatus;


- (void)setAuthenticationData:(id)arg1;
- (id)authenticationData;
- (void)setResponseVettingStatus:(id)arg1;
- (id)responseVettingStatus;
- (id)URI;
- (void)handleResponseDictionary:(id)arg1;
- (id)additionalMessageHeaders;
- (id)bagKey;
- (BOOL)wantsBodySignature;
- (BOOL)wantsSignature;
- (id)requiredKeys;
- (id)messageBody;
- (void)setURI:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
