/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSString;

@interface FTProfileAuthenticationMessage : FTProfileMessage <NSCopying> {
    NSString *_username;
    NSString *_password;
    NSString *_responseProfileID;
    NSString *_responseAuthToken;
}

@property(copy) NSString * username;
@property(copy) NSString * password;
@property(copy) NSString * responseProfileID;
@property(copy) NSString * responseAuthorizationToken;


- (void)setResponseAuthorizationToken:(id)arg1;
- (id)responseAuthorizationToken;
- (void)setResponseProfileID:(id)arg1;
- (id)responseProfileID;
- (void)handleResponseDictionary:(id)arg1;
- (id)additionalMessageHeadersForOutgoingPush;
- (id)additionalMessageHeaders;
- (id)bagKey;
- (BOOL)hasRequiredKeys:(id*)arg1;
- (BOOL)payloadCanBeLogged;
- (id)requiredKeys;
- (id)messageBody;
- (void)setPassword:(id)arg1;
- (void)setUsername:(id)arg1;
- (id)username;
- (void)dealloc;
- (id)password;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
