/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSArray, NSMutableSet, NSData, NSMutableArray;

@interface FTPushHandler : NSObject  {
    NSMutableSet *_topics;
    NSMutableArray *_handlers;
    BOOL _registeredForPush;
}

@property(retain) NSArray * topics;
@property(readonly) NSData * pushToken;
@property BOOL registered;
@property(readonly) int connectionStatus;

+ (id)alloc;
+ (id)sharedInstance;

- (void)setTopics:(id)arg1;
- (int)connectionStatus;
- (void)removeTopic:(id)arg1;
- (void)addTopic:(id)arg1;
- (id)topics;
- (void)requestKeepAlive;
- (void)updateTopics;
- (id)initWithTopics:(id)arg1;
- (id)pushToken;
- (void)setRegistered:(BOOL)arg1;
- (BOOL)registered;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)init;
- (void)dealloc;

@end
