/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class NSData;

@interface GCDAsyncWritePacket : NSObject  {
    NSData *buffer;
    unsigned int bytesDone;
    long tag;
    double timeout;
}


- (void)dealloc;
- (id)initWithData:(id)arg1 timeout:(double)arg2 tag:(long)arg3;

@end
