/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSString;

@interface GEOAttribution : PBCodable  {
    NSString *_badge;
    NSString *_logo;
    NSString *_name;
    NSString *_url;
}

@property(readonly) BOOL hasBadge;
@property(retain) NSString * badge;
@property(readonly) BOOL hasLogo;
@property(retain) NSString * logo;
@property(readonly) BOOL hasName;
@property(retain) NSString * name;
@property(readonly) BOOL hasUrl;
@property(retain) NSString * url;


- (void)setLogo:(id)arg1;
- (void)setBadge:(id)arg1;
- (BOOL)hasUrl;
- (id)logo;
- (BOOL)hasLogo;
- (id)badge;
- (BOOL)hasBadge;
- (BOOL)hasName;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)name;
- (id)description;
- (void)setUrl:(id)arg1;
- (id)url;
- (id)dictionaryRepresentation;
- (void)setName:(id)arg1;

@end
