/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSMutableArray;

@interface GEODirectionsCollectionRequest : PBRequest  {
    NSMutableArray *_requestElements;
}

@property(retain) NSMutableArray * requestElements;


- (id)requestElements;
- (id)requestElementsAtIndex:(unsigned int)arg1;
- (void)clearRequestElements;
- (unsigned int)requestElementsCount;
- (void)addRequestElements:(id)arg1;
- (void)setRequestElements:(id)arg1;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (Class)responseClass;
- (void)writeTo:(id)arg1;
- (unsigned int)requestTypeCode;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)dictionaryRepresentation;

@end
