/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSMutableArray;

@interface GEOETATrafficUpdateResponse : PBCodable  {
    NSMutableArray *_routes;
    int _status;
    struct { 
        unsigned int status : 1; 
    } _has;
}

@property BOOL hasStatus;
@property int status;
@property(retain) NSMutableArray * routes;


- (void)setHasStatus:(BOOL)arg1;
- (BOOL)hasStatus;
- (id)routes;
- (id)routeAtIndex:(unsigned int)arg1;
- (void)clearRoutes;
- (unsigned int)routesCount;
- (void)addRoute:(id)arg1;
- (void)setRoutes:(id)arg1;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (void)setStatus:(int)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)dictionaryRepresentation;
- (int)status;

@end
