/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSString;

@interface GEOGeocodeRequest : GEOPlaceSearchRequest  {
    unsigned short _geocodeProvider;
    NSString *_logRequestToFile;
    NSString *_logResponseToFile;
}

@property unsigned short geocodeProvider;
@property(retain) NSString * logRequestToFile;
@property(retain) NSString * logResponseToFile;


- (id)initReverseGeocodeWithCoordinate:(struct { double x1; double x2; })arg1 includeBusinessOptions:(BOOL)arg2;
- (void)setGeocodeProvider:(unsigned short)arg1;
- (void)setLogResponseToFile:(id)arg1;
- (void)setLogRequestToFile:(id)arg1;
- (unsigned short)geocodeProvider;
- (id)initForwardGeocodeWithAddressString:(id)arg1;
- (id)initForwardGeocodeWithAddressDictionary:(id)arg1;
- (id)initReverseGeocodeWithCoordinate:(struct { double x1; double x2; })arg1;
- (id)logResponseToFile;
- (id)logRequestToFile;
- (void)dealloc;

@end
