/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOLocationShiftFunctionRequest : GEOLocationShiftRequest  {
    unsigned short _providerID;
}

@property unsigned short providerID;
@property struct { double x1; double x2; } coordinate;


- (void)setCoordinate:(struct { double x1; double x2; })arg1;
- (void)setProviderID:(unsigned short)arg1;
- (unsigned short)providerID;
- (struct { double x1; double x2; })coordinate;

@end
