/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSString;

@interface GEONamedFeature : PBCodable  {
    double _value;
    NSString *_name;
}

@property(retain) NSString * name;
@property double value;


- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)name;
- (id)description;
- (void)setValue:(double)arg1;
- (double)value;
- (id)dictionaryRepresentation;
- (void)setName:(id)arg1;

@end
