/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSString;

@interface GEONameInfo : PBCodable  {
    NSString *_name;
    NSString *_phoneticName;
    int _phoneticType;
    NSString *_shield;
    int _shieldType;
    int _signType;
    struct { 
        unsigned int phoneticType : 1; 
        unsigned int shieldType : 1; 
        unsigned int signType : 1; 
    } _has;
}

@property(readonly) BOOL hasName;
@property(retain) NSString * name;
@property(readonly) BOOL hasPhoneticName;
@property(retain) NSString * phoneticName;
@property(readonly) BOOL hasShield;
@property(retain) NSString * shield;
@property BOOL hasShieldType;
@property int shieldType;
@property BOOL hasPhoneticType;
@property int phoneticType;
@property BOOL hasSignType;
@property int signType;


- (void)setHasSignType:(BOOL)arg1;
- (void)setHasPhoneticType:(BOOL)arg1;
- (void)setHasShieldType:(BOOL)arg1;
- (void)setSignType:(int)arg1;
- (int)signType;
- (BOOL)hasSignType;
- (void)setPhoneticType:(int)arg1;
- (int)phoneticType;
- (BOOL)hasPhoneticType;
- (void)setShieldType:(int)arg1;
- (int)shieldType;
- (BOOL)hasShieldType;
- (id)shield;
- (BOOL)hasShield;
- (void)setShield:(id)arg1;
- (id)phoneticName;
- (BOOL)hasPhoneticName;
- (void)setPhoneticName:(id)arg1;
- (BOOL)hasName;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)name;
- (id)description;
- (id)dictionaryRepresentation;
- (void)setName:(id)arg1;

@end
