/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSString;

@interface GEOPhotoInfo : PBCodable  {
    int _size;
    NSString *_url;
    struct { 
        unsigned int size : 1; 
    } _has;
}

@property BOOL hasSize;
@property int size;
@property(readonly) BOOL hasUrl;
@property(retain) NSString * url;


- (void)setHasSize:(BOOL)arg1;
- (BOOL)hasUrl;
- (BOOL)hasSize;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (int)size;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (void)setUrl:(id)arg1;
- (void)setSize:(int)arg1;
- (id)url;
- (id)dictionaryRepresentation;

@end
