/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEOLatLng, GEOMapRegion, NSString, NSMutableArray, GEOAddress;

@interface GEOPlace : PBCodable  {
    long long _geoId;
    long long _uID;
    GEOAddress *_address;
    int _addressGeocodeAccuracy;
    NSMutableArray *_business;
    GEOLatLng *_center;
    NSMutableArray *_entryPoints;
    GEOMapRegion *_mapRegion;
    NSString *_name;
    GEOAddress *_phoneticAddress;
    NSString *_phoneticName;
    int _type;
    int _version;
    BOOL _isDisputed;
    struct { 
        unsigned int geoId : 1; 
        unsigned int uID : 1; 
        unsigned int addressGeocodeAccuracy : 1; 
        unsigned int type : 1; 
        unsigned int version : 1; 
        unsigned int isDisputed : 1; 
    } _has;
}

@property BOOL hasUID;
@property long long uID;
@property BOOL hasVersion;
@property int version;
@property BOOL hasType;
@property int type;
@property(readonly) BOOL hasName;
@property(retain) NSString * name;
@property(readonly) BOOL hasMapRegion;
@property(retain) GEOMapRegion * mapRegion;
@property(readonly) BOOL hasAddress;
@property(retain) GEOAddress * address;
@property(readonly) BOOL hasPhoneticName;
@property(retain) NSString * phoneticName;
@property(readonly) BOOL hasPhoneticAddress;
@property(retain) GEOAddress * phoneticAddress;
@property(readonly) BOOL hasCenter;
@property(retain) GEOLatLng * center;
@property(retain) NSMutableArray * business;
@property BOOL hasAddressGeocodeAccuracy;
@property int addressGeocodeAccuracy;
@property(retain) NSMutableArray * entryPoints;
@property BOOL hasIsDisputed;
@property BOOL isDisputed;
@property BOOL hasGeoId;
@property long long geoId;


- (id)entryPoints;
- (id)business;
- (void)setHasGeoId:(BOOL)arg1;
- (void)setHasIsDisputed:(BOOL)arg1;
- (void)setHasAddressGeocodeAccuracy:(BOOL)arg1;
- (void)setGeoId:(long long)arg1;
- (long long)geoId;
- (BOOL)hasGeoId;
- (void)setIsDisputed:(BOOL)arg1;
- (BOOL)isDisputed;
- (BOOL)hasIsDisputed;
- (id)entryPointAtIndex:(unsigned int)arg1;
- (void)clearEntryPoints;
- (unsigned int)entryPointsCount;
- (void)setAddressGeocodeAccuracy:(int)arg1;
- (int)addressGeocodeAccuracy;
- (BOOL)hasAddressGeocodeAccuracy;
- (id)businessAtIndex:(unsigned int)arg1;
- (void)clearBusiness;
- (unsigned int)businessCount;
- (id)phoneticAddress;
- (BOOL)hasPhoneticAddress;
- (BOOL)hasAddress;
- (void)addEntryPoint:(id)arg1;
- (void)addBusiness:(id)arg1;
- (void)setEntryPoints:(id)arg1;
- (void)setBusiness:(id)arg1;
- (void)setPhoneticAddress:(id)arg1;
- (void)setHasVersion:(BOOL)arg1;
- (void)setHasUID:(BOOL)arg1;
- (BOOL)hasCenter;
- (id)phoneticName;
- (BOOL)hasPhoneticName;
- (BOOL)hasVersion;
- (void)setUID:(long long)arg1;
- (long long)uID;
- (BOOL)hasUID;
- (void)setPhoneticName:(id)arg1;
- (void)setHasType:(BOOL)arg1;
- (BOOL)hasType;
- (BOOL)hasName;
- (id)addressDictionary;
- (void)copyTo:(id)arg1;
- (id)mapRegion;
- (BOOL)hasMapRegion;
- (void)setMapRegion:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (void)setType:(int)arg1;
- (void)setAddress:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)name;
- (id)description;
- (void)setCenter:(id)arg1;
- (id)center;
- (int)type;
- (void)setVersion:(int)arg1;
- (id)dictionaryRepresentation;
- (void)setName:(id)arg1;
- (int)version;
- (id)address;

@end
