/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOResourceManager : NSObject  {
}

+ (id)sharedManager;

- (id)dataForResourceWithName:(id)arg1 fallbackBundle:(id)arg2;
- (id)allResourceNames;
- (id)pathForResourceWithName:(id)arg1 fallbackBundle:(id)arg2;

@end
