/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSearchRequest : GEOPlaceSearchRequest  {
    unsigned short _provider;
}

@property unsigned short provider;


- (unsigned short)provider;
- (Class)responseClass;
- (id)init;
- (void)setProvider:(unsigned short)arg1;

@end
