/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSURL;

@interface GEOThrottleKey : NSObject  {
    NSURL *_serverURL;
    unsigned int _requestType;
}


- (id)initWithRequestType:(unsigned int)arg1 serverURL:(id)arg2;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;

@end
