/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSMutableArray;

@interface GEOUsageCollectionRequest : PBRequest  {
    NSMutableArray *_directionsFeedbackCollections;
    NSMutableArray *_placeSearchFeedbackCollections;
    NSMutableArray *_transitAppLaunchFeedbackCollections;
    NSMutableArray *_usageCollections;
}

@property(retain) NSMutableArray * usageCollections;
@property(retain) NSMutableArray * directionsFeedbackCollections;
@property(retain) NSMutableArray * placeSearchFeedbackCollections;
@property(retain) NSMutableArray * transitAppLaunchFeedbackCollections;


- (id)transitAppLaunchFeedbackCollections;
- (id)placeSearchFeedbackCollections;
- (id)directionsFeedbackCollections;
- (id)usageCollections;
- (id)transitAppLaunchFeedbackCollectionAtIndex:(unsigned int)arg1;
- (void)clearTransitAppLaunchFeedbackCollections;
- (unsigned int)transitAppLaunchFeedbackCollectionsCount;
- (id)placeSearchFeedbackCollectionAtIndex:(unsigned int)arg1;
- (void)clearPlaceSearchFeedbackCollections;
- (unsigned int)placeSearchFeedbackCollectionsCount;
- (id)directionsFeedbackCollectionAtIndex:(unsigned int)arg1;
- (void)clearDirectionsFeedbackCollections;
- (unsigned int)directionsFeedbackCollectionsCount;
- (id)usageCollectionAtIndex:(unsigned int)arg1;
- (void)clearUsageCollections;
- (unsigned int)usageCollectionsCount;
- (void)setTransitAppLaunchFeedbackCollections:(id)arg1;
- (void)setPlaceSearchFeedbackCollections:(id)arg1;
- (void)setDirectionsFeedbackCollections:(id)arg1;
- (void)setUsageCollections:(id)arg1;
- (void)addPlaceSearchFeedbackCollection:(id)arg1;
- (void)addTransitAppLaunchFeedbackCollection:(id)arg1;
- (void)addDirectionsFeedbackCollection:(id)arg1;
- (void)addUsageCollection:(id)arg1;
- (void)copyTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (Class)responseClass;
- (void)writeTo:(id)arg1;
- (unsigned int)requestTypeCode;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)dictionaryRepresentation;

@end
