/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOUserSession : NSObject  {
    double _lastSessionCreationTime;
    struct { 
        unsigned long long _high; 
        unsigned long long _low; 
    } _sessionID;
    struct { 
        unsigned long long _high; 
        unsigned long long _low; 
    } _probeID;
}

@property(readonly) struct { unsigned long long x1; unsigned long long x2; } sessionID;
@property(readonly) struct { unsigned long long x1; unsigned long long x2; } probeID;

+ (id)sharedInstance;

- (struct { unsigned long long x1; unsigned long long x2; })probeID;
- (void)_updateWithNewUUIDForSessionID:(struct { unsigned long long x1; unsigned long long x2; }*)arg1;
- (struct { unsigned long long x1; unsigned long long x2; })sessionID;
- (id)init;

@end
