/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEORequester;

@interface GEOVoltaireDirectionsProvider : GEODirectionsProvider <PBRequesterDelegate> {
    GEORequester *_requester;
}

@property(retain) GEORequester * requester;

+ (void)setUsePersistentConnection:(BOOL)arg1;
+ (id)providerURL;
+ (void)resetProviderURL;
+ (unsigned short)providerID;

- (void)cleanupRequester;
- (void)setRequester:(id)arg1;
- (id)requester;
- (void)cancelProviderRequest;
- (void)startProviderWithRequest:(id)arg1;
- (void)requester:(id)arg1 didFailWithError:(id)arg2;
- (void)requesterDidCancel:(id)arg1;
- (void)requesterDidFinish:(id)arg1;
- (id)init;
- (void)dealloc;

@end
