/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@interface GKAbbreviatedNumberFormatter : NSNumberFormatter  {
}


- (id)formatForNumberWithAbbreviation;
- (id)abbreviationForThousands;
- (id)abbreviationForMillions;
- (id)abbreviationForBillions;
- (id)bundle;
- (id)stringForObjectValue:(id)arg1;

@end
