/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImage, GKAchievement, GKPlayer, GKAchievementDescription, GKGame;

@interface GKAchievementSharingInfo : NSObject <NSCoding> {
    GKPlayer *_player;
    GKAchievement *_achievement;
    UIImage *_badgeImage;
    UIImage *_iconImage;
    GKAchievementDescription *_achievementDescription;
    GKGame *_game;
}

@property(retain) GKAchievement * achievement;
@property(retain) GKAchievementDescription * achievementDescription;
@property(retain) GKPlayer * player;
@property(retain) GKGame * game;
@property(retain) UIImage * iconImage;
@property(retain) UIImage * badgeImage;


- (id)initWithAchievement:(id)arg1 forGame:(id)arg2 player:(id)arg3;
- (id)subjectForEmailActivity;
- (id)itemsForActivityType:(id)arg1;
- (id)thumbnailForActivityType:(id)arg1;
- (id)badgeImage;
- (void)setIconImage:(id)arg1;
- (void)setBadgeImage:(id)arg1;
- (id)achievementDescription;
- (void)setAchievementDescription:(id)arg1;
- (void)setAchievement:(id)arg1;
- (id)achievement;
- (void)setGame:(id)arg1;
- (id)game;
- (id)player;
- (void)setPlayer:(id)arg1;
- (void)dealloc;
- (id)iconImage;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
