/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKAchievementInternal;

@interface GKAchievementChallengeInternal : GKChallengeInternal  {
    GKAchievementInternal *_achievement;
}

@property(copy) GKAchievementInternal * achievement;

+ (id)codedPropertyKeys;
+ (id)internalRepresentation;

- (void)setAchievement:(id)arg1;
- (id)achievement;
- (id)issueRepresentationToPlayerID:(id)arg1;
- (void)dealloc;

@end
