/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKUITheme, GKPlayer;

@interface GKAchievementCompareHeaderCellContents : UIView <GKTableViewCellContents> {
    GKUITheme *_theme;
    GKPlayer *_player;
    unsigned int _achievements;
    unsigned int _points;
}

@property(retain) GKUITheme * theme;
@property(retain) GKPlayer * player;
@property unsigned int achievements;
@property unsigned int points;
@property struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } confirmationButtonRect;


- (float)preferredHeightForOrientation:(int)arg1;
- (void)setAchievements:(unsigned int)arg1;
- (unsigned int)achievements;
- (void)setTheme:(id)arg1;
- (id)theme;
- (unsigned int)points;
- (void)setPoints:(unsigned int)arg1;
- (id)player;
- (void)setPlayer:(id)arg1;
- (void)drawRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)dealloc;
- (void)prepareForReuse;

@end
