/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImage;

@interface GKBackgroundDrawDescriptor : NSObject  {
    UIImage *_borderImage;
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    } _borderInsets;
    int _sectionLocation;
    BOOL _drawOutline;
}

@property(retain) UIImage * borderImage;
@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } borderInsets;
@property int sectionLocation;
@property BOOL drawOutline;


- (void)setDrawOutline:(BOOL)arg1;
- (BOOL)drawOutline;
- (void)setBorderInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })borderInsets;
- (void)setBorderImage:(id)arg1;
- (id)borderImage;
- (void)dealloc;
- (id)description;
- (void)setSectionLocation:(int)arg1;
- (int)sectionLocation;

@end
