/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKComposeHeaderField, NSString;

@interface GKChallengeComposeController : GKSimpleComposeController  {
    GKComposeHeaderField *_challengeField;
    NSString *_challengeDescription;
}

@property(retain) NSString * challengeDescription;
@property(retain) GKComposeHeaderField * challengeField;


- (id)challengeDescription;
- (id)challengeField;
- (void)setChallengeField:(id)arg1;
- (void)setChallengeDescription:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)cancel;

@end
