/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSString, GKUITheme, GKComposeRemoteViewController, NSMutableArray, NSNumber;

@interface GKComposeHostedViewController : GKHostedViewController  {
    NSMutableArray *_playerIDsToAddAsRecipients;
    NSMutableArray *_emailsToAddAsRecipients;
    GKUITheme *_theme;
    NSNumber *_rid;
}

@property(retain) GKUITheme * theme;
@property(retain) NSNumber * rid;
@property(copy) NSString * defaultMessage;
@property(retain) NSMutableArray * playerIDsToAddAsRecipients;
@property(retain) NSMutableArray * emailsToAddAsRecipients;
@property(readonly) GKComposeRemoteViewController * _remote;


- (id)emailsToAddAsRecipients;
- (id)playerIDsToAddAsRecipients;
- (id)_presentingViewController;
- (id)hostSideViewControllerClassName;
- (id)serviceSideViewControllerClassName;
- (void)setEmailsToAddAsRecipients:(id)arg1;
- (void)setPlayerIDsToAddAsRecipients:(id)arg1;
- (id)_remote;
- (void)didGetRemoteViewController;
- (id)defaultMessage;
- (void)addRecipientsWithEmailAddresses:(id)arg1;
- (void)addRecipientsWithPlayerIDs:(id)arg1;
- (void)setRid:(id)arg1;
- (id)rid;
- (void)setDefaultMessage:(id)arg1;
- (void)setTheme:(id)arg1;
- (id)theme;
- (void)dealloc;

@end
