/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@interface GKComposeHeaderFieldBackgroundView : UIImageView  {
    unsigned int _location;
}

@property unsigned int location;


- (void)resetBackgroundImage;
- (unsigned int)location;
- (void)setLocation:(unsigned int)arg1;
- (id)init;
- (void)layoutSubviews;

@end
