/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKMultilineCellContentView, UIView;

@interface GKDualThreeLineCellContents : UIView <GKTableViewCellContents> {
    UIView *_separatorView;
    GKMultilineCellContentView *_topContents;
    GKMultilineCellContentView *_bottomContents;
}

@property(retain) GKMultilineCellContentView * topContents;
@property(retain) GKMultilineCellContentView * bottomContents;
@property struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } confirmationButtonRect;


- (id)bottomContents;
- (id)topContents;
- (void)setBottomContents:(id)arg1;
- (void)setTopContents:(id)arg1;
- (float)preferredHeightForOrientation:(int)arg1;
- (void)setTheme:(id)arg1;
- (id)theme;
- (id)init;
- (void)dealloc;
- (void)prepareForReuse;
- (void)layoutSubviews;

@end
