/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@interface GKFacebookUtils : NSObject  {
}

+ (void)requestFacebookAccountWithCompletionHandler:(id)arg1;
+ (void)requestAccessTokenWithCompletionHandler:(id)arg1;


@end
