/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKFriendRequestInternal, NSString, NSDate;

@interface GKFriendRequest : NSObject  {
    GKFriendRequestInternal *_internal;
    int _status;
}

@property(readonly) NSString * playerID;
@property(readonly) NSString * message;
@property(readonly) NSDate * date;
@property int status;
@property(retain) GKFriendRequestInternal * internal;


- (id)initWithPendingFriendRequest:(id)arg1;
- (void)setInternal:(id)arg1;
- (id)internal;
- (id)initWithInternalRepresentation:(id)arg1;
- (void)setStatus:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (int)status;

@end
