/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSDate, NSString;

@interface GKFriendRequestInternal : GKInternalRepresentation  {
    NSString *_playerID;
    NSDate *_date;
    NSString *_message;
    NSString *_email;
}

@property(retain) NSString * playerID;
@property(retain) NSDate * date;
@property(retain) NSString * message;
@property(retain) NSString * email;

+ (id)codedPropertyKeys;

- (void)setPlayerID:(id)arg1;
- (id)playerID;
- (void)setEmail:(id)arg1;
- (id)email;
- (id)message;
- (void)dealloc;
- (id)date;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)setMessage:(id)arg1;
- (void)setDate:(id)arg1;

@end
