/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImageView, GKGameTitleView, GKGameRecord, GKUITheme, GKHeaderSegmentedControl;

@interface GKGameDetailHeaderViewPhone : GKGameDetailHeaderView  {
    BOOL _landscapeStyle;
    UIImageView *_iconView;
    GKGameTitleView *_titleView;
    GKGameRecord *_gameRecordLocalPlayer;
}

@property(retain) GKUITheme * theme;
@property(retain) UIImageView * iconView;
@property(retain) GKGameTitleView * titleView;
@property GKHeaderSegmentedControl * segmentedControl;
@property(retain) GKGameRecord * gameRecordLocalPlayer;


- (void)setIconView:(id)arg1;
- (void)setGameRecordLocalPlayer:(id)arg1;
- (void)setLandscapeStyle:(BOOL)arg1;
- (BOOL)landscapeStyle;
- (void)setSegmentedControl:(id)arg1;
- (BOOL)iconOnLeft;
- (void)configureTitleView;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })layoutSubviewsForBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)layoutAccessoryViewForBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)updateFromGameRecord;
- (id)gameRecordLocalPlayer;
- (id)iconView;
- (float)preferredHeightForOrientation:(int)arg1;
- (void)setTheme:(id)arg1;
- (id)theme;
- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)init;
- (void)dealloc;
- (id)segmentedControl;
- (void)prepareForReuse;
- (void)setTitleView:(id)arg1;
- (id)titleView;
- (struct CGSize { float x1; float x2; })sizeThatFits:(struct CGSize { float x1; float x2; })arg1;

@end
