/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSURL;

@interface GKImportFriendsViewController : GKServerWebViewController  {
    NSURL *_url;
}

@property(retain) NSURL * url;


- (void)processGameKitURLComponents:(id)arg1;
- (void)dealloc;
- (void)setUrl:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)url;

@end
