/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@interface GKInternalRepresentation : NSObject <NSCoding, NSCopying, NSSecureCoding> {
}

+ (id)codedPropertyKeys;
+ (id)internalRepresentation;
+ (BOOL)supportsSecureCoding;

- (id)serverRepresentation;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
