/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSArray, NSString, NSData, NSObject<OS_dispatch_group>, GKMatchRequestInternal, NSDictionary;

@interface GKMatchResponse : GKResponse  {
    NSObject<OS_dispatch_group> *_matchingGroup;
    NSString *_rid;
    NSData *_cdxTicket;
    NSArray *_relayPushes;
    NSArray *_matches;
    NSData *_sessionToken;
    int _sequence;
    int _state;
    GKMatchRequestInternal *_matchRequest;
    NSDictionary *_serverRequest;
}

@property(retain) NSString * rid;
@property(retain) NSArray * matches;
@property(retain) NSData * sessionToken;
@property(retain) NSArray * relayPushes;
@property(retain) NSData * cdxTicket;
@property NSObject<OS_dispatch_group> * matchingGroup;
@property(retain) GKMatchRequestInternal * matchRequest;
@property(retain) NSDictionary * serverRequest;
@property(readonly) int sequence;
@property int state;

+ (id)codedPropertyKeys;

- (void)setSessionToken:(id)arg1;
- (id)sessionToken;
- (void)setServerRequest:(id)arg1;
- (id)serverRequest;
- (void)setRelayPushes:(id)arg1;
- (void)setCdxTicket:(id)arg1;
- (void)setMatchingGroup:(id)arg1;
- (id)matchingGroup;
- (BOOL)transitionToState:(int)arg1;
- (int)_incrementSequence;
- (void)setMatchRequest:(id)arg1;
- (void)setMatches:(id)arg1;
- (id)relayPushes;
- (id)cdxTicket;
- (id)matches;
- (void)setRid:(id)arg1;
- (id)rid;
- (id)matchRequest;
- (int)sequence;
- (void)setState:(int)arg1;
- (int)state;
- (void)dealloc;
- (BOOL)isFinished;
- (BOOL)isCancelled;

@end
