/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIViewController;

@interface GKModalRootViewController : GKViewController  {
    UIViewController *oldRootViewController;
    id oldDelegate;
    int statusBarOrientation;
}

@property(retain) UIViewController * oldRootViewController;
@property(retain) id oldDelegate;
@property int statusBarOrientation;


- (id)oldDelegate;
- (id)oldRootViewController;
- (void)setOldDelegate:(id)arg1;
- (void)setOldRootViewController:(id)arg1;
- (void)dealloc;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)setStatusBarOrientation:(int)arg1;
- (int)statusBarOrientation;

@end
