/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIViewController;

@interface GKNavigationControllerDeferredTransitionInfo : NSObject  {
    UIViewController *_viewController;
    int _type;
    BOOL _animated;
}

@property(retain) UIViewController * viewController;
@property int type;
@property BOOL animated;


- (void)setType:(int)arg1;
- (void)setAnimated:(BOOL)arg1;
- (BOOL)animated;
- (id)viewController;
- (void)setViewController:(id)arg1;
- (int)type;

@end
