/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImage, NSString, GKPlayer;

@interface GKParticipant : NSObject  {
    GKPlayer *_player;
    int _status;
    UIImage *_image;
    BOOL _cancelBoxVisible;
    int _kind;
}

@property(retain) GKPlayer * player;
@property int status;
@property(retain) UIImage * image;
@property(readonly) NSString * title;
@property(readonly) NSString * statusString;
@property BOOL progressIndicatorVisible;
@property BOOL cancelBoxVisible;
@property int kind;


- (id)statusString;
- (BOOL)cancelBoxVisible;
- (BOOL)progressIndicatorVisible;
- (void)setCancelBoxVisible:(BOOL)arg1;
- (void)reloadWithCompletionHandler:(id)arg1;
- (void)setPlayer:(id)arg1 withCompletionHandler:(id)arg2;
- (id)player;
- (void)setPlayer:(id)arg1;
- (void)setImage:(id)arg1;
- (id)image;
- (void)setStatus:(int)arg1;
- (void)dealloc;
- (id)title;
- (id)description;
- (int)kind;
- (void)setKind:(int)arg1;
- (int)status;

@end
