/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKStoreItemInternal, UIButton, GKPurchasableGameTitleView;

@interface GKPurchasableGameDetailHeaderViewPhone : GKGameDetailHeaderViewPhone  {
    UIButton *_buyButton;
    GKStoreItemInternal *_storeItem;
}

@property(retain) GKStoreItemInternal * storeItem;
@property(retain) UIButton * buyButton;
@property(readonly) GKPurchasableGameTitleView * purchasableTitleView;


- (void)setBuyButton:(id)arg1;
- (void)updateFromStoreItem;
- (void)_showStorePage;
- (id)purchasableTitleView;
- (id)buyButton;
- (BOOL)iconOnLeft;
- (void)configureTitleView;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })layoutSubviewsForBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (int)gameIconStyle;
- (void)updateFromGameRecord;
- (void)setStoreItem:(id)arg1;
- (id)storeItem;
- (id)init;
- (void)dealloc;

@end
