/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImage;

@interface GKRotatedIconView : UIView  {
    UIImage *_image;
    BOOL _mirrored;
}

@property(retain) UIImage * image;
@property BOOL mirrored;


- (BOOL)mirrored;
- (void)setMirrored:(BOOL)arg1;
- (void)drawRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setImage:(id)arg1;
- (id)image;
- (id)init;
- (void)dealloc;

@end
