/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSString, NSRegularExpression, NSArray;

@interface GKRoute : NSObject  {
    NSRegularExpression *_regex;
    NSArray *_parameterNames;
    NSString *_scheme;
}


- (BOOL)matchesURL:(id)arg1 parameters:(id*)arg2;
- (id)nonParameterCharacterSet;
- (id)initWithString:(id)arg1 scheme:(id)arg2;
- (BOOL)matchesURL:(id)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1;

@end
