/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class UIImage, GKPlayer, GKGame, GKLeaderboardCategory;

@interface GKScoreSharingInfo : NSObject  {
    GKGame *_game;
    UIImage *_badgeImage;
    UIImage *_iconImage;
    GKPlayer *_player;
    GKLeaderboardCategory *_leaderboardCategory;
}

@property(retain) GKLeaderboardCategory * leaderboardCategory;
@property(retain) GKPlayer * player;
@property(retain) GKGame * game;
@property(retain) UIImage * badgeImage;
@property(retain) UIImage * iconImage;


- (id)subjectForEmailActivity;
- (id)itemsForActivityType:(id)arg1;
- (id)thumbnailForActivityType:(id)arg1;
- (id)initWithCategoryID:(id)arg1 forGame:(id)arg2 playerID:(id)arg3;
- (id)badgeImage;
- (void)setIconImage:(id)arg1;
- (void)setBadgeImage:(id)arg1;
- (id)leaderboardCategory;
- (void)setLeaderboardCategory:(id)arg1;
- (void)setGame:(id)arg1;
- (id)game;
- (id)player;
- (void)setPlayer:(id)arg1;
- (void)dealloc;
- (id)iconImage;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
