/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKCoreTextLabel, NSAttributedString;

@interface GKShareChallengeFooterContents : UIView <GKTableViewCellContents> {
    GKCoreTextLabel *_label;
}

@property(retain) NSAttributedString * attributedText;
@property(retain) GKCoreTextLabel * label;
@property struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } confirmationButtonRect;


- (void)setTheme:(id)arg1;
- (id)theme;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)dealloc;
- (id)label;
- (void)setLabel:(id)arg1;
- (id)attributedText;
- (void)prepareForReuse;
- (void)setAttributedText:(id)arg1;
- (void)layoutSubviews;

@end
