/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKTextField, GKSignInHeaderSection, GKSignInButtonSection, GKGame, GKSignInInputSection;

@interface GKSignInDataSource : GKSectionArrayDataSource  {
    GKTextField *_usernameField;
    GKTextField *_passwordField;
    GKGame *_game;
    GKSignInHeaderSection *_signInHeaderSection;
    GKSignInInputSection *_signInInputSection;
    GKSignInButtonSection *_signInButtonSection;
}

@property(retain) GKTextField * usernameField;
@property(retain) GKTextField * passwordField;
@property(retain) GKSignInHeaderSection * signInHeaderSection;
@property(retain) GKSignInButtonSection * signInButtonSection;
@property(retain) GKSignInInputSection * signInInputSection;
@property(retain) GKGame * game;


- (id)signInButtonSection;
- (id)signInInputSection;
- (id)signInHeaderSection;
- (void)updatePlaceholderTextForEnvironment;
- (void)setSignInButtonSection:(id)arg1;
- (void)setSignInInputSection:(id)arg1;
- (void)setSignInHeaderSection:(id)arg1;
- (void)setPasswordField:(id)arg1;
- (void)setUsernameField:(id)arg1;
- (id)usernameField;
- (id)tableView:(id)arg1 sectionAtIndex:(int)arg2;
- (void)prepareSections;
- (void)setGame:(id)arg1;
- (id)game;
- (void)dealloc;
- (id)description;
- (id)passwordField;
- (int)numberOfSectionsInTableView:(id)arg1;

@end
