/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class GKComposeHeaderField, NSString, NSArray;

@interface GKSimpleComposeController : GKBaseComposeController  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _doneHandler;

    NSString *_defaultMessage;
    NSArray *_players;
    GKComposeHeaderField *_toField;
}

@property(retain) GKComposeHeaderField * toField;
@property(retain) NSString * defaultMessage;
@property(retain) NSArray * players;
@property(copy) id doneHandler;


- (void)setToField:(id)arg1;
- (id)toField;
- (id)doneHandler;
- (void)setDoneHandler:(id)arg1;
- (void)handleDoneButton;
- (void)setupSendButton;
- (id)defaultMessage;
- (id)players;
- (void)pushOntoNavigationController:(id)arg1 withDoneHandler:(id)arg2;
- (void)setPlayers:(id)arg1;
- (void)setDefaultMessage:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

@end
