/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class GKTurnBasedMatch, NSMutableDictionary;

@interface GKTurnBasedMatchHeaderSection : GKTableSection  {
    GKTurnBasedMatch *_match;
    int _matchStyle;
    NSMutableDictionary *_players;
}

@property int matchStyle;
@property(retain) GKTurnBasedMatch * match;
@property(retain) NSMutableDictionary * players;


- (int)matchStyle;
- (id)lastTurnString;
- (void)configureContents:(id)arg1 withGameIcon:(id)arg2;
- (id)creationDateString;
- (id)playingWithString;
- (void)setMatchStyle:(int)arg1;
- (id)players;
- (void)setMatch:(id)arg1;
- (id)match;
- (int)sectionItemCountInTableView:(id)arg1;
- (void)setPlayers:(id)arg1;
- (float)tableView:(id)arg1 heightForContentRow:(int)arg2;
- (id)tableView:(id)arg1 prepareContents:(id)arg2 forCell:(id)arg3 atIndexPath:(id)arg4;
- (id)tableView:(id)arg1 reuseIdentifierForRow:(int)arg2;
- (void)dealloc;
- (id)description;
- (float)heightForHeaderInTableView:(id)arg1;

@end
