/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class <GKTurnBasedMatchmakerViewControllerDelegate>, GKTurnBasedMatchesViewController;

@interface GKTurnBasedMatchmakerViewController : UINavigationController  {
    GKTurnBasedMatchesViewController *_privateViewController;
}

@property <GKTurnBasedMatchmakerViewControllerDelegate> * turnBasedMatchmakerDelegate;
@property BOOL showExistingMatches;
@property(retain) GKTurnBasedMatchesViewController * privateViewController;


- (void)setTurnBasedMatchmakerDelegate:(id)arg1;
- (id)turnBasedMatchmakerDelegate;
- (void)setShowExistingMatches:(BOOL)arg1;
- (BOOL)showExistingMatches;
- (id)privateViewController;
- (void)setPrivateViewController:(id)arg1;
- (id)initWithMatchRequest:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)__viewControllerWillBePresented:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;

@end
