/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/GameKit.framework/GameKit
 */

@class NSDictionary, NSString, NSArray;

@interface GKURLCommand : NSObject  {
    NSString *_method;
    NSArray *_arguments;
    NSDictionary *_options;
}

@property(retain) NSString * method;
@property(retain) NSArray * arguments;
@property(retain) NSDictionary * options;


- (id)initFromURL:(id)arg1;
- (void)setMethod:(id)arg1;
- (void)dealloc;
- (void)setOptions:(id)arg1;
- (void)setArguments:(id)arg1;
- (id)arguments;
- (id)method;
- (id)options;

@end
