/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@interface HSBulkCloudArtworkInfoRequest : HSRequest  {
}

+ (id)requestWithDatabaseID:(unsigned int)arg1 itemIDs:(id)arg2 sessionID:(unsigned int)arg3;

- (id)initWithDatabaseID:(unsigned int)arg1 itemIDs:(id)arg2 sessionID:(unsigned int)arg3;
- (id)_bodyDataForItemIDs:(id)arg1 sessionID:(unsigned int)arg2;
- (id)canonicalResponseForResponse:(id)arg1;

@end
