/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@interface HSContainersRequest : HSRequest  {
    BOOL _shouldParseResponse;
}

@property BOOL shouldParseResponse;

+ (id)requestWithDatabaseID:(unsigned int)arg1;

- (void)setShouldParseResponse:(BOOL)arg1;
- (BOOL)shouldParseResponse;
- (id)initWithDatabaseID:(unsigned int)arg1;
- (id)initWithAction:(id)arg1;
- (id)canonicalResponseForResponse:(id)arg1;

@end
