/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSString, SSAccount, NSDictionary, NSURL;

@interface HSConnectionConfiguration : NSObject <HSXPCCoding, NSCopying, NSMutableCopying> {
    SSAccount *_account;
    NSDictionary *_urlBag;
    NSURL *_baseURL;
    NSString *_buildIdentifier;
    NSDictionary *_cookieHeaders;
    NSString *_userAgent;
}

@property(readonly) SSAccount * account;
@property(readonly) NSDictionary * urlBag;
@property(readonly) NSURL * baseURL;
@property(readonly) NSString * buildIdentifier;
@property(readonly) NSDictionary * cookieHeaders;
@property(readonly) NSString * userAgent;


- (id)urlBag;
- (id)_dictonaryFromXPCDictonary:(id)arg1;
- (id)_copyXPCDictonaryFromDictonary:(id)arg1;
- (id)cookieHeaders;
- (id)buildIdentifier;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)userAgent;
- (id)account;
- (id)init;
- (void)dealloc;
- (id)baseURL;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
