/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSArray;

@interface HSContainersResponse : HSResponse  {
    NSArray *containers;
}

@property(copy) NSArray * containers;


- (void)setContainers:(id)arg1;
- (id)containers;
- (void)dealloc;

@end
