/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSArray;

@interface HSGetGeniusItemsResponse : HSResponse  {
    NSArray *itemIDs;
}

@property(copy) NSArray * itemIDs;


- (void)setItemIDs:(id)arg1;
- (id)itemIDs;

@end
