/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@interface HSItemDataRequest : HSRequest  {
}

+ (id)requestWithDatabaseID:(unsigned int)arg1 itemID:(unsigned int)arg2 format:(id)arg3;

- (id)initWithDatabaseID:(unsigned int)arg1 itemID:(unsigned int)arg2 format:(id)arg3;

@end
