/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class <NSObject>, HSConnection, NSString, SSAccount;

@interface HSLibrary : NSObject  {
    SSAccount *_account;
    HSConnection *_connection;
    <NSObject> *_context;
    NSString *_name;
    BOOL _requiresPassword;
    NSString *_uniqueIdentifier;
    unsigned int _version;
}

@property(readonly) NSString * name;
@property(readonly) NSString * uniqueIdentifier;
@property(readonly) unsigned int version;
@property(readonly) BOOL requiresPassword;
@property(readonly) HSConnection * connection;
@property(retain) <NSObject> * context;


- (id)initWithConnectionConfiguration:(id)arg1;
- (id)initWithName:(id)arg1 uniqueIdentifier:(id)arg2 version:(unsigned int)arg3 baseURL:(id)arg4;
- (BOOL)requiresPassword;
- (void)setContext:(id)arg1;
- (id)context;
- (void)dealloc;
- (id)name;
- (id)uniqueIdentifier;
- (id)connection;
- (unsigned int)version;

@end
