/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSError, NSData, NSDictionary;

@interface HSResponse : NSObject  {
    struct __CFHTTPMessage { } *_CFHTTPMessage;
    NSData *_responseData;
    unsigned int _responseCode;
    NSDictionary *_responseHeaderFields;
    NSError *_error;
}

@property(readonly) unsigned int responseCode;
@property(readonly) NSDictionary * responseHeaderFields;
@property(readonly) NSData * responseData;
@property(readonly) NSError * error;
@property struct __CFHTTPMessage { }* CFHTTPMessage;

+ (id)responseWithResponse:(id)arg1;
+ (id)responseWithCode:(unsigned int)arg1 headerFields:(id)arg2 data:(id)arg3 error:(id)arg4;

- (struct __CFHTTPMessage { }*)CFHTTPMessage;
- (id)responseHeaderFields;
- (id)initWithCode:(unsigned int)arg1 headerFields:(id)arg2 data:(id)arg3 error:(id)arg4;
- (void)setCFHTTPMessage:(struct __CFHTTPMessage { }*)arg1;
- (unsigned int)responseCode;
- (id)responseData;
- (void)dealloc;
- (id)description;
- (id)error;

@end
