/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class NSString;

@interface HTTPRedirectResponse : NSObject <HTTPResponse> {
    NSString *redirectPath;
}


- (void)dealloc;
- (void)setOffset:(unsigned long long)arg1;
- (unsigned long long)offset;
- (id)readDataOfLength:(unsigned int)arg1;
- (id)initWithPath:(id)arg1;
- (id)httpHeaders;
- (int)status;
- (BOOL)isDone;
- (unsigned long long)contentLength;

@end
