/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class NSString, HTTPConnection;

@interface HTTPFileResponse : NSObject <HTTPResponse> {
    HTTPConnection *connection;
    NSString *filePath;
    unsigned long long fileLength;
    unsigned long long fileOffset;
    BOOL aborted;
    int fileFD;
    void *buffer;
    unsigned int bufferSize;
}


- (void)dealloc;
- (id)filePath;
- (void)setOffset:(unsigned long long)arg1;
- (unsigned long long)offset;
- (id)readDataOfLength:(unsigned int)arg1;
- (BOOL)openFile;
- (id)initWithFilePath:(id)arg1 forConnection:(id)arg2;
- (BOOL)isDone;
- (unsigned long long)contentLength;
- (BOOL)openFileIfNeeded;
- (void)abort;

@end
