/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@interface HTTPMessage : NSObject  {
    struct __CFHTTPMessage { } *message;
}


- (void)dealloc;
- (id)body;
- (void)setBody:(id)arg1;
- (id)url;
- (id)allHeaderFields;
- (id)version;
- (id)method;
- (BOOL)appendData:(id)arg1;
- (int)statusCode;
- (id)initRequestWithMethod:(id)arg1 URL:(id)arg2 version:(id)arg3;
- (id)messageData;
- (id)initResponseWithStatusCode:(int)arg1 description:(id)arg2 version:(id)arg3;
- (BOOL)isHeaderComplete;
- (void)setHeaderField:(id)arg1 value:(id)arg2;
- (id)initEmptyRequest;
- (id)headerField:(id)arg1;

@end
