/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class NSData;

@interface HTTPDataResponse : NSObject <HTTPResponse> {
    unsigned int offset;
    NSData *data;
}


- (void)dealloc;
- (void)setOffset:(unsigned long long)arg1;
- (unsigned long long)offset;
- (id)readDataOfLength:(unsigned int)arg1;
- (id)initWithData:(id)arg1;
- (BOOL)isDone;
- (unsigned long long)contentLength;

@end
