/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

@class NSString;

@interface ICSDate : ICSProperty  {
}

@property(retain) NSString * tzid;


- (id)initWithYear:(int)arg1 month:(int)arg2 day:(int)arg3;
- (id)initWithYear:(int)arg1 month:(int)arg2 day:(int)arg3 hour:(int)arg4 minute:(int)arg5 second:(int)arg6;
- (void)setTzid:(id)arg1;
- (id)tzid;
- (BOOL)hasTimeComponent;
- (id)initWithValue:(id)arg1;
- (BOOL)hasFloatingTimeZone;
- (id)description;
- (id)components;
- (id)initWithYear:(int)arg1 month:(int)arg2 day:(int)arg3 hour:(int)arg4 minute:(int)arg5 second:(int)arg6 timeZone:(id)arg7;

@end
