/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMDaemonCore.framework/IMDaemonCore
 */

@class IMDService, NSString, IMDServiceSession, NSDictionary, NSMutableDictionary;

@interface IMDAccount : NSObject <IMSystemMonitorListener> {
    NSMutableDictionary *_accountDefaults;
    NSString *_account;
    IMDService *_service;
    IMDServiceSession *_session;
    NSMutableDictionary *_myStatus;
    NSDictionary *_lastPostedStatus;
    BOOL _isLoading;
    BOOL _isManaged;
}

@property BOOL isLoading;
@property(readonly) NSDictionary * accountDefaults;
@property(readonly) NSString * accountID;
@property(readonly) NSString * loginID;
@property(readonly) IMDService * service;
@property(readonly) IMDServiceSession * session;
@property(readonly) BOOL isActive;
@property(readonly) BOOL isDisabled;
@property BOOL wasDisabledAutomatically;
@property BOOL isManaged;
@property(readonly) NSDictionary * status;
@property(readonly) NSDictionary * statusToSave;
@property(readonly) NSDictionary * statusToPost;
@property(readonly) NSDictionary * accountInfoToPost;
@property(readonly) BOOL shouldPublishNowPlaying;
@property(readonly) int registrationStatus;
@property(readonly) int registrationError;
@property(readonly) NSDictionary * registrationAlertInfo;


- (id)registrationAlertInfo;
- (int)registrationError;
- (id)loginID;
- (void)setRegistrationStatus:(int)arg1 error:(int)arg2 alertInfo:(id)arg3;
- (void)tunesController:(id)arg1 playerInfoChanged:(id)arg2;
- (id)statusToSave;
- (void)releaseSession;
- (void)createSessionIfNecessary;
- (id)accountInfoToPost;
- (void)postAccountCapabilities;
- (void)setIsManaged:(BOOL)arg1;
- (id)initWithAccountID:(id)arg1 defaults:(id)arg2 service:(id)arg3;
- (id)_registrationInfo;
- (void)_updateIdle;
- (void)changeStatus:(id)arg1;
- (BOOL)shouldPublishNowPlaying;
- (void)setWasDisabledAutomatically:(BOOL)arg1;
- (BOOL)wasDisabledAutomatically;
- (id)statusToPost;
- (void)postAccountCapabilitiesToListener:(id)arg1;
- (id)accountDefaults;
- (void)writeAccountDefaults:(id)arg1;
- (BOOL)isManaged;
- (int)registrationStatus;
- (void)setIsLoading:(BOOL)arg1;
- (id)session;
- (BOOL)isActive;
- (void)systemDidBecomeUnidle;
- (void)systemDidBecomeIdle;
- (id)service;
- (id)accountID;
- (BOOL)isLoading;
- (BOOL)isDisabled;
- (void)dealloc;
- (id)status;

@end
