/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class <IMFileCopierDelegate>, NSURL;

@interface IMFileCopier : NSObject  {
    <IMFileCopierDelegate> *_delegate;
    NSURL *_inputURL;
    NSURL *_outputURL;
    id _identifier;
    BOOL _shouldCancel;
    BOOL _didErrorOccur;
    BOOL _inProgress;
    unsigned int _operation;
    void *_BOMCopier;
}

@property <IMFileCopierDelegate> * delegate;
@property(readonly) NSURL * inputURL;
@property(readonly) NSURL * outputURL;
@property(readonly) id identifier;
@property(readonly) BOOL wasCancelled;
@property(readonly) BOOL didErrorOccur;
@property void* _BOMCopier;
@property BOOL inProgress;
@property unsigned int operation;


- (void)set_BOMCopier:(void*)arg1;
- (void*)_BOMCopier;
- (void)setOperation:(unsigned int)arg1;
- (unsigned int)operation;
- (void)setInProgress:(BOOL)arg1;
- (BOOL)inProgress;
- (BOOL)didErrorOccur;
- (BOOL)wasCancelled;
- (void)_main_copierFinishedWithResult:(id)arg1;
- (id)outputURL;
- (void)_worker_doCopy;
- (id)_temporaryCopierPath;
- (id)inputURL;
- (void)_fillOutputURLFromInputURL;
- (id)initWithInputURL:(id)arg1 outputURL:(id)arg2 identifier:(id)arg3 operation:(unsigned int)arg4 delegate:(id)arg5;
- (void)dealloc;
- (void)start;
- (id)identifier;
- (void)cancel;
- (void)cleanup;
- (void)setDelegate:(id)arg1;
- (id)delegate;

@end
