/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class ACAccountStore, NSMutableSet;

@interface IMPasswordManager : NSObject  {
    NSMutableSet *_runningQueries;
    ACAccountStore *_accountStore;
}

+ (id)_loginUserNotificationForService:(id)arg1 user:(id)arg2 isForBadPassword:(BOOL)arg3 showForgetPassword:(BOOL)arg4;
+ (id)sharedInstance;

- (void)cancelRequestID:(id)arg1;
- (void)requestAuthTokenForUsername:(id)arg1 service:(id)arg2 badPassword:(BOOL)arg3 showForgotPassword:(BOOL)arg4 outRequestID:(id*)arg5 completionBlock:(id)arg6;
- (BOOL)supportsAuthTokenRequests;
- (void)requestPasswordForUsername:(id)arg1 service:(id)arg2 badPassword:(BOOL)arg3 showForgotPassword:(BOOL)arg4 outRequestID:(id*)arg5 completionBlock:(id)arg6;
- (void)setAuthTokenForUsername:(id)arg1 service:(id)arg2 authToken:(id)arg3 outRequestID:(id*)arg4 completionBlock:(id)arg5;
- (void)setPasswordForUsername:(id)arg1 service:(id)arg2 password:(id)arg3 outRequestID:(id*)arg4 completionBlock:(id)arg5;
- (void)fetchPasswordForUsername:(id)arg1 service:(id)arg2 outRequestID:(id*)arg3 completionBlock:(id)arg4;
- (void)fetchAuthTokenForUsername:(id)arg1 service:(id)arg2 outRequestID:(id*)arg3 completionBlock:(id)arg4;
- (id)init;
- (void)dealloc;

@end
