/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@class NSMutableArray, NSArray;

@interface IMPeopleCollection : IMPeople  {
    NSMutableArray *_collectedPeople;
}

@property(readonly) NSArray * collectedIMPeople;
@property NSMutableArray * _collectedPeople;


- (void)set_collectedPeople:(id)arg1;
- (BOOL)containsPerson:(id)arg1;
- (void)removeIMPeople:(id)arg1;
- (void)addIMPeople:(id)arg1;
- (BOOL)collectsIMPeople:(id)arg1;
- (id)collectedIMPeople;
- (void)_collectionNotification:(id)arg1;
- (id)_collectedPeople;
- (id)people;
- (id)groups;
- (id)init;
- (void)dealloc;

@end
