/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
 */

@class NSArray, NSData, NSString;

@interface IMXMLParserContext : NSObject  {
    NSData *_inContentAsData;
}

@property(readonly) NSData * inContentAsData;
@property(readonly) NSString * name;
@property(readonly) NSArray * resultsForLogging;


- (id)inContent;
- (id)initWithContent:(id)arg1;
- (id)initWithContentAsData:(id)arg1;
- (id)inContentAsData;
- (void)reset;
- (id)resultsForLogging;
- (void)dealloc;
- (id)name;

@end
