/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class UILabel;

@interface InfoVC : UIViewController  {
    UILabel *webServerStatusLabel;
    UILabel *memoryLabel;
}

@property(retain) UILabel * webServerStatusLabel;
@property(retain) UILabel * memoryLabel;


- (void)dealloc;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)webServerStatusLabel;
- (id)memoryLabel;
- (void)openWebSiteAction:(id)arg1;
- (void)closeAction:(id)arg1;
- (void)setMemoryLabel:(id)arg1;
- (void)setWebServerStatusLabel:(id)arg1;
- (id)memoryInfo;

@end
