/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@interface ISMainThreadInvocationRecorder : ISInvocationRecorder  {
    BOOL _waitUntilDone;
}

@property BOOL waitUntilDone;


- (BOOL)waitUntilDone;
- (void)invokeInvocation:(id)arg1;
- (void)setWaitUntilDone:(BOOL)arg1;

@end
