/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class NSOperationQueue;

@interface ISOperationQueue : NSObject  {
    NSOperationQueue *_queue;
}

@property BOOL adjustsMaxConcurrentOperationCount;

+ (id)mainQueue;

- (void)setAdjustsMaxConcurrentOperationCount:(BOOL)arg1;
- (BOOL)adjustsMaxConcurrentOperationCount;
- (void)setMaxConcurrentOperationCount:(int)arg1;
- (id)init;
- (void)dealloc;
- (void)addOperation:(id)arg1;
- (void)setSuspended:(BOOL)arg1;
- (void)cancelAllOperations;
- (int)operationCount;
- (id)operations;
- (int)maxConcurrentOperationCount;
- (void)addOperations:(id)arg1 waitUntilFinished:(BOOL)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

@end
