/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class ISPropertyListProvider, NSDictionary;

@interface ISProcessPropertyListOperation : ISOperation  {
    ISPropertyListProvider *_dataProvider;
    NSDictionary *_propertyList;
}

@property(retain) ISPropertyListProvider * dataProvider;


- (id)initWithPropertyList:(id)arg1;
- (void)dealloc;
- (id)dataProvider;
- (void)setDataProvider:(id)arg1;
- (void)run;

@end
