/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class ISURLCacheConfiguration, NSString, NSURLCache;

@interface ISURLCache : NSObject  {
    NSURLCache *_cache;
    ISURLCacheConfiguration *_configuration;
}

@property(readonly) NSString * persistentIdentifier;
@property(readonly) unsigned int currentDiskUsage;
@property(readonly) unsigned int currentMemoryUsage;
@property(readonly) unsigned int diskCapacity;
@property(readonly) unsigned int memoryCapacity;

+ (id)cacheDirectoryPath;

- (void)saveMemoryCacheToDisk;
- (void)purgeMemoryCache;
- (void)reloadWithCacheConfiguration:(id)arg1;
- (id)initWithCacheConfiguration:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentIdentifier;
- (void)removeAllCachedResponses;
- (void)removeCachedResponseForRequest:(id)arg1;
- (void)storeCachedResponse:(id)arg1 forRequest:(id)arg2;
- (id)cachedResponseForRequest:(id)arg1;
- (unsigned int)currentDiskUsage;
- (unsigned int)currentMemoryUsage;
- (unsigned int)diskCapacity;
- (unsigned int)memoryCapacity;

@end
