/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class NSDictionary;

@interface ISUserNotification : NSObject  {
    int _allowedRetryCount;
    int _currentRetryCount;
    NSDictionary *_dictionary;
    unsigned long _optionFlags;
    NSDictionary *_userInfo;
}

@property(readonly) NSDictionary * dictionary;
@property(readonly) unsigned long optionFlags;
@property int allowedRetryCount;
@property int currentRetryCount;
@property(retain) NSDictionary * userInfo;


- (unsigned long)optionFlags;
- (id)initWithDictionary:(id)arg1 options:(unsigned long)arg2;
- (void)setCurrentRetryCount:(int)arg1;
- (int)currentRetryCount;
- (struct __CFUserNotification { }*)copyUserNotification;
- (int)allowedRetryCount;
- (void)setAllowedRetryCount:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)userInfo;
- (void)setUserInfo:(id)arg1;
- (id)dictionary;

@end
