/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/Librarian.framework/Librarian
 */

@interface LBAccountNotification : NSObject <AccountNotificationProtocol> {
}

+ (void)noteAccountChanges:(id)arg1;


@end
