/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@class NSString;

@interface MCEncryptedProfileServicePayload : MCPayload  {
    NSString *_urlString;
}

+ (id)localizedDescriptionForPayloadCount:(unsigned int)arg1;
+ (id)typeStrings;

- (id)subtitle1Label;
- (id)subtitle1Description;
- (id)initWithURLString:(id)arg1 profile:(id)arg2;
- (id)title;
- (void).cxx_destruct;
- (id)description;

@end
