/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@class CPDistributedMessagingCenter;

@interface MCMDMClient : NSObject  {
    CPDistributedMessagingCenter *_messageCenter;
}

+ (id)sharedClient;

- (void)removeManagedAppsAccordingToFlags;
- (void)simulatePush;
- (void)scheduleTokenUpdate;
- (void)notifyNewConfiguration;
- (BOOL)checkOutCheckInURL:(id)arg1 identity:(struct __SecIdentity { }*)arg2 topic:(id)arg3 signMessage:(BOOL)arg4 outError:(id*)arg5;
- (BOOL)authenticateWithCheckInURL:(id)arg1 identity:(struct __SecIdentity { }*)arg2 topic:(id)arg3 useDevelopmentAPNS:(BOOL)arg4 signMessage:(BOOL)arg5 outError:(id*)arg6;
- (id)init;
- (void).cxx_destruct;

@end
