/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@class NSArray, MCProfile, NSString;

@interface MCPayload : NSObject  {
    MCProfile *_profile;
    NSString *_type;
    NSString *_payloadDescription;
    NSString *_displayName;
    NSString *_identifier;
    NSString *_organization;
    NSString *_UUID;
    int _version;
    NSString *_persistentResourceID;
}

@property(readonly) MCProfile * profile;
@property(readonly) NSString * friendlyName;
@property(readonly) NSString * type;
@property(readonly) NSString * payloadDescription;
@property(retain) NSString * displayName;
@property(readonly) NSString * identifier;
@property(readonly) NSString * organization;
@property(readonly) NSString * UUID;
@property(readonly) int version;
@property(retain) NSString * persistentResourceID;
@property(readonly) NSArray * installationWarnings;

+ (id)wrapperPayloadDictionary;
+ (id)badFieldValueErrorWithField:(id)arg1;
+ (id)badFieldTypeErrorWithField:(id)arg1;
+ (id)payloadFromDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3;
+ (id)payloadsFromArray:(id)arg1 profile:(id)arg2 outError:(id*)arg3;
+ (id)localizedDescriptionForPayloadCount:(unsigned int)arg1;
+ (id)typeStrings;

- (void)setPersistentResourceID:(id)arg1;
- (void)setPersistentResourceID:(id)arg1;
- (id)persistentResourceID;
- (id)organization;
- (id)payloadDescription;
- (id)subtitle2Description;
- (id)subtitle2Label;
- (id)subtitle1Label;
- (id)subtitle1Description;
- (id)malformedPayloadErrorWithError:(id)arg1;
- (id)installationWarnings;
- (id)friendlyName;
- (id)stubDictionary;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (id)profile;
- (void)dealloc;
- (id)title;
- (void).cxx_destruct;
- (id)description;
- (id)UUID;
- (id)identifier;
- (id)type;
- (int)version;

@end
