/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/usr/lib/libmecabra.dylib
 */

@class NSString;

@interface MecabraSyllables : NSObject  {
    void *_syllables;
    NSString *_string;
}


- (int)syllableTypeAtIndex:(unsigned int)arg1;
- (id)syllableAtIndex:(unsigned int)arg1;
- (void*)baseObject;
- (void)dealloc;
- (id)initWithString:(id)arg1;
- (unsigned int)count;
- (id)description;

@end
