/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@interface MFCountingDataConsumer : MFNullDataConsumer  {
    unsigned int _count;
}

@property(readonly) unsigned int count;


- (unsigned int)count;
- (int)appendData:(id)arg1;

@end
