/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@interface MFEmailSet : NSMutableSet  {
    struct __CFSet { } *_set;
}

+ (id)set;

- (id)init;
- (void)dealloc;
- (BOOL)isEqualToSet:(id)arg1;
- (id)objectEnumerator;
- (id)allObjects;
- (id)initWithCapacity:(unsigned int)arg1;
- (unsigned int)countByEnumeratingWithState:(struct { unsigned long x1; id *x2; unsigned long *x3; unsigned long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned int)arg3;
- (void)removeObject:(id)arg1;
- (id)member:(id)arg1;
- (void)removeAllObjects;
- (void)addObject:(id)arg1;
- (unsigned int)count;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)isSubsetOfSet:(id)arg1;
- (BOOL)intersectsSet:(id)arg1;
- (void)setSet:(id)arg1;
- (void)intersectSet:(id)arg1;
- (void)unionSet:(id)arg1;
- (void)minusSet:(id)arg1;

@end
