/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@class NSData;

@interface MFMessageDataContainer : NSObject  {
    NSData *_data;
    BOOL _partial;
    BOOL _incomplete;
}


- (id)initWithData:(id)arg1 partial:(BOOL)arg2 incomplete:(BOOL)arg3;
- (void)dealloc;
- (id)data;
- (id)initWithData:(id)arg1;

@end
