/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableArray;

@interface MFPalette : NSObject <MFObject> {
    NSMutableArray *m_colours;
}

+ (id)paletteWithColours:(id)arg1;

- (BOOL)resize:(int)arg1;
- (BOOL)setEntries:(int)arg1 :(id)arg2;
- (id)initWithColours:(id)arg1;
- (int)selectInto:(id)arg1;
- (id)getColour:(int)arg1;
- (id)init;
- (void)dealloc;

@end
