/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPColorBalanceEffect : MFPEffect  {
    long mCyanRed;
    long mMagentaGreen;
    long mYellowBlue;
}

+ (id)GUID;

- (id)initWithCyanRed:(long)arg1 magentaGreen:(long)arg2 yellowBlue:(long)arg3;

@end
