/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPhoneBrush : MFBrush  {
}


- (BOOL)fillWithROP:(id)arg1 :(struct CGPath { }*)arg2;
- (void)fillPath:(id)arg1 :(struct CGPath { }*)arg2;

@end
