/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPHueSaturationLightnessEffect : MFPEffect  {
    long mHueChange;
    long mSaturationChange;
    long mLightnessChange;
}

+ (id)GUID;

- (id)initWithHueChange:(long)arg1 saturationChange:(long)arg2 lightnessChange:(long)arg3;

@end
