/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPhonePath : MFPath  {
    struct CGPath { } *m_path;
    int m_state;
}


- (struct CGPath { }*)getBezierPath;
- (id)initWithPath:(struct CGPath { }*)arg1 state:(int)arg2;
- (void)appendBezierPath:(struct CGPath { }*)arg1 dc:(id)arg2;
- (int)fill:(id)arg1;
- (int)widen:(id)arg1;
- (int)closeFigure;
- (int)stroke:(id)arg1;
- (int)flatten;
- (BOOL)isOpen;
- (int)state;
- (int)begin;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)end;
- (struct CGPoint { float x1; float x2; })currentPoint;
- (int)abort;

@end
