/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class TSUColor;

@interface MFPhoneSolidBrush : MFPhoneBrush  {
    TSUColor *m_colour;
}

+ (id)solidBrushWithColour:(id)arg1;

- (id)initWithColour:(id)arg1;
- (void)fillPath:(id)arg1 :(struct CGPath { }*)arg2;
- (void)dealloc;

@end
