/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class TSUColor, TSUImage;

@interface MFPImageBrush : MFPBrush  {
    TSUImage *mPhoneImage;
    TSUColor *mPhonePatternColor;
}


- (id)initWithPhoneImage:(id)arg1;
- (void)fillPath:(struct CGPath { }*)arg1 evenOddRule:(BOOL)arg2;
- (id)color;
- (void)dealloc;

@end
