/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSArray, TSUColor;

@interface MFPPathGradientBrush : MFPGradientBrush  {
    TSUColor *mCenterColor;
    struct CGPoint { 
        float x; 
        float y; 
    } mCenterPoint;
    NSArray *mSurroundColors;
    struct CGPath { } *mPath;
}


- (id)endColor;
- (id)startColor;
- (void)createShading;
- (void)setSurroundColors:(id)arg1;
- (void)setCenterPoint:(struct CGPoint { float x1; float x2; })arg1;
- (void)setCenterColor:(id)arg1;
- (void)setPath:(struct CGPath { }*)arg1;
- (void)dealloc;
- (id).cxx_construct;

@end
