/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPRedEyeCorrectionEffect : MFPEffect  {
    struct vector<CGRect, std::allocator<CGRect> > { struct _Vector_impl { struct CGRect {} *x_1_1_1; struct CGRect {} *x_1_1_2; struct CGRect {} *x_1_1_3; } x1; } *mAreas;
}

+ (id)GUID;

- (id)initWithAreas:(const struct vector<CGRect, std::allocator<CGRect> > { struct _Vector_impl { struct CGRect {} *x_1_1_1; struct CGRect {} *x_1_1_2; struct CGRect {} *x_1_1_3; } x1; }*)arg1;
- (void)dealloc;

@end
