/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@class NSString;

@interface MFRecursiveLock : NSRecursiveLock <MFLockObject> {
    NSString *_name;
    id _delegate;
}

+ (void)initialize;

- (BOOL)isLockedByMe;
- (id)initWithName:(id)arg1 andDelegate:(id)arg2;
- (id)init;
- (void)dealloc;
- (id)description;
- (BOOL)tryLock;
- (BOOL)lockBeforeDate:(id)arg1;
- (void)unlock;
- (void)lock;

@end
