/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreMIDI.framework/CoreMIDI
 */

@class MIDINetworkHost;

@interface MIDINetworkConnection : NSObject  {
    struct _MIDINetworkConnectionImpl { id x1; } *_impl;
}

@property(readonly) MIDINetworkHost * host;

+ (id)connectionWithHost:(id)arg1;

- (id)init;
- (void)dealloc;
- (id)host;

@end
