/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MIME.framework/MIME
 */

@class MimePart;

@interface MimeBody : MessageBody  {
    MimePart *_topLevelPart;
    unsigned int _preferredAlternative : 16;
    unsigned int _numAlternatives : 16;
}

+ (id)copyNewMimeBoundary;
+ (id)versionString;

- (id)firstPartPassingTest:(id)arg1;
- (id)partWithNumber:(id)arg1;
- (id)mimeSubtype;
- (void)setTopLevelPart:(id)arg1;
- (void)setPreferredAlternative:(int)arg1;
- (int)preferredAlternative;
- (id)preferredBodyPart;
- (id)topLevelPart;
- (int)numberOfAlternatives;
- (unsigned int)totalTextSize;
- (id)textHtmlPart;
- (unsigned int)numberOfAttachmentsSigned:(BOOL*)arg1 encrypted:(BOOL*)arg2;
- (BOOL)isRich;
- (BOOL)isHTML;
- (id)contentToOffset:(unsigned int)arg1 resultOffset:(unsigned int*)arg2 asHTML:(BOOL)arg3 isComplete:(BOOL*)arg4;
- (id)attachments;
- (id)init;
- (void)dealloc;
- (id)mimeType;

@end
