/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3Artist : ML3Collection  {
}

+ (id)trackForeignPersistentID;
+ (id)propertiesForGroupingKey;
+ (id)foreignPropertyForProperty:(id)arg1 entityClass:(Class)arg2;
+ (id)predisambiguatedProperties;
+ (id)databaseTable;
+ (id)joinClausesForProperty:(id)arg1;
+ (int)revisionTrackingCode;
+ (id)defaultOrderingProperties;
+ (id)allProperties;
+ (void)initialize;
+ (id)countingQueryForMPMediaEntityProperty:(id)arg1 library:(id)arg2 identifier:(long long)arg3;
+ (id)propertyForMPMediaEntityProperty:(id)arg1;

- (void)updateTrackValues:(id)arg1;

@end
