/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3BaseLocation : ML3Entity  {
}

+ (BOOL)insertionChangesLibraryContents;
+ (id)databaseTable;
+ (int)revisionTrackingCode;

- (void)enumerateOrphanedAssetsUsingBlock:(id)arg1;

@end
