/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3NegationPredicate : ML3UnaryPredicate  {
}


- (void)appendSQLToMutableString:(id)arg1 entityClass:(Class)arg2;
- (id)description;

@end
