/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@class ML3MusicLibrary, NSDictionary;

@interface ML3SpotlightQuery : NSObject  {
    ML3MusicLibrary *_library;
    NSDictionary *_options;
}


- (void)enumerateResultsForSearchString:(id)arg1 cancelHandler:(id)arg2 rowHandler:(id)arg3;
- (id)initWithLibrary:(id)arg1 options:(id)arg2;
- (void)dealloc;

@end
