/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MMCSServices.framework/MMCSServices
 */

@class NSURL, NSString, NSData;

@interface MMCSSimpleFile : NSObject  {
    int _fd;
    double _progress;
    NSString *_authToken;
    int _encryptionBehavior;
    NSString *_localPath;
    NSURL *_requestURL;
    NSString *_requestorID;
    NSString *_guid;
    unsigned long long _itemID;
    NSData *_signature;
    NSData *_fileHash;
    unsigned long long _protocolFileSize;
}

@property(retain) NSString * guid;
@property unsigned long long itemID;
@property(retain) NSURL * requestURL;
@property(retain) NSString * requestorID;
@property(retain) NSData * signature;
@property(retain) NSString * authToken;
@property(retain) NSString * localPath;
@property int fd;
@property(retain) NSData * fileHash;
@property unsigned long long protocolFileSize;
@property double progress;
@property int encryptionBehavior;


- (void)setItemID:(unsigned long long)arg1;
- (id)requestorID;
- (void)setEncryptionBehavior:(int)arg1;
- (int)encryptionBehavior;
- (void)setFd:(int)arg1;
- (int)fd;
- (void)setRequestURL:(id)arg1;
- (void)setRequestorID:(id)arg1;
- (void)setLocalPath:(id)arg1;
- (unsigned long long)itemID;
- (void)setProtocolFileSize:(unsigned long long)arg1;
- (unsigned long long)protocolFileSize;
- (void)setFileHash:(id)arg1;
- (id)fileHash;
- (void)setSignature:(id)arg1;
- (id)authToken;
- (void)setAuthToken:(id)arg1;
- (id)requestURL;
- (id)localPath;
- (void)setGuid:(id)arg1;
- (id)guid;
- (id)init;
- (void)dealloc;
- (id)description;
- (double)progress;
- (void)setProgress:(double)arg1;
- (id)signature;

@end
