/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@class NSArray;

@interface MPArrayQueueFeeder : MPQueueFeeder  {
    NSArray *_queueItems;
}

@property(readonly) NSArray * items;


- (id)copyRawItemAtIndex:(unsigned int)arg1;
- (id)playbackInfoAtIndex:(unsigned int)arg1;
- (id)pathAtIndex:(unsigned int)arg1;
- (unsigned int)itemCount;
- (id)items;
- (void)dealloc;
- (id)initWithItems:(id)arg1;

@end
