/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@class MPAVItem;

@interface MPAVControllerToAggregateDCommunicator : NSObject  {
    MPAVItem *_item;
    unsigned int _lastMediaType;
    double _playbackStartTime;
    BOOL _playbackStartTimeIsValid;
}


- (void)_updateLastMediaTypeForItem;
- (void)_stopPlaybackTimer;
- (void)_handleItemTypeAvailableNotification:(id)arg1;
- (void)_handleItemChangedNotification:(id)arg1;
- (void)_handlePlaybackStateChangedNotification:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)_startPlaybackTimer;

@end
