/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@interface MPCenteringNavigationBar : UINavigationBar  {
}


- (void)removeBackgroundImage;
- (void)addSubview:(id)arg1;
- (void)layoutSubviews;

@end
