/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@class HSCloudClient;

@interface MPCloudController : NSObject  {
    BOOL _isCloudEnabled;
    BOOL _isUpdateInProgress;
    HSCloudClient *_cloudClient;
    BOOL _isInitialImport;
}

@property(readonly) BOOL canShowCloudTracks;
@property(readonly) BOOL isCloudEnabled;
@property(readonly) BOOL hasCloudLockerAccount;
@property(readonly) BOOL isUpdateInProgress;
@property(readonly) BOOL isInitialImport;
@property(readonly) BOOL isGeniusEnabled;

+ (void)setCanObserveWiFiChanges:(BOOL)arg1;
+ (BOOL)canObserveWiFiChanges;
+ (id)sharedCloudController;
+ (BOOL)isCellularDataRestricted;

- (void)updatePlaylistWithSagaID:(unsigned long long)arg1 itemSagaIDs:(id)arg2 completionHandler:(id)arg3;
- (BOOL)isUpdateInProgress;
- (BOOL)isInitialImport;
- (BOOL)canShowCloudTracks;
- (void)removePlaylistWithSagaID:(unsigned long long)arg1 completionHandler:(id)arg2;
- (void)loadUpdateProgressWithCompletionHandler:(id)arg1;
- (void)incrementItemProperty:(id)arg1 forSagaID:(unsigned long long)arg2;
- (void)_initializeUpdateInProgressState;
- (void)addGeniusPlaylistWithName:(id)arg1 seedItemSagaIDs:(id)arg2 itemSagaIDs:(id)arg3 completionHandler:(id)arg4;
- (void)addPlaylistWithName:(id)arg1 completionHandler:(id)arg2;
- (void)loadGeniusItemsForSagaID:(unsigned long long)arg1 completionHandler:(id)arg2;
- (BOOL)hasCloudLockerAccount;
- (void)setItemProperties:(id)arg1 forSagaID:(unsigned long long)arg2;
- (BOOL)isCloudEnabled;
- (BOOL)isGeniusEnabled;
- (void)resignActive;
- (void)becomeActive;
- (id)init;
- (void)dealloc;

@end
