/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@class MPMediaItem, MPMediaQuery;

@interface MPConcreteMediaItemCollection : MPMediaItemCollection <NSCoding, NSCopying> {
    long long _identifier;
    MPMediaQuery *_itemsQuery;
    int _grouping;
    MPMediaItem *_representativeItem;
}


- (id)initWithIdentifier:(long long)arg1 itemsQuery:(id)arg2 grouping:(int)arg3;
- (id)itemsQuery;
- (void)enumerateValuesForProperties:(id)arg1 usingBlock:(id)arg2;
- (id)initWithIdentifier:(long long)arg1 valuesForProperties:(id)arg2 itemsQuery:(id)arg3 grouping:(int)arg4 representativeItemIdentifier:(long long)arg5;
- (id)representativeItem;
- (id)mediaLibrary;
- (id)valuesForProperties:(id)arg1;
- (unsigned long long)persistentID;
- (id)items;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (unsigned int)count;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)mediaTypes;
- (void)setValue:(id)arg1 forProperty:(id)arg2;
- (id)valueForProperty:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
