/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSObject<OS_dispatch_queue>;

@interface MPMediaDownloadObserver : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _progressHandler;

    NSObject<OS_dispatch_queue> *_queue;
    BOOL _hasPendingProgressHandlerExecution;
    BOOL _invalidated;
    long long _pid;
    int _retainCount;
}

@property(readonly) double downloadProgress;
@property(getter=isCurrentlyPlayable,readonly) BOOL currentlyPlayable;
@property(copy) id progressHandler;
@property(readonly) BOOL canCancel;
@property(getter=isRestoreDownload,readonly) BOOL restoreDownload;
@property(readonly) long long persistentID;

+ (id)sharedITunesStoreDownloadManager;
+ (id)newObserverForMediaItem:(id)arg1;
+ (id)newObserverForDownloadIdentifier:(id)arg1 downloadStatus:(int)arg2 itemPersistentID:(long long)arg3;
+ (id)newObserverForDownloadIdentifier:(id)arg1 downloadStatus:(int)arg2 downloadPersistentID:(long long)arg3;

- (BOOL)isCurrentlyPlayable;
- (void)_onQueue_setShouldFireProgressHandler;
- (void)_onQueue_invalidate;
- (BOOL)canCancel;
- (BOOL)isRestoreDownload;
- (long long)persistentID;
- (void)cancelDownload;
- (void)setProgressHandler:(id)arg1;
- (id)progressHandler;
- (id)init;
- (void)dealloc;
- (void)invalidate;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (double)downloadProgress;

@end
