/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@interface MPPreparingDownloadObserver : MPMediaDownloadObserver  {
}


- (void)_onQueue_invalidate;
- (id)initWithMediaItemPersistentIdentifier:(id)arg1;
- (BOOL)canCancel;
- (void)cancelDownload;
- (double)downloadProgress;

@end
