/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//MediaPlayer.framework/MediaPlayer
 */

@class MPStoreOfferContentRating, NSDictionary;

@interface MPStoreOfferMediaItem : MPNondurableMediaItem <NSCoding, NSCopying> {
    NSDictionary *_lookupCollectionPropertyValues;
    unsigned int _indexInCollectionItems;
    int _preferredStoreOfferVariant;
    MPStoreOfferContentRating *_contentRating;
}

+ (id)localRepresentativeItemPropertyForMediaProperty:(id)arg1;
+ (id)assetLookupKeyForItemMediaProperty:(id)arg1;
+ (id)offerDictionaryWithPreferredAssetDictionaryInItemResponseDictionary:(id)arg1;
+ (id)offerLookupKeyForItemMediaProperty:(id)arg1;
+ (id)itemLookupKeyForMediaProperty:(id)arg1;
+ (id)collectionLookupKeyForMediaProperty:(id)arg1;
+ (id)preferredAssetDictionaryInOfferDictionary:(id)arg1;
+ (id)mediaitemsByRemovingRestrictedContentFromMediaItems:(id)arg1;
+ (id)mediaItemsByMergingStoreOfferMediaItems:(id)arg1 localItems:(id)arg2;
+ (id)mediaItemsWithStoreLookupCollectionPropertyValues:(id)arg1 preferredStoreOfferVariant:(int)arg2;
+ (id)offerDictionariesForLookupCollectionPropertyValues:(id)arg1 itemIndex:(unsigned int)arg2;
+ (id)fallbackPropertyValues;
+ (id)contentRatingForCollectionPropertyValues:(id)arg1 itemIndex:(unsigned int)arg2;
+ (id)mediaValueForStoreLookupCollectionPropertyValues:(id)arg1 itemIndex:(unsigned int)arg2 mediaProperty:(id)arg3;
+ (BOOL)hasMediaItemValuesForStoreLookupCollectionPropertyValues:(id)arg1 itemIndex:(unsigned int)arg2;
+ (BOOL)canMergeStoreOfferMediaItemsLocalItems:(id)arg1;
+ (BOOL)canFilterByProperty:(id)arg1;

- (id)_lookupOfferDictionaries;
- (BOOL)_offeredItemAlreadyExists;
- (id)buyOfferForVariant:(int)arg1;
- (id)initWithLookupLookupCollectionPropertyValues:(id)arg1 preferredStoreOfferVariant:(int)arg2 itemID:(id)arg3 itemIndex:(unsigned int)arg4;
- (int)preferredStoreOfferVariant;
- (BOOL)isDownloadable;
- (id)mediaLibrary;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setValue:(id)arg1 forProperty:(id)arg2;
- (id)valueForProperty:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
