/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/MailServices.framework/MailServices
 */

@interface MSAccounts : MSMailDefaultService  {
}

+ (BOOL)deleteAccountsWithUniqueIdentifiers:(id)arg1 error:(id*)arg2;
+ (id)customSignatureForSendingEmailAddress:(id)arg1;
+ (void)accountValuesForKeys:(id)arg1 completionBlock:(id)arg2;
+ (BOOL)hasActiveAccounts;
+ (void)accountValuesForKeys:(id)arg1 launchMobileMail:(BOOL)arg2 completionBlock:(id)arg3;
+ (BOOL)canSendMail;

- (void)_simulateServicesMethod:(id)arg1 arguments:(id)arg2 callback:(id)arg3;
- (void)_listAccountKeys:(id)arg1 handler:(id)arg2;

@end
