/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks//CoreMediaStream.framework/CoreMediaStream
 */

@class MSAsset, MSASAlbum;

@interface MSASAssetInfoToReauthForDownload : NSObject  {
    MSAsset *_asset;
    MSASAlbum *_album;
}

@property(retain) MSAsset * asset;
@property(retain) MSASAlbum * album;


- (void)setAlbum:(id)arg1;
- (id)album;
- (void).cxx_destruct;
- (id)asset;
- (void)setAsset:(id)arg1;

@end
