/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@interface MyIP : NSObject  {
}

+ (id)sharedInstance;

- (id)ipsForInterfaces;

@end
