/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSLocale;

@interface NSAutoLocale : NSLocale  {
    NSLocale *loc;
}

+ (BOOL)supportsSecureCoding;

- (id)init;
- (void)dealloc;
- (id)initWithLocaleIdentifier:(id)arg1;
- (id)displayNameForKey:(id)arg1 value:(id)arg2;
- (id)_prefs;
- (id)objectForKey:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)_update:(id)arg1;
- (Class)classForCoder;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
