/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface NSBlock : NSObject <NSCopying> {
}


- (void)performAfterDelay:(double)arg1;
- (void)invoke;
- (id)copy;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
