/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSBlockOperation : NSOperation  {
    id _private2;
    void *_reserved2;
}

+ (id)blockOperationWithBlock:(id)arg1;

- (id)init;
- (void)dealloc;
- (void)addExecutionBlock:(id)arg1;
- (id)executionBlocks;
- (void)main;

@end
