/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSURLResponse, NSData, NSDictionary;

@interface NSCachedURLResponseInternal : NSObject  {
    NSURLResponse *response;
    NSData *data;
    NSDictionary *userInfo;
    unsigned int storagePolicy;
    struct _CFCachedURLResponse { } *_cachedURLResponse;
}


- (void)dealloc;

@end
