/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSSet;

@interface NSConcretePortCoder : NSPortCoder  {
    NSSet *whitelist;
}


- (void)dealloc;
- (BOOL)_classAllowed:(Class)arg1;
- (void)_setWhitelist:(id)arg1;

@end
