/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSInvocation, NSConnection, NSArray;

@interface NSConcreteDistantObjectRequest : NSDistantObjectRequest  {
    NSInvocation *invocation;
    NSArray *importedObjects;
    id conversation;
    unsigned int sequence;
    NSConnection *connection;
}


- (void)dealloc;
- (id)initWithInvocation:(id)arg1 conversation:(id)arg2 sequence:(unsigned int)arg3 importedObjects:(id)arg4 connection:(id)arg5;
- (void)replyWithException:(id)arg1;
- (id)conversation;
- (id)connection;
- (id)invocation;

@end
