/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteData : NSData  {
    unsigned int _isInline : 1;
    unsigned int _shouldFree : 1;
    unsigned int _hasVM : 1;
    unsigned int _retainCount : 29;
    unsigned int _length;
    unsigned int _capacity;
    void *_bytes;
    unsigned char _space[12];
}


- (id)init;
- (void)dealloc;
- (void)getBytes:(void*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (const void*)bytes;
- (unsigned int)length;
- (void)finalize;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)getBytes:(void*)arg1 length:(unsigned int)arg2;
- (void)getBytes:(void*)arg1;
- (BOOL)_bytesAreVM;
- (id)initWithBytes:(void*)arg1 length:(unsigned int)arg2 copy:(BOOL)arg3 freeWhenDone:(BOOL)arg4 bytesAreVM:(BOOL)arg5;

@end
