/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConditionLock : NSObject <NSLocking> {
    void *_priv;
}

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (id)init;
- (void)dealloc;
- (id)name;
- (void)finalize;
- (id)description;
- (int)condition;
- (void)unlockWithCondition:(int)arg1;
- (BOOL)tryLockWhenCondition:(int)arg1;
- (void)lockWhenCondition:(int)arg1;
- (BOOL)lockWhenCondition:(int)arg1 beforeDate:(id)arg2;
- (id)initWithCondition:(int)arg1;
- (BOOL)tryLock;
- (BOOL)lockBeforeDate:(id)arg1;
- (void)setName:(id)arg1;
- (void)unlock;
- (void)lock;

@end
