/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface NSDateComponents : NSObject <NSCopying, NSSecureCoding> {
}

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (BOOL)supportsSecureCoding;
+ (id)namesForComponents:(unsigned int)arg1;
+ (unsigned int)largerComponentsRelativeToComponent:(unsigned int)arg1;
+ (unsigned int)smallerComponentsRelativeToComponent:(unsigned int)arg1;
+ (unsigned int)smaller:(BOOL)arg1 componentsRelativeToComponent:(unsigned int)arg2;

- (id)init;
- (void)dealloc;
- (id)calendar;
- (void)setCalendar:(id)arg1;
- (int)nanosecond;
- (int)quarter;
- (int)weekdayOrdinal;
- (int)weekday;
- (int)yearForWeekOfYear;
- (int)weekOfMonth;
- (int)week;
- (int)weekOfYear;
- (int)second;
- (int)minute;
- (int)hour;
- (int)day;
- (BOOL)isLeapMonth;
- (int)month;
- (int)year;
- (int)era;
- (void)setNanosecond:(int)arg1;
- (void)setQuarter:(int)arg1;
- (void)setWeekdayOrdinal:(int)arg1;
- (void)setWeekday:(int)arg1;
- (void)setYearForWeekOfYear:(int)arg1;
- (void)setWeekOfMonth:(int)arg1;
- (void)setWeek:(int)arg1;
- (void)setWeekOfYear:(int)arg1;
- (void)setLeapMonth:(BOOL)arg1;
- (void)setEra:(int)arg1;
- (id)timeZone;
- (id)date;
- (void)setTimeZone:(id)arg1;
- (void)setSecond:(int)arg1;
- (void)setMinute:(int)arg1;
- (void)setHour:(int)arg1;
- (void)setDay:(int)arg1;
- (void)setMonth:(int)arg1;
- (void)setYear:(int)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setComponents:(id)arg1;
- (id)conciseDescription;
- (void)setValue:(int)arg1 forComponent:(unsigned int)arg2;
- (int)valueForComponent:(unsigned int)arg1;

@end
