/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface NSDocumentDifferenceSize : NSObject  {
    int _generationCount;
    int _changeCount;
}

@property int generationCount;
@property int changeCount;


- (int)generationCount;
- (id)description;
- (void)setChangeCount:(int)arg1;
- (void)setGenerationCount:(int)arg1;
- (int)changeCount;

@end
