/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSExpression : NSObject <NSCoding, NSCopying> {
    void *_reserved;
    unsigned int _expressionType;
}

+ (id)expressionForBlock:(id)arg1 arguments:(id)arg2;
+ (id)expressionForMinusSet:(id)arg1 with:(id)arg2;
+ (id)expressionForIntersectSet:(id)arg1 with:(id)arg2;
+ (id)expressionForUnionSet:(id)arg1 with:(id)arg2;
+ (id)expressionForFunction:(id)arg1 arguments:(id)arg2;
+ (id)expressionForKeyPath:(id)arg1;
+ (id)expressionForTernaryWithPredicate:(id)arg1 trueExpression:(id)arg2 falseExpression:(id)arg3;
+ (id)expressionForVariableNameAssignment:(id)arg1 expression:(id)arg2;
+ (id)expressionForFunction:(id)arg1 selectorName:(id)arg2 arguments:(id)arg3;
+ (id)expressionForSubquery:(id)arg1 usingIteratorVariable:(id)arg2 predicate:(id)arg3;
+ (id)expressionForAggregate:(id)arg1;
+ (id)expressionForSymbolicString:(id)arg1;
+ (id)expressionForVariable:(id)arg1;
+ (id)expressionForEvaluatedObject;
+ (id)expressionForConstantValue:(id)arg1;
+ (id)expressionWithFormat:(id)arg1;
+ (id)expressionWithFormat:(id)arg1 argumentArray:(id)arg2;
+ (id)expressionWithFormat:(id)arg1 arguments:(char *)arg2;
+ (id)_newKeyPathExpressionForString:(id)arg1;

- (id)description;
- (SEL)selector;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)_shouldUseParensWithDescription;
- (id)falseExpression;
- (id)trueExpression;
- (id)subexpression;
- (id)predicate;
- (id)operand;
- (id)function;
- (id)variable;
- (id)expressionBlock;
- (unsigned int)expressionType;
- (id)collection;
- (id)initWithExpressionType:(unsigned int)arg1;
- (id)predicateFormat;
- (id)_expressionWithSubstitutionVariables:(id)arg1;
- (void)acceptVisitor:(id)arg1 flags:(unsigned int)arg2;
- (id)expressionValueWithObject:(id)arg1 context:(id)arg2;
- (id)rightExpression;
- (id)leftExpression;
- (id)constantValue;
- (id)arguments;
- (id)keyPath;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)minimalFormInContext:(id)arg1;

@end
