/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@interface NSExternalRefCountedData : NSObject  {
    int _cd_rc;
    int _externalReferenceCount;
    struct _externalRefFlags_st { 
        unsigned int _invalidToOnes : 1; 
        unsigned int _hasTemporaryID : 1; 
        unsigned int _backgroundDealloc : 1; 
        unsigned int _reservedFlags : 1; 
        unsigned int _virtualfk_count : 14; 
        unsigned int _ordkey_count : 14; 
    } _externalRefFlags;
    id _toManyMap;
    double _birth;
}

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (void)setRelatedIDs:(id)arg1 forKey:(id)arg2 options:(unsigned int)arg3 andTimestamp:(double)arg4;
- (double)timestampForKey:(id)arg1;
- (id)relatedIDsForKey:(id)arg1;
- (unsigned int)optionsForKey:(id)arg1;
- (void)updateFromOriginalRelationshipCaches:(id)arg1;
- (void)incrementExternalReferenceCount:(int)arg1;
- (int)externalReferenceCount;
- (int)decrementRefCount;
- (void)incrementRefCount;
- (void)setRelationshipCaches:(id)arg1;
- (id)initWithOptions:(unsigned int)arg1 andTimestamp:(double)arg2;
- (id)relationshipCaches;
- (void)setTimestamp:(double)arg1;
- (double)timestamp;
- (void)dealloc;
- (unsigned int)retainCount;
- (void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (unsigned int)options;

@end
