/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSIdRunStorage : NSRunStorage  {
}

+ (void)initialize;

- (void)_reallocData:(unsigned long)arg1;
- (void)_allocData:(unsigned long)arg1;
- (void)dealloc;

@end
