/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

/* RuntimeBrowser encountered one or more ivar type encodings for a function pointer. 
   The runtime does not encode function signature information.  We use a signature of: 
           "int (*funcName)()",  where funcName might be null. 
 */

@interface NSInvocation : NSObject  {
    void *_frame;
    void *_retdata;
    id _signature;
    id _container;
    unsigned char _retainedArgs;
    unsigned char _reserved[15];
}

+ (id)_invocationWithMethodSignature:(id)arg1 frame:(void*)arg2;
+ (id)invocationWithMethodSignature:(id)arg1;
+ (id)invocationWithBlock:(id)arg1;
+ (void)executeBlock:(id)arg1;

- (void)setReturnValue:(void*)arg1;
- (id)init;
- (void)dealloc;
- (void)invokeSuper;
- (void)invokeUsingIMP:(int (*)())arg1;
- (BOOL)argumentsRetained;
- (void)invoke;
- (void)setArgument:(void*)arg1 atIndex:(int)arg2;
- (void)getArgument:(void*)arg1 atIndex:(int)arg2;
- (void)retainArguments;
- (void)setTarget:(id)arg1;
- (SEL)selector;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)_addAttachedObject:(id)arg1;
- (void)invokeWithTarget:(id)arg1;
- (id)target;
- (id)methodSignature;
- (void)getReturnValue:(void*)arg1;
- (void)setSelector:(SEL)arg1;
- (id)debugDescription;
- (BOOL)wantsReturnValue;
- (void)_webkit_invokeAndHandleException:(id)arg1;
- (int)_firstXPCProxyReplyHandlerArgumentIndex;

@end
