/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSHashTable, NSArray;

@interface NSKeyValueObservationInfo : NSObject  {
    int _retainCountMinusOne;
    NSArray *_observances;
    unsigned int _cachedHash;
    BOOL _cachedIsShareable;
    NSHashTable *_observables;
}


- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (id)description;
- (id)_initWithObservances:(id*)arg1 count:(unsigned int)arg2;

@end
