/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyPathExpression : NSFunctionExpression  {
}


- (void)dealloc;
- (id)initWithOperand:(id)arg1 andKeyPath:(id)arg2;
- (id)pathExpression;
- (id)predicateFormat;
- (id)initWithKeyPath:(id)arg1;
- (id)keyPath;

@end
