/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSLikePredicateOperator : NSMatchingPredicateOperator  {
}


- (SEL)selector;
- (BOOL)_shouldEscapeForLike;
- (id)symbol;

@end
