/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@interface NSManagedObjectID : NSObject <NSCopying> {
}

+ (void)initialize;
+ (int)version;
+ (BOOL)accessInstanceVariablesDirectly;

- (BOOL)_isPersistentStoreAlive;
- (id)_storeIdentifier;
- (id)_storeInfo1;
- (id)_referenceData;
- (id)_retainedURIString;
- (long long)_referenceData64;
- (id)entity;
- (BOOL)isTemporaryID;
- (id)persistentStore;
- (id)URIRepresentation;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
