/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@class NSDictionary, NSManagedObject;

@interface NSMergeConflict : NSObject  {
    id _source;
    id _snapshot1;
    id _snapshot2;
    id _snapshot3;
    unsigned int _newVersion;
    unsigned int _oldVersion;
}

@property(readonly) NSManagedObject * sourceObject;
@property(readonly) NSDictionary * objectSnapshot;
@property(readonly) NSDictionary * cachedSnapshot;
@property(readonly) NSDictionary * persistedSnapshot;
@property(readonly) unsigned int newVersionNumber;
@property(readonly) unsigned int oldVersionNumber;


- (id)cachedSnapshot;
- (id)objectSnapshot;
- (unsigned int)newVersionNumber;
- (unsigned int)oldVersionNumber;
- (id)persistedSnapshot;
- (id)sourceObject;
- (id)ancestorSnapshot;
- (id)initWithSource:(id)arg1 newVersion:(unsigned int)arg2 oldVersion:(unsigned int)arg3 snapshot1:(id)arg4 snapshot2:(id)arg5 snapshot3:(id)arg6;
- (id)initWithSource:(id)arg1 newVersion:(unsigned int)arg2 oldVersion:(unsigned int)arg3 cachedSnapshot:(id)arg4 persistedSnapshot:(id)arg5;
- (void)dealloc;
- (id)objectForKey:(id)arg1;
- (id)description;
- (id)valueForKey:(id)arg1;

@end
