/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSOperation : NSObject  {
    id _private;
    int _private1;
}

@property unsigned int tag;

+ (void)initialize;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;

- (id)init;
- (void)dealloc;
- (void)setObservationInfo:(void*)arg1;
- (void)start;
- (void)waitUntilFinished;
- (void)finalize;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (BOOL)isAsynchronous;
- (BOOL)isConcurrent;
- (id)__;
- (id)dependencies;
- (void)removeDependency:(id)arg1;
- (void)addDependency:(id)arg1;
- (void)waitUntilFinishedOrTimeout:(double)arg1;
- (void)setCompletionBlock:(id)arg1;
- (void)setQueuePriority:(int)arg1;
- (int)queuePriority;
- (void)cancel;
- (BOOL)isExecuting;
- (id)completionBlock;
- (void)setThreadPriority:(double)arg1;
- (double)threadPriority;
- (BOOL)isReady;
- (BOOL)isFinished;
- (id)_implicitObservationInfo;
- (void*)observationInfo;
- (void)main;
- (BOOL)isCancelled;
- (void)NSOperationAdditions_dealloc;
- (unsigned int)tag;
- (void)setTag:(unsigned int)arg1;

@end
