/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSPathStore2 : NSString  {
    unsigned int _lengthAndRefCount;
    unsigned short _characters[0];
}

+ (id)pathWithComponents:(id)arg1;
+ (id)pathStoreWithCharacters:(const unsigned short*)arg1 length:(unsigned int)arg2;

- (void)getCharacters:(unsigned short*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (unsigned short)characterAtIndex:(unsigned int)arg1;
- (unsigned int)hash;
- (unsigned int)length;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)stringByResolvingSymlinksInPath;
- (id)stringByExpandingTildeInPath;
- (id)stringByAbbreviatingWithTildeInPath;
- (id)stringByAppendingPathExtension:(id)arg1;
- (id)stringByDeletingPathExtension;
- (id)pathComponents;
- (id)stringByStandardizingPath;
- (id)stringByAppendingPathComponent:(id)arg1;
- (BOOL)isAbsolutePath;
- (BOOL)isEqualToString:(id)arg1;
- (id)pathExtension;
- (id)stringByDeletingLastPathComponent;
- (id)_stringByResolvingSymlinksInPathUsingCache:(BOOL)arg1;
- (id)_stringByStandardizingPathUsingCache:(BOOL)arg1;
- (id)lastPathComponent;

@end
