/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@class NSArray;

@interface NSPersistentStoreRequest : NSObject <NSCopying> {
    NSArray *_affectedStores;
}

+ (void)initialize;

- (void)setAffectedStores:(id)arg1;
- (id)affectedStores;
- (unsigned int)requestType;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
