/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSPlaceholderValue : NSNumber  {
    struct _NSZone { } *zoneForInstance;
}

+ (BOOL)supportsSecureCoding;

- (id)init;
- (void)dealloc;
- (const char *)objCType;
- (void)finalize;
- (unsigned int)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (id)initWithBytes:(const void*)arg1 objCType:(const char *)arg2;
- (void)getValue:(void*)arg1;
- (id)initWithCoder:(id)arg1;

@end
