/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSFileAccessNode, <NSProgressSubscriber>, NSString;

@interface NSProgressSubscriberProxy : NSObject <NSProgressSubscriber> {
    <NSProgressSubscriber> *_forwarder;
    id _subscriberID;
    NSFileAccessNode *_itemLocation;
    NSString *_appBundleIDOrNil;
}


- (void)dealloc;
- (id)description;
- (id)initWithForwarder:(id)arg1 subscriberID:(id)arg2 appBundleID:(id)arg3;
- (id)appBundleID;
- (oneway void)addPublisher:(id)arg1 forID:(id)arg2 withValues:(id)arg3 isOld:(BOOL)arg4;
- (oneway void)removePublisherForID:(id)arg1;
- (oneway void)observePublisherForID:(id)arg1 value:(id)arg2 forKey:(id)arg3 inUserInfo:(BOOL)arg4;
- (void)setItemLocation:(id)arg1;
- (id)descriptionWithIndenting:(id)arg1;

@end
