/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@interface NSScalarObjectID48 : _NSScalarObjectID  {
    unsigned long long _referenceData48_cd_rc16;
}

+ (char *)generatedNameSuffix;

- (unsigned int)retainCount;

@end
