/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSShadow : NSObject <NSCopying, NSCoding> {
    unsigned int _shadowFlags;
    id _shadowColor;
    struct CGSize { 
        float width; 
        float height; 
    } _shadowOffset;
    float _shadowBlurRadius;
}

@property struct CGSize { float x1; float x2; } shadowOffset;
@property float shadowBlurRadius;
@property(retain) id shadowColor;

+ (id)shadow;
+ (id)defaultShadowColor;
+ (void)initialize;

- (id)shadowColor;
- (struct CGSize { float x1; float x2; })shadowOffset;
- (id)initWithShadow:(id)arg1;
- (float)shadowBlurRadius;
- (void)setShadowColor:(id)arg1;
- (void)setShadowBlurRadius:(float)arg1;
- (void)setShadowOffset:(struct CGSize { float x1; float x2; })arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
