/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSSimpleAttributeDictionary;

@interface NSSimpleAttributeDictionaryEnumerator : NSEnumerator  {
    NSSimpleAttributeDictionary *dictionary;
    unsigned int nextElement;
}


- (void)dealloc;
- (id)nextObject;
- (void)finalize;
- (id)initWithAttributeDictionary:(id)arg1;

@end
