/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks//CoreData.framework/CoreData
 */

@interface NSSQLTernaryExpressionIntermediate : NSSQLExpressionIntermediate  {
}


- (id)_generateSQLForPredicate:(id)arg1 inContext:(id)arg2;
- (id)generateSQLStringInContext:(id)arg1;

@end
