/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSTask : NSObject  {
}

@property(copy) id terminationHandler;

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)launchedTaskWithLaunchPath:(id)arg1 arguments:(id)arg2;
+ (id)launchedTaskWithDictionary:(id)arg1;
+ (id)currentTaskDictionary;

- (BOOL)suspend;
- (id)standardError;
- (id)environment;
- (id)init;
- (void)setTerminationHandler:(id)arg1;
- (BOOL)isRunning;
- (id)standardOutput;
- (id)standardInput;
- (void)setStandardError:(id)arg1;
- (void)setStandardOutput:(id)arg1;
- (void)setStandardInput:(id)arg1;
- (id)launchPath;
- (int)suspendCount;
- (BOOL)resume;
- (void)terminate;
- (void)interrupt;
- (void)setLaunchPath:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setCurrentDirectoryPath:(id)arg1;
- (void)launch;
- (int)terminationReason;
- (int)terminationStatus;
- (id)terminationHandler;
- (int)processIdentifier;
- (void)setArguments:(id)arg1;
- (id)arguments;
- (id)currentDirectoryPath;

@end
