/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSURLKeyValuePair : NSObject  {
    id key;
    id value;
    unsigned int hash;
}

+ (id)pair;
+ (id)pairWithKey:(id)arg1 value:(id)arg2;

- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (void)setValue:(id)arg1;
- (void)setKey:(id)arg1;
- (id)initWithKey:(id)arg1 value:(id)arg2;
- (id)value;
- (id)key;

@end
