/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSURLConnectionDelegateProxy, NSURLAuthenticationChallenge;

@interface NSURLDownloadInternal : NSObject  {
    struct _CFURLDownload { } *cfDownload;
    struct _CFURLAuthChallenge { } *currCFChallenge;
    NSURLAuthenticationChallenge *currNSChallenge;
    NSURLConnectionDelegateProxy *proxy;
    id delegate;
    BOOL downloadActive;
}


- (void)dealloc;

@end
