/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class NSString, NSObject<OS_xpc_object>, NSXPCConnection, NSXPCInterface, NSMutableArray;

@interface NSXPCDecoder : NSXPCCoder  {
    NSMutableArray *_containers;
    NSObject<OS_xpc_object> *_oolObjects;
    NSXPCInterface *_interface;
    NSString *_replyToSelector;
    unsigned int _genericIndex;
    NSMutableArray *_allowedClasses;
    NSXPCConnection *_connection;
}

@property(retain) NSXPCInterface * interface;
@property(copy) NSString * replyToSelector;
@property NSXPCConnection * _connection;


- (void)dealloc;
- (int)decodeInt32ForKey:(id)arg1;
- (long long)decodeInt64ForKey:(id)arg1;
- (id)decodeObjectForKey:(id)arg1;
- (const char *)decodeBytesForKey:(id)arg1 returnedLength:(unsigned int*)arg2;
- (BOOL)allowsKeyedCoding;
- (void)finalize;
- (id)replyToSelector;
- (id)_decodeXPCObjectAtIndex:(id)arg1;
- (id)__objectStuff:(id)arg1;
- (void)_popContainer;
- (void)_pushContainer:(id)arg1;
- (void)set_connection:(id)arg1;
- (void)setReplyToSelector:(id)arg1;
- (void)setInterface:(id)arg1;
- (id)interface;
- (id)_initWithRootXPCObject:(id)arg1;
- (id)_topContainer;
- (id)decodeInvocation;
- (id)_connection;
- (id)decodeXPCObjectForKey:(id)arg1;
- (float)decodeFloatForKey:(id)arg1;
- (id)allowedClasses;
- (id)decodeObjectOfClasses:(id)arg1 forKey:(id)arg2;
- (BOOL)decodeBoolForKey:(id)arg1;
- (double)decodeDoubleForKey:(id)arg1;
- (int)decodeIntegerForKey:(id)arg1;
- (int)decodeIntForKey:(id)arg1;
- (id)decodeObjectOfClass:(Class)arg1 forKey:(id)arg2;
- (id)_decodeArrayOfObjectsForKey:(id)arg1;
- (BOOL)containsValueForKey:(id)arg1;
- (id)debugDescription;
- (id)decodeObject;
- (void)decodeValueOfObjCType:(const char *)arg1 at:(void*)arg2;

@end
