/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OABGroup : NSObject  {
}

+ (void)writeGroup:(id)arg1 toParentContainer:(id)arg2 state:(id)arg3;
+ (id)readGroup:(id)arg1 state:(id)arg2;


@end
