/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADSubBlip;

@interface OADBlip : NSObject  {
    unsigned long mReferenceCount;
    OADSubBlip *mMainSubBlip;
    OADSubBlip *mAltSubBlip;
}

+ (id)pathExtensionForBlipType:(int)arg1;

- (id)altSubBlip;
- (void)setAltSubBlip:(id)arg1;
- (unsigned int*)referenceCount;
- (void)setMainSubBlip:(id)arg1;
- (id)mainSubBlip;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;

@end
