/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface OADCharacterBulletProperties : OADBulletProperties  {
    NSString *mBullet;
}


- (id)bullet;
- (id)initWithBullet:(id)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;

@end
