/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADConnection : NSObject  {
    long mDrawableId;
    int mLocationIndex;
}


- (int)locationIndex;
- (long)drawableId;
- (void)setLocationIndex:(int)arg1;
- (void)setDrawableId:(long)arg1;

@end
