/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADShapeProperties, OADTextListStyle, OADTextBodyProperties;

@interface OADDefaultProperties : NSObject  {
    OADShapeProperties *mShapeProperties;
    OADTextBodyProperties *mTextBodyProperties;
    OADTextListStyle *mTextListStyle;
}


- (void)setTextListStyle:(id)arg1;
- (id)textBodyProperties;
- (void)setTextBodyProperties:(id)arg1;
- (void)setShapeProperties:(id)arg1;
- (id)textListStyle;
- (id)initWithDefaults;
- (id)shapeProperties;
- (id)init;
- (void)dealloc;

@end
