/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableDictionary;

@interface OADFontScheme : NSObject  {
    NSMutableDictionary *mMajorFont;
    NSMutableDictionary *mMinorFont;
}

+ (void)addFontEntry:(id)arg1 script:(id)arg2 typeface:(id)arg3;

- (id)minorFont;
- (unsigned int)minorFontCount;
- (id)majorFont;
- (unsigned int)majorFontCount;
- (id)majorTypefaceForScript:(id)arg1;
- (id)minorTypefaceForScript:(id)arg1;
- (id)fontForFontSchemeRef:(id)arg1;
- (BOOL)isFontSchemeRef:(id)arg1;
- (id)init;
- (void)dealloc;

@end
