/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSDictionary;

@interface OADImageRecolorInfo : NSObject  {
    NSDictionary *mColors;
    NSDictionary *mFills;
}


- (id)initWithColors:(id)arg1 fills:(id)arg2;
- (id)fills;
- (id)colors;
- (void)dealloc;

@end
