/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADRelativeRect;

@interface OADStretchTechnique : OADImageFillTechnique  {
    OADRelativeRect *mFillRect;
    BOOL mIsFillRectOverridden;
}

+ (id)defaultProperties;

- (id)fillRect;
- (BOOL)isFillRectOverridden;
- (void)setFillRect:(id)arg1;
- (id)initWithDefaults;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
