/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADSchemeColor : OADColor  {
    int mIndex;
}

+ (id)schemeColorWithIndex:(int)arg1;

- (id)initWithSchemeColorIndex:(int)arg1;
- (int)schemeColorIndex;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
