/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableArray;

@interface OADTableRow : NSObject  {
    NSMutableArray *mCells;
    float mHeight;
}


- (id)addCell;
- (id)cellAtIndex:(unsigned int)arg1;
- (unsigned int)cellCount;
- (void)setHeight:(float)arg1;
- (float)height;
- (id)init;
- (void)dealloc;

@end
