/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OCCancel : NSObject <OCCancelDelegate> {
    BOOL mIsCancelled;
    BOOL mIsQuit;
}


- (BOOL)isQuit;
- (void)quit;
- (id)init;
- (void)cancel;
- (BOOL)isCancelled;

@end
