/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OCDReader, NSData, CPImportTracing, NSURL;

@interface OCImporter : OCMapper  {
    NSURL *mURL;
    NSData *mData;
    OCDReader *mReader;
    CPImportTracing *mTracing;
    BOOL mTryAlternateReader;
}

@property(readonly) CPImportTracing * tracing;

+ (void)initialize;

- (BOOL)isXML;
- (BOOL)isDocumentEncryptedUnsupportedVersion:(BOOL*)arg1 errorMessage:(id*)arg2;
- (BOOL)tryAlternateReader;
- (BOOL)isDocumentEncryptedUnsupportedVersionHelper:(BOOL*)arg1 errorMessage:(id*)arg2 readError:(BOOL*)arg3;
- (id)tracing;
- (BOOL)setPassphrase:(id)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1;
- (BOOL)start;
- (id)filename;
- (void)setURL:(id)arg1;
- (id)initWithData:(id)arg1;

@end
