/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class ODDPresentationPoint, NSMutableArray;

@interface ODDPresentationPoint : ODDPoint  {
    ODDPresentationPoint *mParent;
    NSMutableArray *mChildren;
}


- (void)addChild:(id)arg1 order:(unsigned long)arg2;
- (void)setType:(int)arg1;
- (void)dealloc;
- (id)parent;
- (id)children;

@end
