/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface ODIArrow4 : NSObject  {
}

+ (id)pointAtIndex:(unsigned int)arg1 points:(id)arg2;
+ (BOOL)mapIdentifier:(id)arg1 state:(id)arg2;


@end
