/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableSet;

@interface PBAnimationCacheState : PDAnimationCacheState  {
    NSMutableSet *mEntranceDrawables;
    NSMutableSet *mExitDrawables;
}


- (BOOL)isValid:(id)arg1;
- (id)init;
- (void)dealloc;

@end
