/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface PBNotes : NSObject  {
}

+ (void)writeNotes:(id)arg1 targetNotesSlideId:(unsigned long)arg2 presentationState:(id)arg3;
+ (void)writeNotesMaster:(id)arg1 presentationState:(id)arg2;


@end
