/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class PBPresentationReaderState;

@interface PBOfficeArtReaderState : OABReaderState  {
    PBPresentationReaderState *mPresentationState;
}


- (id)initWithPresentationState:(id)arg1;
- (id)presentationState;

@end
