/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSMutableDictionary;

@interface PBOutlineBulletDictionary : NSObject  {
    NSMutableDictionary *mDictionary;
}


- (id)objectForSlideId:(unsigned long)arg1 textType:(int)arg2 placeholderIndex:(unsigned long)arg3;
- (id)initFromContainer:(id)arg1 objectType:(unsigned int)arg2;
- (void)dealloc;

@end
