/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
 */

@interface PLXPCShMemData : NSData  {
    void *_buffer;
    unsigned long _dataLength;
    unsigned long _bufferLength;
}


- (id)initWithXPCShmem:(id)arg1 length:(long long)arg2;
- (id)initWithXPCShmem:(id)arg1;
- (void)dealloc;
- (const void*)bytes;
- (unsigned int)length;
- (id)description;

@end
