/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@class <SBSAccelerometerDelegate>, BKSAccelerometer;

@interface SBSAccelerometer : NSObject <BKSAccelerometerDelegate> {
    <SBSAccelerometerDelegate> *_delegate;
    BKSAccelerometer *_bksMirror;
}

@property BOOL accelerometerEventsEnabled;
@property double updateInterval;
@property float xThreshold;
@property float yThreshold;
@property float zThreshold;
@property BOOL orientationEventsEnabled;
@property <SBSAccelerometerDelegate> * delegate;


- (int)currentDeviceOrientation;
- (void)accelerometer:(id)arg1 didChangeDeviceOrientation:(int)arg2;
- (void)accelerometer:(id)arg1 didAccelerateWithTimeStamp:(double)arg2 x:(float)arg3 y:(float)arg4 z:(float)arg5 eventType:(int)arg6;
- (BOOL)accelerometerEventsEnabled;
- (void)setOrientationEventsEnabled:(BOOL)arg1;
- (void)setAccelerometerEventsEnabled:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)orientationEventsEnabled;
- (void)setZThreshold:(float)arg1;
- (float)zThreshold;
- (void)setYThreshold:(float)arg1;
- (float)yThreshold;
- (void)setXThreshold:(float)arg1;
- (float)xThreshold;
- (void)setUpdateInterval:(double)arg1;
- (double)updateInterval;
- (void)setDelegate:(id)arg1;
- (id)delegate;

@end
