/* Generated by RuntimeBrowser.
   Image: /Users/steipete/Library/Application Support/iPhone Simulator/6.0/Applications/169BE991-A55A-4056-B56F-2FCCE879D4E7/OCRuntime.app/OCRuntime
 */

@class AllClasses, ClassDisplayVC, NSArray, InfoVC;

@interface TreeTVC : UITableViewController <UITableViewDataSource, UITableViewDelegate> {
    ClassDisplayVC *classDisplayVC;
    BOOL isSubLevel;
    NSArray *classStubs;
    AllClasses *allClasses;
    InfoVC *infoVC;
}

@property BOOL isSubLevel;
@property(retain) NSArray * classStubs;
@property(retain) AllClasses * allClasses;
@property(retain) ClassDisplayVC * classDisplayVC;
@property(retain) InfoVC * infoVC;


- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)isSubLevel;
- (id)classStubs;
- (void)showInfo:(id)arg1;
- (void)setIsSubLevel:(BOOL)arg1;
- (void)setClassStubs:(id)arg1;
- (id)infoVC;
- (void)setInfoVC:(id)arg1;
- (id)allClasses;
- (void)dismissModalView:(id)arg1;
- (void)showHeaderForClassName:(id)arg1;
- (id)classDisplayVC;
- (void)setAllClasses:(id)arg1;
- (void)setClassDisplayVC:(id)arg1;

@end
