/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIActivityItemProvider : NSOperation <UIActivityItemSource> {
    NSString *_status;
    id _placeholderItem;
    NSString *_activityType;
    id _providedItem;
    float _progress;
}

@property(retain) id placeholderItem;
@property(readonly) NSString * activityType;
@property(copy) NSString * status;
@property float progress;
@property(retain) id providedItem;


- (void)setStatus:(id)arg1;
- (void)dealloc;
- (void)_setActivityType:(id)arg1;
- (id)providedItem;
- (void)setProvidedItem:(id)arg1;
- (void)setPlaceholderItem:(id)arg1;
- (id)initWithPlaceholderItem:(id)arg1;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
- (id)placeholderItem;
- (id)activityType;
- (float)progress;
- (id)item;
- (void)setProgress:(float)arg1;
- (void)main;
- (id)status;

@end
