/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIActivityViewPopoverBackgroundView : _UIPopoverStandardChromeView  {
}

+ (void)useNormalContentViewInsets:(BOOL)arg1;
+ (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })contentViewInsets;

- (float)_shadowOpacity;

@end
