/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIAccessibilityElement : NSObject <UIAccessibilityIdentification> {
}

@property id accessibilityContainer;
@property BOOL isAccessibilityElement;
@property(retain) NSString * accessibilityLabel;
@property(retain) NSString * accessibilityHint;
@property(retain) NSString * accessibilityValue;
@property struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } accessibilityFrame;
@property unsigned long long accessibilityTraits;
@property(copy) NSString * accessibilityIdentifier;


- (id)initWithAccessibilityContainer:(id)arg1;

@end
