/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlphaAnimation : UIAnimation  {
    float _startAlpha;
    float _endAlpha;
}


- (float)alphaForFraction:(float)arg1;
- (void)setEndAlpha:(float)arg1;
- (void)setStartAlpha:(float)arg1;
- (float)_alphaForMultiplier:(float)arg1;
- (void)setProgress:(float)arg1;

@end
