/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UILabel;

@interface UIAlertLabeledButton : UIAlertButton  {
    UILabel *_typeLabel;
    float _titleOffset;
}

@property(readonly) UILabel * typeLabel;
@property float titleOffset;


- (void)dealloc;
- (id)typeLabel;
- (void)setTitleOffset:(float)arg1;
- (float)titleOffset;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;

@end
