/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UICollectionView, NSString, UICollectionViewLayoutAttributes;

@interface UICollectionReusableView : UIView  {
    UICollectionViewLayoutAttributes *_layoutAttributes;
    NSString *_reuseIdentifier;
    UICollectionView *_collectionView;
    struct { 
        unsigned int inUpdateAnimation : 1; 
    } _reusableViewFlags;
}

@property(readonly) NSString * reuseIdentifier;


- (void)dealloc;
- (void)applyLayoutAttributes:(id)arg1;
- (id)_collectionView;
- (void)_setInUpdateAnimation:(BOOL)arg1;
- (void)_setReuseIdentifier:(id)arg1;
- (void)willTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)didTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (BOOL)_isInUpdateAnimation;
- (id)_layoutAttributes;
- (void)_setCollectionView:(id)arg1;
- (void)_setLayoutAttributes:(id)arg1;
- (void)prepareForReuse;
- (id)reuseIdentifier;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
