/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIDictationMeterView, UIButton, UIKeyboardDicationBackground;

@interface UIDictationView : UIView  {
    UIKeyboardDicationBackground *_background;
    UIDictationMeterView *_meterView;
    UIButton *_endpointButton;
    UIButton *_endpointButtonLandscape;
    int _state;
    BOOL _keyboardInTransition;
    BOOL _automaticAppearanceWasEnabled;
}

+ (Class)dictationViewClass;
+ (struct CGSize { float x1; float x2; })layoutSize;
+ (id)activeInstance;
+ (id)sharedInstance;

- (void)setState:(int)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)dealloc;
- (struct CGPoint { float x1; float x2; })positionForShow;
- (void)applicationEnteredBackground;
- (struct CGSize { float x1; float x2; })currentScreenSize;
- (id)endpointButton;
- (struct CGPoint { float x1; float x2; })backgroundOffset;
- (id)createEndpointButtonWithRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 action:(SEL)arg2;
- (void)endpointButtonPressed;
- (BOOL)drawsOwnBackground;
- (void)returnToKeyboard;
- (void)finishReturnToKeyboard;
- (void)prepareForReturnToKeyboard;
- (id)endpointButtonImageWithRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 pressed:(BOOL)arg2;
- (BOOL)visible;
- (void)keyboardDidShow:(id)arg1;
- (struct CGPoint { float x1; float x2; })contentOffset;
- (void)show;
- (void)layoutSubviews;

@end
