/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSArray, NSString, NSMutableArray;

@interface UIKBIdentifierList : NSObject <NSCoding, NSCopying> {
    NSString *m_name;
    NSMutableArray *m_list;
    BOOL m_explicitlySpecified;
}

@property(copy) NSString * name;
@property(readonly) unsigned int count;
@property(readonly) NSArray * list;
@property BOOL explicitlySpecified;


- (id)init;
- (void)dealloc;
- (id)name;
- (unsigned int)count;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)addIdentifier:(id)arg1;
- (id)list;
- (BOOL)explicitlySpecified;
- (void)setExplicitlySpecified:(BOOL)arg1;
- (void)setName:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
