/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSEnumerator, NSDictionary;

@interface UIKBTreeLocalizedKeylistEnumerator : NSEnumerator  {
    NSDictionary *_keyplaneCache;
    NSEnumerator *_nameEnum;
}


- (void)dealloc;
- (id)nextObject;
- (id)initWithKeyplaneCache:(id)arg1;

@end
