/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIKeyboardEmoji : NSObject  {
    NSString *emojiString;
    unsigned short _glyph;
}

@property(retain) NSString * emojiString;
@property(readonly) NSString * key;
@property unsigned short glyph;

+ (id)emojiWithString:(id)arg1;

- (void)dealloc;
- (id)initWithString:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned short)glyph;
- (id)emojiString;
- (void)setGlyph:(unsigned short)arg1;
- (void)setEmojiString:(id)arg1;
- (id)key;

@end
