/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardCandidatePadInlineFloatingBackgroundView : UIView  {
    float _rowHeight;
    unsigned int _highlightedRowIndex;
    float _contentHeight;
}

@property float rowHeight;
@property unsigned int highlightedRowIndex;
@property float contentHeight;


- (void)drawRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (float)contentHeight;
- (unsigned int)highlightedRowIndex;
- (void)setHighlightedRowIndex:(unsigned int)arg1;
- (void)setContentHeight:(float)arg1;
- (float)rowHeight;
- (void)setRowHeight:(float)arg1;

@end
