/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface UIKeyboardCandidateUtilities  {
}

+ (id)candidateBarBackgroundWithHighlight:(BOOL)arg1;
+ (id)candidateScrollViewBackgroundWithHeight:(float)arg1;
+ (/* Warning: Unrecognized filer type: '' using 'void*' */ void*)initialize;
     /* Encoded args for previous method:  */



@end
