/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class CPBitmapStore, NSSet;

@interface UIKeyboardCache : NSObject  {
    CPBitmapStore *_store;
    NSSet *_layouts;
    BOOL _isCommitting;
}

+ (BOOL)enabled;
+ (id)sharedInstance;

- (id)init;
- (void)dealloc;
- (struct CGImage { }*)renderBlock:(id)arg1 forView:(id)arg2 withKey:(id)arg3 fromLayout:(id)arg4;
- (void)cacheView:(id)arg1 forKey:(id)arg2 fromLayout:(id)arg3;
- (id)uniqueLayoutsFromInputModes:(id)arg1;
- (void)displayView:(id)arg1 withKey:(id)arg2 fromLayout:(id)arg3;
- (struct CGImage { }*)cachedImageForKey:(id)arg1 fromLayout:(id)arg2;
- (void)displayView:(id)arg1 imageWidth:(float)arg2 withKey:(id)arg3 fromLayout:(id)arg4;
- (void)updateCacheForInputModes:(id)arg1;
- (void)commitTransaction;

@end
