/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardLayoutDictation : UIKeyboardLayout  {
}

+ (struct CGSize { float x1; float x2; })dictationLayoutSize;
+ (float)portraitHeight;
+ (float)landscapeHeight;

- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (BOOL)visible;
- (void)showKeyboardType:(int)arg1 withAppearance:(int)arg2;
- (void)didRotate;
- (void)layoutSubviews;

@end
