/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, NSArray;

@interface UIKeyboardInputMode : UITextInputMode  {
    NSString *primaryLanguage;
    NSString *identifier;
    NSString *softwareLayout;
    NSString *hardwareLayout;
}

@property(retain) NSString * identifier;
@property(retain) NSString * primaryLanguage;
@property(retain) NSString * softwareLayout;
@property(retain) NSString * hardwareLayout;
@property(readonly) NSArray * normalizedIdentifierLevels;

+ (id)hardwareLayoutFromIdentifier:(id)arg1;
+ (id)softwareLayoutFromIdentifier:(id)arg1;
+ (id)canonicalLanguageIdentifierFromIdentifier:(id)arg1;
+ (id)keyboardInputModeWithIdentifier:(id)arg1;

- (id)initWithIdentifier:(id)arg1;
- (void)dealloc;
- (id)softwareLayout;
- (id)normalizedIdentifierLevels;
- (void)setHardwareLayout:(id)arg1;
- (void)setSoftwareLayout:(id)arg1;
- (void)setPrimaryLanguage:(id)arg1;
- (id)hardwareLayout;
- (id)primaryLanguage;
- (void)setIdentifier:(id)arg1;
- (id)identifier;

@end
