/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIView;

@interface UILayoutContainerView : UIView <NSCoding> {
    id _delegate;
    BOOL _usesRoundedCorners;
    float _cornerRadius;
    BOOL _usesInnerShadow;
    BOOL _shadowViewsInstalled;
    UIView *_shadowView;
}

@property id delegate;
@property BOOL usesInnerShadow;
@property BOOL usesRoundedCorners;


- (void)setBounds:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)addSubview:(id)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)dealloc;
- (BOOL)usesInnerShadow;
- (BOOL)usesRoundedCorners;
- (void)_tearDownShadowViews;
- (void)_installShadowViews;
- (void)setUsesInnerShadow:(BOOL)arg1;
- (void)setUsesRoundedCorners:(BOOL)arg1;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
