/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPanGestureVelocitySample : NSObject  {
    struct CGPoint { 
        float x; 
        float y; 
    } start;
    struct CGPoint { 
        float x; 
        float y; 
    } end;
    double dt;
}

@property struct CGPoint { float x1; float x2; } start;
@property struct CGPoint { float x1; float x2; } end;
@property double dt;


- (struct CGPoint { float x1; float x2; })start;
- (void)setDt:(double)arg1;
- (double)dt;
- (void)setEnd:(struct CGPoint { float x1; float x2; })arg1;
- (void)setStart:(struct CGPoint { float x1; float x2; })arg1;
- (struct CGPoint { float x1; float x2; })end;

@end
