/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIRotationAnimation : UIAnimation  {
    float _startAngle;
    float _endAngle;
}


- (void)setEndRotationAngle:(float)arg1;
- (void)setStartRotationAngle:(float)arg1;
- (void)setProgress:(float)arg1;

@end
