/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class SLComposeViewController;

@interface UISocialActivity : UIActivity  {
    SLComposeViewController *_socialComposeViewController;
}

@property(retain) SLComposeViewController * socialComposeViewController;


- (void)dealloc;
- (void)setSocialComposeViewController:(id)arg1;
- (id)_serviceType;
- (int)_maxImageDataSize;
- (id)socialComposeViewController;
- (void)prepareWithActivityItems:(id)arg1;
- (id)activityViewController;
- (void)_cleanup;
- (BOOL)canPerformWithActivityItems:(id)arg1;
- (id)_activityImage;
- (id)activityTitle;
- (id)activityType;

@end
