/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarAnimationParameters : NSObject  {
    double _startTime;
    double _duration;
    int _curve;
}

@property double startTime;
@property double duration;
@property int curve;


- (void)setDuration:(double)arg1;
- (id)init;
- (id)initWithEmptyParameters;
- (double)startTime;
- (int)curve;
- (void)setCurve:(int)arg1;
- (void)setStartTime:(double)arg1;
- (id)initWithDefaultParameters;
- (double)duration;

@end
