/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarLocationItemView : UIStatusBarItemView  {
    int _iconType;
}


- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;
- (id)contentsImageForStyle:(int)arg1;

@end
