/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIView;

@interface UIStoryboardEmbedSegue : UIStoryboardSegue  {
    UIView *_containerView;
}

@property(retain) UIView * containerView;


- (void)dealloc;
- (void)setContainerView:(id)arg1;
- (void)perform;
- (id)containerView;

@end
