/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UITextPosition;

@interface UITextInputArrowKeyHistory : NSObject  {
    UITextPosition *startPosition;
    int amount;
    int anchor;
    UITextPosition *start;
    UITextPosition *end;
    UITextPosition *cursor;
    BOOL affinityDownstream;
}

@property(retain) UITextPosition * startPosition;
@property int anchor;
@property(retain) UITextPosition * start;
@property(retain) UITextPosition * end;
@property(retain) UITextPosition * cursor;
@property BOOL affinityDownstream;
@property int amount;


- (id)startPosition;
- (void)dealloc;
- (id)start;
- (int)amount;
- (void)setAmount:(int)arg1;
- (void)setAffinityDownstream:(BOOL)arg1;
- (void)setCursor:(id)arg1;
- (BOOL)affinityDownstream;
- (void)setAnchor:(int)arg1;
- (int)anchor;
- (id)cursor;
- (void)setStartPosition:(id)arg1;
- (void)setEnd:(id)arg1;
- (void)setStart:(id)arg1;
- (id)end;

@end
