/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextFieldCenteredLabel : UITextFieldLabel  {
    float _textXPosition;
    float _textWidth;
}

@property float textXPosition;
@property float textWidth;


- (void)setTextWidth:(float)arg1;
- (float)textWidth;
- (void)setTextXPosition:(float)arg1;
- (float)textXPosition;
- (BOOL)isTextFieldCenteredLabel;

@end
