/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMutableArray;

@interface UIWebTouchEventsGestureRecognizer : UIGestureRecognizer  {
    id _touchTarget;
    SEL _touchAction;
    unsigned int _passedHitTest : 1;
    unsigned int _defaultPrevented : 1;
    unsigned int _inJavaScriptGesture : 1;
    float _originalGestureDistance;
    float _originalGestureAngle;
    int _type;
    struct CGPoint { 
        float x; 
        float y; 
    } _locationInWindow;
    NSMutableArray *_touchLocations;
    NSMutableArray *_touchIdentifiers;
    NSMutableArray *_touchPhases;
    float _scale;
    float _rotation;
}

@property(getter=isDefaultPrevented) BOOL defaultPrevented;
@property(readonly) int type;
@property(readonly) struct CGPoint { float x1; float x2; } locationInWindow;
@property(retain) NSMutableArray * touchLocations;
@property(retain) NSMutableArray * touchIdentifiers;
@property(retain) NSMutableArray * touchPhases;
@property(readonly) BOOL inJavaScriptGesture;
@property(readonly) float scale;
@property(readonly) float rotation;


- (id)_typeDescription;
- (id)touchPhases;
- (id)touchIdentifiers;
- (id)touchLocations;
- (struct CGPoint { float x1; float x2; })locationInWindow;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)dealloc;
- (id)description;
- (BOOL)inJavaScriptGesture;
- (void)setDefaultPrevented:(BOOL)arg1;
- (BOOL)isDefaultPrevented;
- (void)_processTouches:(id)arg1 withEvent:(id)arg2 type:(int)arg3;
- (BOOL)_hitTestTouches:(id)arg1;
- (void)_recordTouches:(id)arg1 type:(int)arg2;
- (unsigned int)_getNextTouchIdentifier;
- (id)_phasesDescription;
- (id)_identifiersDescription;
- (id)_locationsDescription;
- (id)_phaseDescription:(int)arg1;
- (void)setTouchPhases:(id)arg1;
- (void)setTouchIdentifiers:(id)arg1;
- (void)setTouchLocations:(id)arg1;
- (float)rotation;
- (void)_reset;
- (void)_resetGestureRecognizer;
- (BOOL)canBePreventedByGestureRecognizer:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (int)type;
- (float)scale;

@end
