/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIWebDocumentView;

@interface UIWebLongPressInSelectableRecognizer : UILongPressGestureRecognizer  {
    UIWebDocumentView *_documentView;
}

@property UIWebDocumentView * documentView;


- (void)setState:(int)arg1;
- (id)documentView;
- (void)setDocumentView:(id)arg1;

@end
