/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@interface WebApplicationCache : NSObject  {
}

+ (id)originsWithCache;
+ (void)deleteCacheForOrigin:(id)arg1;
+ (long long)diskUsageForOrigin:(id)arg1;
+ (void)setDefaultOriginQuota:(long long)arg1;
+ (long long)defaultOriginQuota;
+ (void)setMaximumSize:(long long)arg1;
+ (long long)maximumSize;
+ (void)initializeWithBundleIdentifier:(id)arg1;
+ (void)deleteAllApplicationCaches;


@end
