/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebCookieStorageObjCAdapter : NSObject  {
}


- (void)stopListeningForCookieChangeNotifications;
- (void)startListeningForCookieChangeNotifications;
- (void)cookiesChangedNotificationHandler:(id)arg1;
- (void)notifyCookiesChangedOnMainThread;

@end
