/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class WebFrame, WAKScrollView;

@interface WebFrameViewPrivate : NSObject  {
    WebFrame *webFrame;
    WAKScrollView *frameScrollView;
    BOOL includedInWebKitStatistics;
}


- (void)dealloc;

@end
