/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class NSArray, NSMutableDictionary, NSMutableSet;

@interface WebPluginDatabase : NSObject  {
    NSMutableDictionary *plugins;
    NSMutableSet *registeredMIMETypes;
    NSArray *plugInPaths;
    NSMutableSet *pluginInstanceViews;
}

+ (void)setAdditionalWebPlugInPaths:(id)arg1;
+ (void)closeSharedDatabase;
+ (id)_defaultPlugInPaths;
+ (id)sharedDatabase;

- (id)_plugInPaths;
- (void)destroyAllPluginInstanceViews;
- (void)removePluginInstanceViewsFor:(id)arg1;
- (void)removePluginInstanceView:(id)arg1;
- (void)addPluginInstanceView:(id)arg1;
- (BOOL)isMIMETypeRegistered:(id)arg1;
- (id)pluginForExtension:(id)arg1;
- (void)_addPlugin:(id)arg1;
- (id)_scanForNewPlugins;
- (void)_removePlugin:(id)arg1;
- (id)pluginForMIMEType:(id)arg1;
- (void)setPlugInPaths:(id)arg1;
- (id)plugins;
- (void)refresh;
- (id)init;
- (void)dealloc;
- (void)close;

@end
