/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface WebPDFNSNumberFormatter : NSNumberFormatter  {
}

+ (id)copyNumberFormater;

- (void)dealloc;

@end
