/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class NSBundle;

@interface WebPluginPackage : WebBasePluginPackage  {
    NSBundle *nsBundle;
}


- (id)bundle;
- (Class)viewFactory;
- (void)dealloc;
- (BOOL)load;
- (id)initWithPath:(id)arg1;

@end
