/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class WebPolicyDecisionListenerPrivate;

@interface WebPolicyDecisionListener : NSObject <WebPolicyDecisionListener> {
    WebPolicyDecisionListenerPrivate *_private;
}


- (void)_usePolicy:(int)arg1;
- (id)_initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)download;
- (void)ignore;
- (void)use;
- (void)dealloc;
- (void)_invalidate;
- (oneway void)_webcore_releaseOnWebThread;
- (oneway void)release;

@end
