/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@interface WebSerializedJSValuePrivate : NSObject  {
    struct RefPtr<WebCore::SerializedScriptValue> { 
        struct SerializedScriptValue {} *m_ptr; 
    } value;
}


- (void).cxx_destruct;
- (id).cxx_construct;

@end
