/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.0.sdk/System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class WebUserContentURLPatternPrivate;

@interface WebUserContentURLPattern : NSObject  {
    WebUserContentURLPatternPrivate *_private;
}


- (BOOL)matchesURL:(id)arg1;
- (BOOL)matchesSubdomains;
- (id)initWithPatternString:(id)arg1;
- (void)dealloc;
- (id)host;
- (id)scheme;
- (BOOL)isValid;

@end
